### ISSUE TITLE
Graphing of results

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#10]
Put results of test-runs into graph. Three possibilities:

1. Matplotlib standalone
2. plotinum for direct integration into ```deploy```
3. PGFplots to include the graphs directly into the LaTeX-file

**Comment by ineiti** [comment]
Matplotlib is a python-library - I can't even get it to compile with an example from the matplotlib-webpage...

**Comment by nikkolasg** [comment]
Cool with matplotlib. But what was wrong with plotinum ?

**Comment by ineiti** [comment]
Nothing - I just didn't try this out yet...

**Comment by ineiti** [comment]
Further discussion see #12
