### ISSUE TITLE
Code that rely on timeouts do not pass on Travis

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1000]
Those are: 
* `TestNodeFailure` in bftcosi, 
* `TestService_StoreSkipBlock_Failure` in skipchain and 
* `TestService_ParallelStore`
* `TestService_Propagation`

The issue is because a lot of timeouts, e.g. in protocols, expire before travis is able to finish executing the protocol, which causes many unexpected behavior. However, they should pass when running locally.

**Comment by jeffallen** [comment]
I added another exception for TestService_ParallelStore.

**Comment by ineiti** [comment]
Cleaned up and fixed most of the tests - all tests are running now on Jenkins.
