### ISSUE TITLE
Roster change can make backlinks impossible

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1045]
Consider TestClient_GetUpdateChain. It makes a skipchain that jumps from server to server, with each block getting a new roster. With base =1 maxheight =1, this works.

But if you change to this:
```
	sbs[0], err = makeGenesisRosterArgs(s, onet.NewRoster(roster.List[0:2]),
		nil, VerificationNone, 3, 2)
```

It fails with "Didn't find convenient SkipBlock for height 1" because the new lead server at that point does not have the block with index-3 in it's local DB.

**Comment by ineiti** [comment]
Fixed.
