### ISSUE TITLE
Versioning of dbs and api-messages

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1059]
We need a way to define how the databases can go from one version to another. Something like having a database-version and then being able to migrate, something like:
https://en.wikipedia.org/wiki/Schema_migration

On the other hand we should start adding version-numbers to our api-messages, so that the services can detect if an old client talks to it and then either refuse the message or reply in the previous way.

**Comment by kc1212** [comment]
We should include a version number in the database which the server reads and checks every time it starts. If an upgrade is needed, I think we should just write something from scratch. For example, back-up the database, do the upgrade (change field type for example), repeat until the database is on the latest version that it supports.

For conode-conode API, I feel the complexity will blow up if there are a lot of changes. Maybe we can deal with this issue in a more ad-hoc fashion. That is, put these version numbers on the protocol, e.g. make a propagation before anything happens and find the lowest protocol version, and then use the highest supported version by all nodes.

**Comment by ineiti** [comment]
OK, so we have three versioning systems we need to discuss:
1. db-versions - something like @kc1212 proposes seems to be OK - 
2. protocol versions - we could say that different versions of protocols simply don't talk with each other. Or even add the version of the protocol to its name, then you will only receive a 'protocol not supported'.
3. api-call versions - these are the most important ones, from my point of view, as they will be interacting with non-cothority software. For these calls I would like to have some downward compatible mode where a service can continue replying to 'old' calls.

**Comment by nikkolasg** [comment]
For 3. I think a fairly simple solution would be to rely on the protobuf extensibility functionality: You can add many fields as you want, and an old version would be still able to decrypt incoming messages only with the fields it knows.
For new functionality, then a new endpoint seems appropriate.

**Comment by jeffallen** [comment]
See b1b4f1f1b for how this now works in the context of ByzCoin's database.
