### ISSUE TITLE
Missing/Incorrect Documentation in Wiki

### ISSUE THREAD

**Issue by pablo-lo** [dedis/cothority#1063]
In https://github.com/dedis/cothority/wiki/Cisc there is content missing for some of the sections.

In https://github.com/dedis/cothority/wiki/Operating-a-Conode there is the instruction to "go get github.com/gopkg.in/dedis/cothority.v1", which should probably be "go get gopkg.in/dedis/cothority.v1"

**Comment by jeffallen** [comment]
A documentation cleanup is planned for "cothority v2", due in the coming month.
