### ISSUE TITLE
[skipchain] GetUpdateChain should return only `ForwardLinks`

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#1068]
Since a previous PR introduced the `from` and `to` and the `newRoster` field in a `ForwardLink` it is now possible to only gives back `ForwardLink` + the last skipblock when one tries to catch up to the latest skipblock. So far, the call `GetUpdateChain` is still replying with a list of `SkipBlock` and the roster is being at least duplicated...

**Comment by jeffallen** [comment]
This would be too disruptive of a change. If this becomes important for an app, we'll add a new API called GetUpdateLinks they can use. Closing until that time.
