### ISSUE TITLE
[bftSignature] weird length

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#1079]
In bft signature, using ed25519, the signature length is 65. Normally a regular eddsa signature is only 64 bytes. We don't check the exact length of the signature, only that it's large enough so it went undetected so far but we have an additional byte that should not be there... or at least that should be processed, analyzed.
The relevant file is `bftcosi/packets.go:53` (guess that should be somewhere else).

**Comment by kc1212** [comment]
My understanding is that bft signature has 64 bytes of the actual eddsa style signature and the remaining byte(s) is the mask, which is usually one byte. The same is true for cosi signatures, so sometimes you'll see code like this that drops the final byte if the mask is not needed 
https://github.com/dedis/cothority/blob/master/identity/api_test.go#L91

**Comment by kc1212** [comment]
Just to clarify, bftcosi uses the same crypto code as cosi (under cothority/cosi/crypto), so the byte representation is the same for the two. The mask is needed to handle failures. In my opinion, this more of a feature than a bug.

**Comment by nikkolasg** [comment]
Yes but (1) the mask should not be there if there is no exception, there should not be this one byte more in our test, and (2) the mask is not considered at all in the verification function of `bftSignature.Verify`.

**Comment by nikkolasg** [comment]
Maybe it's the cosi code that is at fault, it's probable, I don't really have time to check it out but there's definitely somethig fishy here that we need to investigate.

**Comment by kc1212** [comment]
The cothority cosi code has the mask, and is used in the verification. The bftcosi does indeed do things a bit differently. In the new cosi and bftcosi implementation (https://github.com/dedis/cothority/pull/1049), I'm using everything from kyber/sign/cosi, which makes the signatures consistent and removes duplicate cosi implementations. But kyber/sign/cosi also uses 64 bytes + mask.

**Comment by nikkolasg** [comment]
Great that solves the point (2). The point number one still remains, but is maybe less of a big deal (but still needs to be done, we don't want to send null bytes around). Closing the issue for now then. Thanks !
