### ISSUE TITLE
Make cothority.Suite use sha512 by default?

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1083]
The current default is sha256, but for cosi to be compatible with the eddsa format, it needs sha512. As a result, if this feature is needed, cosi will have to use a different suite than the rest of cothority. This question is raised in this discussion - https://github.com/dedis/cothority/pull/1049#discussion_r170285298

**Comment by jeffallen** [comment]
Cosi is deprecated. blscosi is using the suite's hash, which is sha256.
