### ISSUE TITLE
evoting

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1084]
When shuffling with too little users, an error is created, but not received by the js-frontend.

**Comment by gnarula** [comment]
It's got to do with how cothorityjs is handling websocket errors. https://github.com/dedis/cothority/blob/master/external/js/cothority/lib/net/net.js#L64
`event.wasClean` is false only if the client doesn't receive the closing frame [https://stackoverflow.com/a/43588055]. What we should instead be checking for is if `event.code == 4000` [https://github.com/dedis/onet/blob/master/websocket.go#L164]

**Comment by ineiti** [comment]
@gnarula - can you create a PR for that, please?

**Comment by ineiti** [comment]
Done
