### ISSUE TITLE
E-voting is pulling code from https://github.com/qantik/nevv

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1087]
Should we incorporate this code in cothority itself, or perhaps kyber? Evoting is probably going to be a long project, it'll be a good idea to keep its code under dedis. Currently the crypto package in nevv doesn't build because the blake package got changed to blake2xb. This is the root cause of https://github.com/dedis/cothority/issues/1086

**Comment by jeffallen** [comment]
Fixed in 69ec43efdcff100e11b1c5569a1317dfb0e47c7a.
