### ISSUE TITLE
Implement IPv6 support

### ISSUE THREAD

**Issue by Daeinar** [dedis/cothority#109]
Since it is to be expected that IPv4 addresses will become harder and harder to come by in the future, I guess it would make sense to have IPv6 support in the cothority framework to be independent of that "resource". I presume that the realisation of that is not too much of a trouble, as Golang's [net package](https://golang.org/pkg/net/) already supports IPv6. There might be even other reasons why we might want to have IPv6 support that I have not thought of yet. Any input is welcome.

**Comment by jeffallen** [comment]
Find out if this is easy enough to get into v2.

**Comment by jeffallen** [comment]
IPv6 on the websocket side is working correctly at this point. Setting up a test to confirm conode/conode comms work right too.

**Comment by jeffallen** [comment]
Making a server listen to *only* ipv6 requires putting it's real IPv6 address into a ListenAddress line, like this:

```
ListenAddress = "[2605:2700:0:2:a800:ff:fe50:8f79]:6800"
```

I ran a test with two servers, one with a default config (listen on v4 and v6), but advertising it's public address as v6, and another with ListenAddress to listen only on v6. They were able to communicate on the conode-conode protocol doing "conode check -g two-server.toml"
