### ISSUE TITLE
Skipchain forwardlinks

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1096]
The forward-links in the skipchain-service are created in two steps:
1. create forward-link from current latest skipblock to new proposed one
  - runs all verification functions
  - is crucial to life of skipchain
2. asks all cothorities (rosters) from backlinked blocks to sign a new forward-link
  - only verifies forward-link from 1.
  - if it fails it only means that there is a slow-down when wanting to catch up

In the current implementation, in `StoreSkipBlock`, both 1. and 2. are done on the same node, which is not possible if there was a roster-change in between.

Needed action: add a call from `StoreSkipBlock` to the leader of the backlinked block to create the forward-link.

**Comment by nikkolasg** [comment]
>  remember that if you are holding the per-skipchain lock, you cannot call back to yourself to do operations on that skipchain.

Why should we hold a lock during remote calls ? It seems super unsafe as  @jeffallen points out... Even with timeout, it's still subject to "artificial deadlock" if the timeout always repeats itself (i.e. attacker sends the right packet every 10mn so the timeout as soon as finished starts again).

**Comment by ineiti** [comment]
two things here:
1. @jeffallen - the timeout is only in `StoreSkipBlock`, so it wouldn't influence creating of higher-level forward links
2. @nikkolasg - yes, an attacker might do this. I think that sooner or later the skipchain service will have its public API removed and be only available to other services.
