### ISSUE TITLE
Fix one-off bug in app/stamp/server.go

### ISSUE THREAD

**Issue by Daeinar** [DeDiS/cothority#110]
There seems to be a one-off bug at https://github.com/DeDiS/cothority/blob/cosi_linus/app/stamp/server.go#L267. As a consequence, simulations run one round less compared to the "Rounds" value specified in the configuration .toml files.

**Comment by ineiti** [comment]
Fixed in cosi_linus - will test and close if OK.

**Comment by ineiti** [comment]
OK in cosi_linus
