### ISSUE TITLE
Do not skip tests in CI

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1108]
We are skipping some tests in Travis and may not notice failures until later. Tests taking too long or too much resources should not be a reason to skip them. It may negatively affect code quality and developer productivity. CI, in my opinion, should do as much as it can to test the code, much more than what a developer can on his/her own machine. I propose we either switch to stronger machines on Travis (if that's possible), or look at other CI solutions such as Jenkins where we can use powerful machines.

**Comment by jeffallen** [comment]
We now do more in Jenkins than in Travis.
