### ISSUE TITLE
StoreSkipBlock potentially overwrites prev when it is supplied by the Client 

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1110]
From reading the code, `prev` is overwritten on this line https://github.com/dedis/cothority/blob/4844826d4b0fc2b8402bcaa36a980e6f76b45ac9/skipchain/skipchain.go#L263 even when it is supplied by the client https://github.com/dedis/cothority/blob/4844826d4b0fc2b8402bcaa36a980e6f76b45ac9/skipchain/skipchain.go#L215

Unless I missed something, I think this is not the right behaviour. 

If the client knows the latest block and wants to add the new block after it, we should respect its wish.

**Comment by kc1212** [comment]
After some digging, this appears to be the intended behaviour (but still not sure if it's the right behaviour).

For example, in `TestClient_StoreSkipBlock`, a few lines are commented out because `StoreSkipBlock` now automatically "advances latest to the true latest block". In that regards, the current code correctly implements this logic. I initially thought if the latest block is given, then the conode should try to append the new block right after latest, otherwise fail.

**Comment by ineiti** [comment]
I think it would be correct if it advances only automatically if `LatestID == nil`.

**Comment by kc1212** [comment]
Spent over a day on this issue and I cannot find a good solution, here's why.

Simply checking if `LatestID` is null before updating `prev` breaks a lot of tests because updating the chain is a valid `LatestID` is what the tests expect. To fix the tests, they need to start sending nil `LatestID` to basically force `prev` to be updated. This also doesn't work because the service now thinks the tests are submitting genesis blocks. We can change `.Index` on the client to indicate that it is not a genesis block or check the `.GenesisID` on the server. However, I'm not a huge fan of this method because the service now needs to "predict" what the client wants by looking at what kind of combination of fields in `.NewBlock` of the `StoreSkipBlock` struct it sent. These two approach also break other tests because, for example, `.Index` is never set anywhere on the client and `.GenesisID` is also not always set. It was possible to fix these but they introduced other problems which I cannot remember anymore. I was basically going down this rabbit hole of changing one thing and see what breaks and then fixing it and see what else break and so on. I'm not sure if I'm close to the bottom yet, but I do have some ideas of how the situation can be improved.

I'm wondering whether `StoreSkipBlock` struct should have a `.NewBlock`, the client is free to populate any of the fields and the server has to "predict" what the client wants and overwrite some parts of the proposal. For example, if the client sets Index in NewBlock, should the server respects that? Right now we don't, we just overwrite it by doing `prop.Index = prev.Index + 1`. If we allow something like this, what are the fields or combination of fields that we support? I feel defining something like this is important so that we don't litter the code with `if` everywhere. Furthermore, maybe we don't need `.NewBlock` at all because it covers too much, maybe just a small number of required fields is enough. For example `Data`, `GenesisID`, `*LatestID` and `onet.Roster` and `Signature`.

While I feel this is a way forward, I'm not sure if it's the right time to make such a big change (it would change most of the tests and all the external clients), especially when v2 is coming. There are ongoing work to make skipchain clients work correctly, i.e. clients only propose transactions instead of blocks. This work would change much of the `StoreSkipBlock` logic.

Further, is automatic advancement something we must not have when `LatestID` is given? I think, to figure out whether a block if valid should not depend on `LatestID` but on the verification function. At the moment, we do not have UTXO style transaction chaining, so specifying exactly which point the block should be appended is not a requirement. Even if an application uses skipchain for UTXO style chaining, the verification should be done by the verification function. Opinions @jeffallen @ineiti ?

**Comment by ineiti** [comment]
Thanks for digging that hole! You're right that this should be refactored, and I agree that this is not the right time, as we try to fix `v2`. What I imagine the proper fix for this would be is to have two methods:

`CreateGenesis` and `AddSkipblock`

But I don't think this is a good moment to do so. We'll do it in the omniledger implementation. For now, what you propose looks good to me.

How big would the changes be to rename `LatestID` to `GenesisID` and then use that to decide if you have to create a new skipchain or simply update it? Ignoring all `Index` and `skipblock.GenesisID`?

**Comment by kc1212** [comment]
So the client must set `GenesisID` if they wish to add to a skipchain? Basically removing the optional `LatestID`. I can give that a go.

**Comment by ineiti** [comment]
Hmm - that's confusing. Now we have two `GenesisID`. Perhaps changing `LatestID` to `AddToSkipchain` would be better?
