### ISSUE TITLE
run_conode.sh greps wrong onet.go

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1151]
In order to find the Onet version, run_conode.sh greps in onet.go.

When running from gopkg.in/dedis/cothority.v2/conode, it still tries to grep onet/onet.go instead of onet.v2/onet.go: 

```
ipv6@dedis:~/go/src/gopkg.in/dedis/cothority.v2/conode$ ./run_conode.sh public
grep: /home/ipv6/go/src/github.com/dedis/onet/onet.go: No such file or directory
Didn't find private.toml in /home/ipv6/.config/conode - setting up conode
Setting up a cothority-server.
```

This whole thing needs to be rethought. See also #801.

**Comment by kc1212** [comment]
I support using dep in versioned releases
