### ISSUE TITLE
Add refusal signature to ftcosi

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1170]
If a sub-leader is malicious, it may not include any of the commit messages of its children. However, the leader has no way of detecting whether this is the case because it is possible that the verification failed on all the children.

We should introduce a new field in the commit message where the children signs a token (e.g. the message used in verification) to indicate that they refused to sign. Then, if the sub-leader does not propagate these refusal signatures back up to the leader, then the leader will know it is behaving maliciously and will propose to change the sub-leader.

**Comment by jeffallen** [comment]
Fixed in BLSCosi.
