### ISSUE TITLE
Travis fails with test

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#118]
In `lib/conode` Travis doesn't build the test `TestStamp` for an unknown reason.

**Comment by Liamsi** [comment]
The reason for that is that on travis we currently use go version 1.4.1 while locally we use 1.5.2 (or 1.5.1). I've als verified that the test fails with version 1.4.1 locally.

**Comment by Liamsi** [comment]
Now the test `TestStamp` runs fine with the branch `travis_tests_fail` (see issue #137). But two other tests fail/quit with panic:
- (fails with only with go 1.5.1) https://travis-ci.org/DeDiS/cothority/jobs/95843756#L4875
- and (fails only with with go 1.5.1 and 1.5.2) https://travis-ci.org/DeDiS/cothority/jobs/95843756#L2037
The 2nd seems related to https://groups.google.com/forum/#!topic/golang-nuts/1aZmhhSvwWc

**Comment by Liamsi** [comment]
Silenced the first by using go version 1.5.2 only (which we should do anyway) and the second by removing/commenting a line in dbug_level.go (which seems unnecessary to me anyways)  
If you want you can have a look on #137, comment/merge and close both #137 and this issue.

**Comment by ineiti** [comment]
Cool - thanks. On an administrative level, we need to decide on what to do with regard to `Issue`s and `Pull-request`s.

**Comment by ineiti** [comment]
Implemented in #137

**Comment by Liamsi** [comment]
Reopened: travis fails again

**Comment by Liamsi** [comment]
Finally, I think this can be closed once and for all
