### ISSUE TITLE
Use a typechecker in javascript projects

### ISSUE THREAD

**Issue by gnarula** [dedis/cothority#1185]
Cothority's javascript library has depends on kyber directly for ensuring runtime type safety [[1](https://github.com/dedis/cothority/blob/master/external/js/cothority/lib/identity.js#L24)]. While it's certainly useful for debugging potential issues with the way the library is being used, this is adding a potential overhead to the Cothority bundle size (750kb non gzipped minified for browser). Usually projects using the portion of cothority that use the type checks for kyber would in turn have kyber-js as a dependency of their own (to pass in a valid publicKey for instance). This duplication of modules being loaded during execution means the `instanceof` checks to ensure type safety fail at runtime. Effectively we're shipping ~350kb of kyber-js with cothority which isn't doing what it's supposed to do. We can get around by configuring webpack to not bundle kyber as a part of cothority's bundle and assume it's present in the downstream project that uses cothorityjs. However, that doesn't solve the problem in the long run.

It's probably better to resort to using a type system like [TypeScript](https://www.typescriptlang.org/) or [Flow](https://flow.org/) for the type checks. While they don't offer run time type checking, it's probably good (or arguably better) for developer productivity since we get the advantage of errors being reported during build time.

**Comment by gnarula** [comment]
Yes, here's the dependency tree:

```
cothority-js
|- kyber-js
```

Now a downstream project would look like:
```
student18_web
|- cothority-js
   |- kyber-js
|- kyber-js
```

This can be avoided by configuring webpack differently to flatten the tree to something like:
```
student18_web
|- cothority-js
|- kyber-js
```

However, kyber-js is a dependency in cothority because of some runtime checks which can be avoided if we switch to TS/Flow

**Comment by jeffallen** [comment]
Kyber is now TS as of cc8095b71b6. We will soon use it in Cothority JS.
