### ISSUE TITLE
Make Jenkins work

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1202]
Jenkins is _mostly_ working, but some of the tests, specifically the `cothority/cosi/test.sh` fail due to bad setup. Find those tests and fix them...

For `cosi/test.sh`, 1st step is to replace calls to `setupServers` with calls to `runCoBG`.

**Comment by jeffallen** [comment]
Where is Jenkins?

**Comment by ValentinMoullet** [comment]
Jenkins: http://cothority.net:8080/
