### ISSUE TITLE
Verify the new verifier list before adding a skipblock

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1243]
Jeff asked: When a conode is asked make a forward link, it runs the list of verifiers proposed in the request for a forward link. How does the signing node know that the list of verifiers it was asked to use is the correct list of verifiers for that chain, and not a shorter list of verifications from a cheating forward link requestor? bftForwardLinkLevel0 uses fs.Newest.VerifierIDs as the list of verifiers, but that seems like it is untrusted input from the network. Seems like it should be using prevSB, which is fetched from the local DB.

But doing it like that would prevent one from ever making a skipchain with evolving verifiers, which might be interesting.

Linus says: bftForwardLinkLevel0 correctly uses the `fs.Newest.VerifierID`s, but most of the time we don’t want to change the verifiers. The correct way to fix this is to add it to `verifyFuncBase`. We can imagine a skipchain that wants to change the verifiers on the go, but it’s not the `FuncBase` behaviour. So yes, it’s a bug, but I would prefer seeing it fixed in `verifyFuncBase` to leave the door open for somebody who wants it otherwise.

**Comment by jeffallen** [comment]
Assigning to @ValentinMoullet , who might find this an interesting assistant task. (If not, just unassign yourself, no prob.)

**Comment by kc1212** [comment]
I don't think we ever change the verifier ID after creating the skipchain. We also haven't had any need to change the verifiers. What I'm thinking of doing is to add a check (either in `verifyBlock` or in `bftForwardLinkLevel0`) that checks whether the verifiers have changed.
