### ISSUE TITLE
proto.awk doesn't work with type aliases and maps

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1266]
This issue was discovered while trying to convert omniledger and eventlog messages to .proto files. For example `type Action string`, `type Instructions []Instruction` and so on.

**Comment by jeffallen** [comment]
I don't understand why we do not use the brilliant "protobuf generator" part of the dedis/protobuf library.  It worked for me once before... https://godoc.org/github.com/dedis/protobuf#GenerateProtobufDefinition

**Comment by kc1212** [comment]
I didn't know it existed, if it works it's definitely something we should use instead of the awk script.

**Comment by ineiti** [comment]
If you can get this thing to work - I had troubles using it on structures with interfaces in it. Let's see if @aounleonardo finishes #1255
