### ISSUE TITLE
omniledger: Optimize creation of new block

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1273]
In dedis/student_18_omniledger#32 @ineiti says:

To have fewer round-trips, the skipchain service should get a `NewBlockAccepted` callback where services can sign up to receive a copy of every new block accepted. Then instead of using `propagateTransactions`, the omniledger service could just listen for new blocks, go through the transactions and store them in the database.

**Comment by kc1212** [comment]
Fixed in https://github.com/dedis/cothority/pull/1387, closing.
