### ISSUE TITLE
omniledger: create follower queues

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1275]
In dedis/student_18_omniledger#11, @ineiti says:

Instead of having the leader take all transactions, allow for transactions to be sent to the other nodes. This means that the leader will have to:
1. ask all nodes to send the latest transactions
2. create a block with the new transactions
3. send that block to all other nodes

**Comment by kc1212** [comment]
This is implemented in https://github.com/dedis/cothority/pull/1329, closing.
