### ISSUE TITLE
omniledger: Darc delegation should always be on the base ID

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1276]
In dedis/student_18_omniledger#59 @kc1212 says:

Currently if we do a delegation, i.e. the "sign" expression will point to another darc, that darc doesn't have to be the base darc. In OmniLedger, we only store the latest darc in the collection (where the key is the base ID), so we cannot easily find the correct darc in the "sign" expression. To solve this problem, we propose to always have the expression in "sign" refer to the base ID, then OmniLedger will be responsible for finding the latest darc under that base ID.

**Comment by kc1212** [comment]
This is fixed, see the test `byzcoin/service_test.go:TestService_DarcDelegation` where we use a DARC identity as the expression for the spawn rule:
```
darc2.Rules.AddRule("spawn:"+ContractSecureDarcID, expression.InitOrExpr(s.darc.GetIdentityString()))
```
