### ISSUE TITLE
Eventlog instance class

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1303]
The current eventlog implementation uses the eventlog-service to send logs, but it should send logs directly to omniledger. Changes needed:
1. implement an eventlog-contract in go that can spawn new events (already done, I think)
2. implement the `EventInstance` class in java that can create `Instruction`s, like `ValueInstance`
3. Write nice documentation

**Comment by kc1212** [comment]
Regarding the `Search` method, it might be possible to implement it in the contract.

**Comment by kc1212** [comment]
https://github.com/dedis/cothority/pull/1310 fixes this issue, closing
