### ISSUE TITLE
TestService_RegisterVerification is probably wrong

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1305]
While testing panics in verifiers, I tried to modify TestService_RegisterVerification and I found that it is probably wrong.

It is testing that len(ver) == 0, but the ver channel should have had writes to it. The verifier is never being called, and the test is passing as if this is desired?

The second try, where it checks that len(ServiceVerifierChan) == 1 is functioning correctly.

**Comment by kc1212** [comment]
Fixed in https://github.com/dedis/cothority/pull/1386, closing.
