### ISSUE TITLE
conode.NewPeer configuration

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#134]
For the moment conode.NewPeer only accepts ConfigConode configuration... This is not great since other people want to use their own configuration and still use NewPeer. The quickfix i've done in skeleton is to convert from one config to a configconode. We should be able to design a minimal interface that every config must implements so that NewPeer has all the info it needs. Such as Tree, Hostlist, AggPublicKey and Suite.

**Comment by nikkolasg** [comment]
Is being solved by PR #184

**Comment by ineiti** [comment]
Not relevant for SDA anymore.
