### ISSUE TITLE
Include failed transactions in blocks

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1343]
In the current implementation, clients cannot check whether their transaction failed or was censored by the leader because failed transactions are not included in the block. If we add a flag that says whether the transaction failed to verify, then the client will have some feedback so that it can submit a correct transaction next time.

There is a potential for a denial-of-service attack where a malicious node will submit a lot of invalid transactions to fill the block up with garbage data. We think this issue will be taken care of once we introduce the coins feature to OmniLedger.

**Comment by jeffallen** [comment]
This was done in 1a096059a18634c338d89dd56745e962303278e7
