### ISSUE TITLE
OmniLedger fails with too many transactions

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1347]
Currently it is very easy to DOS Omniledger by spamming it with too many transactions. We need a better way to make sure that the number of transactions is not too high for the BFTCoSi to treat all transactions.

**Comment by kc1212** [comment]
Yes, I think https://github.com/dedis/cothority/pull/1351 takes care some of it. But the issue description says "make sure that the number of transactions is not too high for the BFTCoSi", does that mean we need to have a limit on the block size?

**Comment by ineiti** [comment]
OK - a better description would be that we need to make sure that the verification time is not too high for BFTCoSi to finish in time and for the next block to appear in time.
