### ISSUE TITLE
need to use domain separation in omniledger hashing?

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1360]
When I was looking at DeriveID and also at darc.GetID(), I was reminded of the domain separation bytes that were used in kyber's Cipher AEAD before. I asked Phillipp about this and he said:

From Phillipp:
_Yeah domain separation is usually used to separate “cryptographic namespaces” so to say. The example you remembered is probably from sponge functions where domain separation is used to distinguish different types of data during processing. For example in NORX we use it to distinguish between associated data (which is not encrypted) and message data (which is encrypted), e.g., see the 0x01, 0x02, etc. in the following image:_ https://www.131002.net/data/talks/gtacs15/img/norx-D2.png

_Anyhow, I agree that it would be good to have a DARC type identifier that goes into the ID computation to ensure that IDs are always unique and thus prevent the issue you described. However, it seems that a description of the actions is going into the ID computation. Maybe that’s already enough to uniquely identify a DARC?_

We need to take a close look at the places we combine hashes and see if there are places where an attacker controls adjacent data and could try to cause a collision.

**Comment by ineiti** [comment]
I remember vaguely that there is some random input to the darc, so that even two darcs with the same rules get another ID. Perhaps it's the base-ID of the darc that is random?

**Comment by jeffallen** [comment]
See also [this comment](https://github.com/dedis/cothority/pull/1388#discussion_r208812995) from Linus.

**Comment by jeffallen** [comment]
This needs to be fixed here:

```
func (instr Instruction) Hash() []byte {
	h := sha256.New()
...
	for _, a := range args {
		h.Write([]byte(a.Name)) // these should both have lengths before them
		h.Write(a.Value)
	}
```
