### ISSUE TITLE
make test deletes cothority stable (v2)

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1397]
The last command in `make test` is
```
test -d $GOPATH/src/gopkg.in/dedis/cothority.v2 && rm -rf $GOPATH/src/gopkg.in/dedis/cothority.v2
```
This is a bit annoying when developing a project on `v2` and on master because you'd have to do `go get gopkg.in/dedis/cothority.v2` every time after the unit test completes.

**Comment by jeffallen** [comment]
To fix this, we need to modify Makefile.base in the dedis/Coding repo, so that it does something less stupid in test_stable_build:
```
test_stable_build:
        $(CREATE_STABLE) $(PKG_STABLE)
        cd $(PKG_STABLE_PATH) && go get ./... && go build ./...
        test -d $(PKG_STABLE_PATH) && rm -rf $(PKG_STABLE_PATH)
```

**Comment by jeffallen** [comment]
Stable is no longer used as of v3.
