### ISSUE TITLE
should be possible to confirm a transaction was committed

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1402]
It should be possible for clients to ask for proof that a given ClientTransaction was committed.

So we can either:
1. create another merkle tree with all the transactionIDs in it, and then get proofs there
2. search through all latest blocks and see if the transaction has been included there

Option 1 is cleaner but needs more work, while 2 is easier to implement, but takes more time on the server side.

We should also consider if GetProof should do double duty, so as to avoid adding a new method to the service. Something like GetProof(which string, key []byte) so that you can ask for proof of inclusion of a transaction (GetProof("tx", txHash)) or proof of inclusion of data into the global state (GetProof("state", key)).

The key for a transaction will be ClientTransaction.Hash(), already implemented as:
```go
// Hash returns the sha256 hash of all client transactions.
func (cts ClientTransactions) Hash() []byte {
	h := sha256.New()
	for _, ct := range cts {
		h.Write(ct.Instructions.Hash())
	}
	return h.Sum(nil)
}
```

Linus' addition: we need to take care here as the `instructions.Hash` doesn't hash the signatures. And for the `ClientTransaction.Hash` we want to hash _everything_.

**Comment by ineiti** [comment]
One simple solution is to add a `hash` method to the java api and then:

1. when calling `spawn`, returning the hash
2. polling for new blocks and verifying if the hash is inside

All within java
