### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#147]
See if all steps described in the conode [README](https://github.com/DeDiS/cothority/blob/development/app/conode/README.md)
are still valid and just work. For instance, the described `tar -xzf conode-0.6.14.tar.gz` won't work and you have to call `tar xf conode-0.6.14.tar.gz`instead)

**Comment by ineiti** [comment]
Le 16/12/2015 10:43, Ismail a écrit :
>
> See if all steps described in the conode README 
> <https://github.com/DeDiS/cothority/blob/development/app/conode/README.md>
> are still valid and just work. For instance, the described |tar -xzf 
> conode-0.6.14.tar.gz| won't work and you have to call |tar xf 
> conode-0.6.14.tar.gz|instead)
>
>
Which system failed that?

Check which `tar` implements which options on which OS. Some `tar` don't 
support the `tar xf` way. IIRC, you have Gnu and Bsd tar which behave a 
little bit differently. Again, IIRC, `tar -xzf` is the most compatible 
way. But here I go corrected.

**Comment by Liamsi** [comment]
> Which system failed that?
It failed on a linux host (centOS). Tar says: `tar (GNU tar) 1.23`. I was also wondering about that, too. It actually should work in both versions (bsd/gnu), but it doesn't (on the same host `gunzip` didn't work, too).

**Comment by Liamsi** [comment]
Note to myself: `tar -xvf ...` works on both Mac and Linux

**Comment by Liamsi** [comment]
Another note to myself: This 'onliner' (almost) can be used in scripts / slides for downloading the latest release without having to which tag/release number is the latest:
```
curl -L http://github.com/micha/jsawk/raw/master/jsawk > jsawk; chmod 700 jsawk
curl  https://api.github.com/repos/dedis/cothority/releases/latest | ./jsawk  'return (this.assets[0].browser_download_url)' | xargs wget
```

**Comment by Daeinar** [comment]
One-liner which uses only UNIX tools:

```
curl https://api.github.com/repos/dedis/cothority/releases/latest | grep 'browser_download_url' | awk -F\" '{ system("curl -LO " $4) }'
```

**Comment by Daeinar** [comment]
In the long run it would be probably good to have an alias which points to the latest archive. Then we can do

```
curl -LO <url>/conode-latest.tar.gz
```

**Comment by ineiti** [comment]
Le 22/12/2015 12:17, Philipp Jovanovic a écrit :
>
> In the long run it would be probably good to have an alias which 
> points to the latest archive. Then we can do
>
|Look at cothority/app/conode/update.sh for a way how to do this.

Linus
|

**Comment by Liamsi** [comment]
Thanks a lot @ineiti. I was searching for a way, that was short (fits on a slide for instance ;) and does not rely on greping for a href on an HTML page (which might change anytime) but using the github API (which shouldn't change, because a lot oft software relies on it). Unfortunately there is no, direct way (without retreiving JSON first). I think we go with @Daeinar's proposal (for the slides).
Ismail

**Comment by Liamsi** [comment]
`$ ./stamp sign file` now should be `$ ./stamp-PLATFORM sign file` (or revert the changes which made more than one `stamp`etc. executable in the release

**Comment by ineiti** [comment]
Le 22/12/2015 12:54, Ismail a écrit :
>
> |$ ./stamp sign file| now should be |$ ./stamp-PLATFORM sign file| (or 
> revert the changes which made more than one |stamp|etc. executable in 
> the release
>
>
I thought we made a symbolic link to the correct stamp-executable.

**Comment by Liamsi** [comment]
> I thought we made a symbolic link to the correct stamp-executable.

Exactly. But it seems to be gone. Try with the latest release:
```
curl https://api.github.com/repos/dedis/cothority/releases/latest | grep '"browser_download_url":' | awk -F\" '{ system("curl -L " $4) }' > conode-latest.tar.gz; tar -tvf conode-latest.tar.gz 
```

**Comment by ineiti** [comment]
Le 23/12/2015 09:43, Ismail a écrit :
>
>     I thought we made a symbolic link to the correct stamp-executable.
>
> Exactly. But it seems to be gone. Try with the latest release:
>
> |curl https://api.github.com/repos/dedis/cothority/releases/latest | 
> grep '"browser_download_url":' | awk -F\" '{ system("curl -L " $4) }' 
> > conode-latest.tar.gz; tar -tvf conode-latest.tar.gz |
>
https://github.com/dedis/cothority/blob/development/app/conode/start-conode.sh#L15

Linus

**Comment by Liamsi** [comment]
Thanks a for the hint! :-) I searched for some `ln -s` and couldn't find where the symbolic link is created. I think the documentation (and the slides) should be clear about when `stamp` exists (only when `start-conode.sh` was previously used)

**Comment by Liamsi** [comment]
Taken care of in #279 #256 #275
