### ISSUE TITLE
Errors to be fixed

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1473]
This is a collection of errors still happening in viewchange:

- `TestHeartbeat_Timeout` - @jeffallen says he fixed it in #1464 
- `TestService_DecryptKey`

**Comment by jeffallen** [comment]
I have a fix for that in branch block_size: https://github.com/dedis/cothority/pull/1464/commits/86331c00f0e4659306942b93c18e986dba150e31

**Comment by ineiti** [comment]
Done.
