### ISSUE TITLE
Java and JavaScript implementation of client-side GetProof checking

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1483]
We need to implement the client-side proof checking in Java. Verification has two steps:
1. from a block id that the client trusts as good (could be genesis block, or some other block farther along the chain, so that the GetProofResponse will be more compact) be able to follow the forward links provided by the GetProof server-side and end up at the same place that the server claims is the latest block.
2. given ONLY the client's copy of the key, and the data the server put into GetProofResponse.Proof.InclusionProof, it should be possible to calculate the collection root hash, and it should be the same as the one found in the Data field of the latest block.

To confirm: that there is enough (but not too much) data serialised into GetProofResponse.Proof.InclusionProof. In particular, it seems (to Jeff) like GetProofResponse.Proof.InclusionProof.Root (type collection.dump) has keys and values in it that should not be there, and that only one of GetProofResponse.Proof.InclusionProof.Root.Children.{Left,Right} is needed.

Also: Before sending back the latest block, the server can and should set the Payload to nil, so that the payload itself is not sent down in GetProof replies. It is not needed in order to verify proofs, only the byzcoin.DataHeader which is carried in the Data field of the skip blcok is needed. This job will require fixing the tests that use txrFromPayload to parse the payload; they will need to use skipchain.GetUpdateChain to fetch the actual skipblock, given the skipblock id calculated from the data received in GetProofResponse.Proof.Latest.SkipBlockFix.

For extra credit: *If it is possible in Java, then it should be possible in JS too!*

**Comment by ineiti** [comment]
Like #1440 we have to wait for @kc1212 to finish the new collection library.

**Comment by jeffallen** [comment]
This was completed for Java in 3af2fef52f1230e146cd9da1a0081ac442ea3a6c and is underway for JS in #1651.
