### ISSUE TITLE
Conodes should be available through wss

### ISSUE THREAD

**Issue by louismerlin** [dedis/cothority#1486]
I am building building a [simple cothority status frontend](https://github.com/blockchainstudentassociation/hello-cothority).

In development, everything works well, but [in production](https://blockchainstudentassociation.github.io/hello-cothority/), mixed content is forbidden in modern browser and my webapp is served through http**s**, so it will not allow an insecure websocket connections to the conodes.

Is a ws**s** connection to conodes a planned feature ?

**Comment by jeffallen** [comment]
This feature was added to in onet (which is the underlying library used by Cothority to serve the websockets) in dedis/onet#405.

Please give it a try, and if you have problems with it, report an issue on the onet repo, and we'll see if we can get it fixed.

**Comment by louismerlin** [comment]
I'll make a fork of the javascript npm module then, to try to force wss when initiating a connection to a conode. If the conode already accept wss, it should not be complicated :smile:

I will open a PR if it all works as expected.

**Comment by louismerlin** [comment]
I modified the package's code to upgrade all websocket connections to wss.

Now it seems the four running nodes do not actually accept a wss connection... Are they outdated ? Or mabye the certificates were not renewed ?

For example, run in a terminal :
```
openssl s_client -connect dedis.nella.org:6880
```

Or open the latest version of the demo [here](https://blockchainstudentassociation.github.io/hello-cothority/).

**Comment by louismerlin** [comment]
Too bad, but I completely understand. This means there can be no https:// frontend for the cothority network at the moment. I'll keep an eye out for changes.

Thank you for your time :smile:
