### ISSUE TITLE
Don't re-use C

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1489]
In `WriteRequest.java` the point `C` is re-used as a _mask_ to encrypt parts of the symmetric key. In order to not re-use `C`, we need to:

- throw an exception if we have a bigger symmetric key than 29 bytes (the maximum we can embed)
- limit the symmetric key material to 16 bytes by putting the IV in the extra data from the write request

**Comment by kc1212** [comment]
More information: the file name is change to `WriteData.java`, the function we're interested in is `encryptKey`, and the problem is that `C` is reused inside the for loop. This is a backward incompatible change but not an API change.
