### ISSUE TITLE
Unable to use cluster after restart

### ISSUE THREAD

**Issue by darekzbik** [dedis/cothority#1507]
test cluster was running and application was connected to it. At some point it stop receiving requests (new value transactions) from client. I tried to restart cluster with the latest database files (untouched).

Cluster seems to start but client is still not able to publish data (value contracts).
Server logs and DB files are attached.

[database.zip](https://github.com/dedis/cothority/files/2453037/database.zip)
[conodes_logs.txt](https://github.com/dedis/cothority/files/2453036/conodes_logs.txt)

Client configuration and user attempting to make write operation
```xml
      <env name="BLOCKCHAIN_GENESIS" value="659EA695FBF24FB5952B7F00DF23373C09C763A1B7D2AEFEB7377A2FFABF7BCF" />
      <env name="CONODES" value="tcp://localhost:7102,d829a0790ffa8799e4bbd1bee8da0507c9166b665660baba72dd8610fca27cc1;tcp://localhost:7104,d750a30daa44713d1a4b44ca4ef31142b3b53c0c36a558c0d610cc4108bb4ecb;tcp://localhost:7106,7f47f33084c3ecc233f8b05b8f408bbd1c2e4a129aae126f92becacc73576bc7;tcp://localhost:7108,8b25f8ac70b85b2e9aa7faf65507d4f7555af1c872240305117b7659b1e58a1e" />
      <env name="ADMIN_ID" value="D6771A25CFD8F90B5C524EE172474D261E191F2EE11A714B59BD2249049DC520" />
      <env name="ADMIN_PRIVATE_KEY" value="3041020100301306072A8648CE3D020106082A8648CE3D0301070427302502010104209CDE02FA348C0B742B82BF47EF79A4E9D9A01312CCA5A1479D09614A813ADBEA" />
      <env name="ADMIN_PUBLIC_KEY" value="3059301306072A8648CE3D020106082A8648CE3D03010703420004D154930F847FC3526A403C641CBC29114FA46D00E3178B412E96D15BCD3D3436CC097511802E2E689D3E13D1305914CADDF293D08BDC2BEFFFAC42E0F4231B8C" />

```

**Comment by jeffallen** [comment]
I suspect this is an old problem, and could not be reproduced now. Please re-open if you disagree and want us to dig deeper into it. (And for example have a newer instance of it to look at.)
