### ISSUE TITLE
Spawn a darc with version != 0

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1510]
It seems like the contract code for spawning a darc does not require that the proposed darc arriving in the argument has version 0.

This makes it possible to target (squat on?) any desired instance ID, because when it calls d.GetBaseID () to find out the correct instance ID for the darc to be stored under, when d.Version != 0, then base id is taken directly from d.BaseID, so that the caller gets to choose it.

I don't know if this is a problem, but it seems like it might be.

**Comment by ineiti** [comment]
So people might squat darc-id's like `0xdeadbeef00ded15`?

On the other hand, if we don't allow to spawn non-0-version darcs, we cannot store darcs that were 'born' in another place, which might be a problem later in a cross-sharding setting, if we want to 'migrate' instances from one shard to another.

But this could be taken care of in a different way later. So it's probably a good idea to have a test of `Version == 0` in the darc.spawn part of the darc contract.
