### ISSUE TITLE
Implement Java stream for streaming blocks

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1516]
Instead of registering a callback, use the API to return a java-stream.

Keep both interfaces, so that the user can chose.

**Comment by kc1212** [comment]
The entry point is here, this is the subscription based API - https://github.com/dedis/cothority/blob/master/external/java/src/main/java/ch/epfl/dedis/byzcoin/ByzCoinRPC.java#L321

where the caller provides an implementation of the `SkipBlockReceiver` interface, and some of its methods are called on every new block. Instead, it'll be nice if we can return a java stream object.

**Comment by Gilthoniel** [comment]
@kc1212 Please let me know if this was the expected change
https://github.com/dedis/cothority/tree/cothority-1516-java-stream

**Comment by kc1212** [comment]
It looks good. Feel free to create a PR.

One thing I tried to do for handling errors is to use an intermediate Result type, which may contain a valid block or an error. Then use `takeWhile` to end the stream early on the first error. But `takeWhile` is a jdk9 feature, its jdk8 workaround isn't pretty. As a first stab this is fine to me, we can add a way for the stream to finish early later.
