### ISSUE TITLE
Add 'Accepted' to ClientTransaction

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1519]
The java implementation of `ClientTransaction` does not have an `Accepted` flag.

**Comment by jeffallen** [comment]
But TxResult does. I don't know where you'd get a ClientTransaction that had an accepted flag associated with it other than from parsing a block, and when you parse a block with ch.epfl.dedis.byzcoin.Block, you end up with a list of TxResults.

**Comment by ineiti** [comment]
Thanks, effectively, ByzCoin `Block` has a list of `TxResult`s, which have `isAccepted` as a method to check if the `ClientTransaction` has been accepted or not.
