### ISSUE TITLE
network library rewrite

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#152]
* Change order of methods from higher priority to lower priority
  - init first, then test method..
  - interface first, then implementations..
* Move encoding part of the network in separate file

**Comment by ineiti** [comment]
* take `name` out of the constructor
* think of a way to have a per-connection suite

**Comment by ineiti** [comment]
`lib/network` - is it possible to have a standard `constructor` for `point` and `abstract`? Something like

```
NewTcpHost("name", network.NewCryptoConstructors(suite))
```
?

**Comment by ineiti** [comment]
Add a 'most simple' test/example.

**Comment by nikkolasg** [comment]
resolved in https://github.com/dedis/cothority/pull/145.
Close.
