### ISSUE TITLE
Instruction.deriveId throw NullPointerException when is taken from Skipblock

### ISSUE THREAD

**Issue by aboruch** [dedis/cothority#1527]
Scenario is as following:

1. we take Skipblock and take client transactions from it
2.  iterate over list of Instruction from ClientTransaction
3.  filter list of Instruction and take only Spawn instructions
4.  from each Spawn instruction we take instanceId as:
  ```
  omniBlock.getClientTransactions()
                    .forEach(clientTransaction -> clientTransaction.getInstructions().
                     forEach(instruction -> processInstruction(instruction)))

void processInstruction(instruction) {
 InstanceId instanceId = instruction.deriveId("");
....

```
  We want to use that id to fetch data using I.e ValueInstance later.
  The problem is that when we call  _instruction.deriveId("")_; **NullPointerException** is thrown:
```
java.lang.NullPointerException: null
	at ch.epfl.dedis.byzcoin.transaction.Instruction.deriveId(Instruction.java:240) ~[cothority-master-181012.jar:na]
```

Seems that during construction Instruction object from protobuf object list of signatures are not set

**Comment by kc1212** [comment]
Which contract are you using? It might be that the contract is accepting instructions that are not signed. Can you also check whether those transactions are accepted? You can use `getTxResults`, it should give you a list of client transactions but with a flag to say whether they're accepted. Maybe the ones that are not accepted will not have signatures.

**Comment by aboruch** [comment]
We're using value contract and we sign it before sent. We use ch.epfl.dedis.byzcoin.Block to take ClientTransaction but unfortunately from this level we haven't access to 'accepted' flag (this is a another issue).
I can try prepare separate to show our approach - and reproduce error.

**Comment by kc1212** [comment]
`ch.epfl.dedis.byzcoin.Block` has a `getTxResults` public method, you should be able to see the acceptance flag using the public function `isAccepted` in `TxResult`.

**Comment by aboruch** [comment]
Ok I've updated logic to take client transactions and add checking that all transactions are accepted.
```
           ch.epfl.dedis.byzcoin.Block omniBlock = new ch.epfl.dedis.byzcoin.Block(omlSkipBlock);
         omniBlock.getTxResults().stream().filter(TxResult::isAccepted).map(TxResult::getClientTransaction)
                    .forEach(clientTransaction ->
                            clientTransaction.getInstructions().
                                    forEach(instruction -> processInstruction(instruction)
```

but NPE exception is still thrown:
```
java.lang.NullPointerException: null
	at ch.epfl.dedis.byzcoin.transaction.Instruction.deriveId(Instruction.java:240) ~[cothority-master-181012.jar:na]
```

**Comment by kc1212** [comment]
Okay, thanks for trying. I managed to reproduced the failure at my side and I will do some investigation later this afternoon.

**Comment by aboruch** [comment]
I'm not sure but maybe when you creating Instruction object from protobuf signatures filed should be also set, I'm talking about following place in ch.epfl.dedis.byzcoin.transaction.Instruction#Instruction(ch.epfl.dedis.lib.proto.ByzCoinProto.Instruction):
```
    public Instruction(ByzCoinProto.Instruction inst) {
        this.instId = new InstanceId(inst.getInstanceid());
        this.nonce = inst.getNonce().toByteArray();
        this.index = inst.getIndex();
        this.length = inst.getLength();
        if (inst.hasSpawn()) {
            this.spawn = new Spawn(inst.getSpawn());
        }
        if (inst.hasInvoke()) {
            this.invoke = new Invoke(inst.getInvoke());
        }
        if (inst.hasDelete()) {
            this.delete = new Delete(inst.getDelete());
        }
    }

```

**Comment by kc1212** [comment]
Hi @aboruch hopefully #1528 fixes the issue. If you're still having problems please reopen it. We'll make a release next week.
