### ISSUE TITLE
SDA-related: protobuf should support maps

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#153]
As we switched to using [dedis/protobuf](https://github.com/dedis/protobuf) for the (cothority) network library, we also want to encode/decode maps (original  [goolang/protobuf](https://github.com/golang/protobuf/) already supports maps). I started working on that in https://github.com/dedis/protobuf/tree/map_support)

**Comment by Liamsi** [comment]
Can be closed, when https://github.com/dedis/protobuf/pull/12 is closed.

**Comment by ineiti** [comment]
dedis/protobuf#12 is merged.
