### ISSUE TITLE
Add `InstanceID` to `Instruction`

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1539]
Add an `InstanceID` argument to `Instruction`s, so that the user can chose his own instanceID as a basis for `GetDeriveID`.

**Comment by ineiti** [comment]
Either have it per default, or have it as an option in some contracts.

**Comment by kc1212** [comment]
I'm a bit confused by this, isn't `InstanceID` already a field in `Instruction`?

**Comment by jeffallen** [comment]
My recollection is that we have discussed this and decided that Byzcoin chooses it's instance IDs, not the user. Closing.
