### ISSUE TITLE
Master branch : nil pointer exception

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#154]
Tried to run a cothority from freshly install Debian + go, ran into a nil pointer exception when I ran the test in lib/conode. (Debian 8 + go1.5.2).

**Comment by Liamsi** [comment]
Can you post tje output (as an attachment)? I'll try to debug this in my Linux machine soon.

**Comment by nikkolasg** [comment]
[dedis_master_nil.txt](https://files.zenhub.io/5694bc8d868eed7b6cccbd51)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by Liamsi** [comment]
We figured out the problem: a quickfix is to comment out some legacy code for voting (which uses [atomic](https://golang.org/pkg/sync/atomic/)). @nikkolasg  will comment out few lines.

**Comment by Liamsi** [comment]
See: https://github.com/golang/go/issues/9959

**Comment by nikkolasg** [comment]
See https://github.com/dedis/cothority/pull/156

**Comment by Liamsi** [comment]
solved in #156
