### ISSUE TITLE
output of proto.awk is not compatible with the dedis/protobuf for repeated fields 

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1569]
The dedis/protobuf package will encode repeated sint/uint/bool etc. with [packed=true]. but proto.awk does not generate [packed=true].

As a result, messages sent back from cothority cannot be decoded by the java client.

**Comment by jeffallen** [comment]
Fixed in ea89938c443d3c5275597bf6ed9b134f9a942e4d.
