### ISSUE TITLE
Monitor proxy_test.go

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#157]
In proxy_test.go, there are two tests: TestProxy and TestReadyProxy. 
ReadyProxy only tests for the Ready functionality, but this is already tested in TestProxy. The issue in Travis VM is that running both tests sequentially fails, but running one after the other does not. It may be a closing connection - related issue, not sure. It works fine on my Mac anyway so that's strange.
For the moment, I just commented out TestReadyProxy.

**Comment by Liamsi** [comment]
related to the test which was commented here: https://github.com/dedis/cothority/commit/d4e86831f8fbd4478d8d030d4b1f8f55819536a0

**Comment by Liamsi** [comment]
You have to install docker and to pull the travis-go docker image ...

**Comment by Liamsi** [comment]
After pulling the docker image, do:
```
docker run -it quay.io/travisci/travis-go /bin/bash
```

**Comment by Liamsi** [comment]
In there install go (setup GOPATH etc) and uncomment the test mentioned in: https://github.com/dedis/cothority/issues/157#issuecomment-171589344

**Comment by Liamsi** [comment]
The relevant part of the failure output is:
[proxy_test.go-error.txt](https://github.com/dedis/cothority/files/90395/proxy_test.go-error.txt)

**Comment by Liamsi** [comment]
The reason for test failing is that the 2nd test is run and tries to open a connection, before the connection of the test is really closed. This would have been clear if we would do proper error handling (might be related: https://github.com/dedis/cothority/issues/160)
