### ISSUE TITLE
Insufficient error handling

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#160]
In some src files in the deploy package there is very limited error handling: 
Function which return `error`s are often called without handling the potentially occurring error. This lead for instance to #17.

**Comment by ineiti** [comment]
Could be a quickfix

**Comment by Liamsi** [comment]
> Could be a quickfix 
Only if we care about the file deploy.go. There seem to be a lot of places with no, or not sufficient error handling. It might be more reasonable to wait for the sda to be finished and than project-wide search for all function calls which might return errors but where the error handling is ignored.

**Comment by Liamsi** [comment]
Still way to many errors ignored. It's OK to ignore errors in test code but not in production cod, as it makes it obviously very hard to find the error (and we already spent hours searching for bugs, which would have been obvious, if the error was at least logged). 
You can hunt for missing error handling using: https://github.com/kisielk/errcheck 
(run `errcheck ./... | grep -v "_test.go"` to exclude test files; currently yields 125 lines)

**Comment by Liamsi** [comment]
I will take care of this.

**Comment by Liamsi** [comment]
Will work on this tomorrow. Or does it make sense to wait for the services-sda-rewrite?

**Comment by nikkolasg** [comment]
closed with #347
