### ISSUE TITLE
For COSI, can I sign a message with N participants, and verify with only 1 participant?

### ISSUE THREAD

**Issue by xy008areshsu** [dedis/cothority#1606]
See the title, is it possible to do this using somethine like the ThresholdPolicy(1)? 
Such as: https://github.com/dedis/cothority/blob/6e9c11bb6202ec6b9fceba7f71902e4613426327/cosi/crypto/cosi_test.go#L143

**Comment by xy008areshsu** [comment]
So what i would like is to, for example, sign with 2 nodes, and to verify with only 1 node (just an example, in production we will redefine the threshold N)
See here: https://pastebin.com/5TfarJ3U, I signed the message with 2 nodes
at line 28 and 29, I first verified the signature with both nodes' public keys, and it certainly can be verified.
And then at line 31, I just use the first node's public key, and at line 32 the for loop, I tried different threshold N, but they all failed verification, even with N of 0 and 1. 

Any idea where I did it wrong? Or did I miss something here?

**Comment by Gilthoniel** [comment]
Ok I see. The threshold is only used to define how many refusals you accept but you cannot decide to "remove" a signature from the aggregated one. As far as a message is signed with given key pairs, you will need to provide the same public keys every time.

The threshold parameter gives you only the right to decide if a signature is accepted with N refusals but the list of public keys must remain the same.

**Comment by xy008areshsu** [comment]
But then what is the point of N here, if we provide all the public keys all the time? If I sign with M nodes' private keys, I always have to provide all M nodes' public keys for verification, then how does this N come into the picture? 
Can you maybe give me an example?

**Comment by Gilthoniel** [comment]
Most of the time you will the same threshold but take the example where you accept to sign with a very low threshold like 1 which is totally insecure. Then the verification is done by someone that requires a better security and then ask for the maximum threshold (# of nodes). In that case the signature would be refused if at least one node refused to sign.

But if you try to verify with a threshold of 1, it would pass.

**Comment by xy008areshsu** [comment]
in other words, does it mean the threshold N_s when signing is always less than or equal to the threshold N_v when verifying?

**Comment by Gilthoniel** [comment]
N_v < N_s you need less security when verifying
N_v == N_s you need the same level of security
N_v > N_s you need more security when verifying

But this makes sense only if different parties use the signature.

**Comment by Gilthoniel** [comment]
No because the threshold is only used to check _how many_ public keys have been used. But you need the aggregated public key to verify the signature.

**Comment by xy008areshsu** [comment]
ok, thanks for the explanation :)
