### ISSUE TITLE
Too much freedom in darcs

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1625]
At the moment, anybody with the spawn permission can spawn a darc with arbitrary rules. Similarly, anybody that's allowed to evolve the darc can evolve it without restrictions.

For example, in a hierarchical scenario, where we have admins, managers and users. We need a way to restrict the managers such that they cannot spawn other managers (this right is reserved for admins). Similarly, users should be allowed to evolve some of its rules but they should not have the possibility of adding a rule that lets them spawn manager darcs.

A high level idea to implement this feature is to create attach a white list (or black list) that specified what kind of evolution and spawn every instance is allowed to do. Since darcs are not useful when they're not attached to instances. We still allow anybody to spawn darcs, but when they try to spawn an instance, the contract will check that the darc rules satisfy the white/black list. Putting restrictions in evolution is trickier, ByzCoin must have a way to find which instance/contract that the darc is attached to, and then make sure the new rules satisfy the restrictions. When restrictions are used, it may be trick to attached multiple instances (from different contracts) to the same darc, but this is a inconvenience that we have to live with.

**Comment by ineiti** [comment]
Here some more ideas how to solve this problem:
1. don't allow adding any new rule once the darc is created - very easy to implement, but very restrictive
2. only allow adding the rules of the parent's darc - needs an `intermediary` darc that defines the maximum ruleset and can only be evolved by the admin
3. create a contract that defines how the darc can be evolved in a special, read-only, field

1. is really simple to implement and might in fact be enough. But 2. keeps more possibilities open, even though it is more complex.

**Comment by kc1212** [comment]
I quite like the idea of intermediaries (2) for its flexibility. It might look something like this:

```
boss Darc: has no restrictions
manager-spawner Darc: spawn:manager, all manager rules (owned by boss Darc)
manager Darc: spawn:user, all user rules, other manager rules (owned by managers)
user-spawner Darc: spawn:user, all user rules (owned by managers)
user Darc: user rules (owned by users)
```

It might be tricky to add additional rules to the user (or whatever Darc is at the leaf), but it should be possible. One must add it to the manager-spawner using evolution. Then the manager makes the evolution, it is allowed because the latest version of its parent has the new rule. So we propagate the rule down the chain. Note that for this idea to work every Darc needs to have a "spawner" field.

**Comment by kc1212** [comment]
Using contracts for this purpose is also possible. Suppose you're spawning an, the contract of the instance will check whether the Darc used to spawn it has the correct set of rules. Similar for evolution, when the Darc is evolved the Darc contract must find the instance/contract for which the Darc is attached and check that the evolved rules satisfies the requirements (blacklist/whitelist) specified in the contract. However, it'll be difficult to change the rules later on because that'll lead to a change in the contract which cannot be done easily.
