### ISSUE TITLE
bn256 for Java

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#1626]
Since we're switching to bn256 for skipblock signatures, we need the same on java (and later js) in order to verify the blocks.

I'm making this issue to note down my investigation on the possible bn256 implementations that we could use on the java side.

The first I tested is https://github.com/herumi/mcl it's mostly written in assembly but there's a Java FFI. I cloned the repo and tried the tests. Other than changing some gcc include paths the tests seem to work. The license is BSD so that's fine too. The biggest downside is that java is only a wrapper, so the building and packaging process is more going to become cumbersome. At the moment the developer do not provide a package release.

**Comment by kc1212** [comment]
The only pure java implementation that I found that has some potential is - http://gas.dia.unisa.it/projects/jpbc/index.html

However, from my understanding, it doesn't have an implementation of the same type of pairing as what is used in https://godoc.org/golang.org/x/crypto/bn256 (i.e., Optimal ATE pairing). But it does have a BN curve implementation (Type F).

OTOH, mcl does support Optimal ATE pairing.

**Comment by jeffallen** [comment]
I'd be happy to trade the easier building/portability of the native Java version for the performance of the FFI one, I had nothing but grief from Java native code on a former project. But keep exploring and tell us what you find, and we'll choose the best way forward.

**Comment by kc1212** [comment]
I was looking at the golang bn256 implementation. It's a standalone implementation (8 files with about 200-300 lines each) and it doesn't use anything other than `crypto/rand` and `math/big`. In fact, most of the operations are just combinations of bignum operations (which makes it non-constant time). So it wouldn't be impossible to port it to java with a few days of concentrated work even without knowing the theory behind it.

The only downside is that the landscape of pairing-based crypto library isn't very standardised and we may very well switch to another one in the future. So it'll be a couple of weeks of wasted work.
