### ISSUE TITLE
BLS signature support in JS/TS

### ISSUE THREAD

**Issue by Gilthoniel** [dedis/cothority#1651]
This issue reports the different solutions that could bring the support of BLS to the javascript library.

1. Using [elliptic](https://www.npmjs.com/package/elliptic) cannot work because the fp256bn curve is not defined and pairing is not supported
2. [WebAssembly](https://github.com/golang/go/wiki/WebAssembly) of Kyber is complex for browser support and a quick test makes me thing the feature is not stable enough for the moment
3. milagro-crypto-js: not producing the same results, and the author seems to have given up the repo

The remaining solution is to port go code into javascript

**Comment by kc1212** [comment]
I did a webassembly test by following https://github.com/golang/go/wiki/WebAssembly

I compiled an example program that uses bn256
```
package main

import (
	"crypto/rand"
	"fmt"

	"golang.org/x/crypto/bn256"
)

func main() {
	// This implements the tripartite Diffie-Hellman algorithm from "A One
	// Round Protocol for Tripartite Diffie-Hellman", A. Joux.
	// http://www.springerlink.com/content/cddc57yyva0hburb/fulltext.pdf

	// Each of three parties, a, b and c, generate a private value.
	a, _ := rand.Int(rand.Reader, bn256.Order)
	b, _ := rand.Int(rand.Reader, bn256.Order)
	c, _ := rand.Int(rand.Reader, bn256.Order)

	// Then each party calculates g‚ÇÅ and g‚ÇÇ times their private value.
	pa := new(bn256.G1).ScalarBaseMult(a)
	qa := new(bn256.G2).ScalarBaseMult(a)

	pb := new(bn256.G1).ScalarBaseMult(b)
	qb := new(bn256.G2).ScalarBaseMult(b)

	pc := new(bn256.G1).ScalarBaseMult(c)
	qc := new(bn256.G2).ScalarBaseMult(c)

	// Now each party exchanges its public values with the other two and
	// all parties can calculate the shared key.
	k1 := bn256.Pair(pb, qc)
	k1.ScalarMult(k1, a)

	k2 := bn256.Pair(pc, qa)
	k2.ScalarMult(k2, b)

	k3 := bn256.Pair(pa, qb)
	k3.ScalarMult(k3, c)

	// k1, k2 and k3 will all be equal.
	fmt.Printf("%v, %v, %v\n", k1, k2, k3)
}
```

compiled it to wasm and then ran it in the browser. The output looked fine to me and I didn't run into any problems during the process.

I don't know what the status of this issue is now, but maybe we should give wasm another look? For example, I don't know how to treat this wasm binary as an "object file" instead of an executable. If that's possible then we can just write a TS wrapper for it.

**Comment by kc1212** [comment]
Did some more reading, as far as I can see you can't just compile an unmodified package to wasm. You have to use https://golang.org/pkg/syscall/js/#NewCallback to say which functions you want to export

**Comment by kc1212** [comment]
Actually, the compiled wasm binary is 2.9 MB for that piece of code. Maybe it's not such a good idea if it needs to be distributed to a lot of clients...

**Comment by Gilthoniel** [comment]
I did compile Kyber, that's when the trouble occurred. But yeah as you said it's not ideal at all knowing it's only the bn256 code.

I'm currently writing the porting from go/java to typescript and it's mostly done.
