### ISSUE TITLE
Suboptimal hashing of ClientTransaction

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1657]
The current hashing method of `ClientTransaction` doesn't include the identities of the signers in the hash. This is a problem, because:

When two blocks containing two same ClientTransactions with only the difference in the identity, the nodes think that it's the same ClientTransaction, and it will not be correctly applied anymore.

Simple fix:
```
delete(s.stateChangeCache.cache, string(sb.SkipChainID()))
```
in `updateTrieCallback`. More complex fix: change `Hash` in ClientTransaction to include the identity, too. But this most probable will break a lot of pieces that do `SignBy` on their own.

**Comment by kc1212** [comment]
Working on this issue now. This is a breaking change because we'll be changing how transactions are hashed, so needs to be done before v3.
