### ISSUE TITLE
Use mocking for network connections

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#170]
Currently, every unit test, that uses network communication also tests the whole network stack.  
We already spent a lot of time in trying to figure out, why tests run locally but fail on travis (see #162, #163, #157, etc). One simple solution to that would be to mock the network connection. We should just test if `Open()`, `Close()`, `Listen()`, etc. are called in an appropriate order.
Tasks:

1) Either use an simple mocking framework (could be golangs [default mocking framework](https://github.com/golang/mock/tree/master/sample) ?) or write a Mock just for the networking layer
2) Make some tests use the mocked network library (instead opening and closing ports on localhost), especially tests which open, close and re-open the same ports are good candidates (see: https://github.com/golang/go/issues/11872#issuecomment-126183460)

**Comment by ineiti** [comment]
We still get occasional improvement of the code by watching what works and what not. So I'll still let it be in there.

**Comment by ineiti** [comment]
Closing, as network is well debugged now and doesn't need to be mocked anymore.

**Comment by ineiti** [comment]
I still think we're merely hiding problems of the network-stack by using mocking here. Our network-stack is broken, so if we put another layer on top of it, it is still broken.

**Comment by ineiti** [comment]
This will be done in #522
