### ISSUE TITLE
SkipBlock hash wrongly calculated

### ISSUE THREAD

**Issue by Gilthoniel** [dedis/cothority#1701]
https://github.com/dedis/cothority/blob/532f4439c37422a1de975cec7bf7e7182b0b5b46/skipchain/struct.go#L320

The error is ignored but the problem is that we try to write a _int_ which is not a fixed length type and then there is actually an error. That means all hash so far ignore the four parameters because the write fails. Also we need to decide on a byte-length because with Go it could be either 32 or 64 so depending on the architecture, the resulting hash will be different.

**Comment by kc1212** [comment]
it seems we use:
```
message SkipBlock {
    required sint32 index = 1;
    required sint32 height = 2;
    required sint32 max_height = 3;
    required sint32 base_height = 4;
}
```
in protobuf.

will it be enough to cast the `i` to int32 before hashing?

we can also change the int to int32 in golang, probably it's a better fix but it might be a big change (adding type casts everywhere)

**Comment by Gilthoniel** [comment]
Hm I think the hash is the only place where the size actually matters. As you said that will need a lot of changes to change it to int32 so for me it would be enough to cast in the hash function.

@jeffallen what do you think ?

**Comment by jeffallen** [comment]
I'm working on a change to SkipBlock in #1699 , so let me see if I can reasonably fix this at the same time.
