### ISSUE TITLE
JS libraries: prepare scripts to publish in a nice way

### ISSUE THREAD

**Issue by Gilthoniel** [dedis/cothority#1712]
With the current situation, we need to import using this kind of paths: "@dedis/cothority/dist/..." but we should be able to import like "@dedis/cothority/...".

In order to achieve that, the package.json should be copied in the dist folder along with the documentation so that the _dist_ folder is considered as the package.

This should be done for both cothority and kyber.

**Comment by jeffallen** [comment]
Other todos in the same PR: make NPM use a travis cache, so that "npm i" goes faster.
