### ISSUE TITLE
go.dedis.ch should be hosted more reliably

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1718]
I put go.dedis.ch on a different DNS name from dedis.ch because I suspected that the web hosting at EPFL would not be reliable enough to make our imports rely on them. On Friday I was proved right, alas.

We need to:
- [ ] choose a cloud hosting provider - investigate https://www.switch.ch/engines/enterprise (Switch says our job is not a good fit for their pricing. Google App Engines is not usable from an epfl.ch account, ugh.)
- [ ] pay them to get started
- [ ] deploy an app that serves the correct meta file for go.dedis.ch/$pkg. See https://github.com/golang/website/blob/master/cmd/golangorg/x.go for an idea how golang.org/x works.
- [ ] using first 3 months of billing as a guide, arrange to pay them for a few more years of service

**Comment by jeffallen** [comment]
go.dedis.ch went down again today due to ISP issues, so it's time to take care of this.

**Comment by jeffallen** [comment]
For testing, I can make go-test.dedis.ch point at whatever IP addresses you need. (Or rather, I can teach you how to update DNS yourself.)

**Comment by Gilthoniel** [comment]
Yes if I can have access to the DNS settings, that would be helpful to configure AWS. For instance you need a CNAME for the certificate request.

**Comment by Gilthoniel** [comment]
For reference: https://github.com/golang/go/issues/26827

Godoc doesn't handle the modules yet so the redirection will show the document on master.

**Comment by Gilthoniel** [comment]
@jeffallen 
- I made a repository that contains the lambda code: https://github.com/dedis/go-imports
- You should have gotten an invitation for the AWS account
- Basically an API gateway is rerouting all the requests to the lambda, the lambda analyzes the request to make the correct redirection
- You can test with the package https://go2.dedis.ch/go-imports-test or https://go2.dedis.ch/go-imports-test

The next step is to improve the readme and then to get the code reviewed. Finally we can switch the domain from `go2.dedis.ch` to `go.dedis.ch` and propagate the DNS.

**Comment by jeffallen** [comment]
As a training exercise, I deployed the cutover from go2.dedis.ch to go.dedis.ch with @Gilthoniel watching/helping me. It is now in service.

The last step is to take a quick look at this next week and if there have been no problems, raise the TTL on the go.dedis.ch DNS name back up, and clean up the stuff in /var/www/go.dedis.ch and /etc/apache2/sites-enabled.

**Comment by Gilthoniel** [comment]
```bash
gaylor@gaylor-l460:~$ nslookup go.dedis.ch
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
go.dedis.ch	canonical name = d-8jq79za180.execute-api.eu-central-1.amazonaws.com.dedis.ch.
d-8jq79za180.execute-api.eu-central-1.amazonaws.com.dedis.ch	canonical name = dedis.ch.
Name:	dedis.ch
Address: 128.179.33.44

```

**Comment by jeffallen** [comment]
It seems we'll be on the free tier this year, and later AWS will bill us monthly via credit card, while sending the PDF in e-mail. (To whose e-mail? That's a bit of a mystery.)

Cleanups are done, so closing this.
