### ISSUE TITLE
SignerCounter creation

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1743]
Mostly cosmetic, but

https://github.com/dedis/cothority/blob/master/byzcoin/replayguard.go#L42

should in fact be `Create` for the first storage of the `SignerCounter` (==0 - is that always the case?) and then `Update` for `>0`. Currently this is ignored once it is stored in the trie (as `Update` and `Create` are treated as writes), but this might later change, no?

**Comment by kc1212** [comment]
version always start at 0, you can see it from `getSignerCounter` where if the version doesn't exist then it'll return 0. it's true that it's better to use `Create` when we're at version 0, i'll fix it.
