### ISSUE TITLE
ContractID for SignerCounter

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1744]
https://github.com/dedis/cothority/blob/master/byzcoin/replayguard.go#L44

uses `byte[]` as `contractID` for `SignerCounter`, but I think this really should be an actual string, like `signerCounter`. Or is there a specific reason to use only an empty slice of bytes?

**Comment by kc1212** [comment]
I spent some time trying to see if there's a good reason why contract ID is `byte[]` while it is `string` in Instruction. I couldn't fine one. So I went ahead and changed `StateChange` and `StateChangeBody` to use `string` as the contract ID in Java and Go and it didn't seem too difficult. @Gilthoniel do you know if it's easy to change it on the TS side? I found `class StateChangeBody extends Message<StateChangeBody>`, I suppose we need to change `Buffer` to `string`, but I'm not sure if we need to change anything else.

**Comment by Gilthoniel** [comment]
No it's not a big deal. The usages of the getter need to be fixed but that's all.

**Comment by ineiti** [comment]
Yes, that was not clear enough, sorry. I wanted to write: `This should be "signerCounter" instead of an empty byte slice []byte{}`

**Comment by kc1212** [comment]
Hmm.. but this is a special case because it's not attached to any contract, that's why the contract ID field is left empty.

**Comment by ineiti** [comment]
True - it's not a contract that can be looked up. 

But what if there is another `special case` later on? How will you distinguish the two?

**Comment by kc1212** [comment]
The instance ID is unique - see `replayguard.go:publicVersionKey`. So there won't be a conflict in the database as long as the other special case has something other than `"signercounter_" + public_key` in the hash.

Having an empty `CountractID` will prevent us from easily iterating over all the state changes and figuring out which ones are the result of a signer version change, but we haven't needed this feature. If we really need to do that, we can look up all the identities in all the darcs and then run `publicVersionKey` on these identities to check if they exist.

**Comment by Gilthoniel** [comment]
Closed by #1746 even if the contract ID remains empty. If this becomes necessary in the future, that could be an easy and backwards compatible change (even if previous state changes would keep an empty string).
