### ISSUE TITLE
js publish.sh improvements

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1767]
The publish.sh script should:
- [ ] find out if it's possible to auto-generate the version in the package.json, so that it comes from the git tag on HEAD like "make bindist" does.
- [x] add a `npm ci && npm test` to make certain that dependencies are right and the thing passes tests before publishing

(Careful: `npm test` for cothority requires that `make docker` is up to date.)

**Comment by tharvik** [comment]
> find out if it's possible to auto-generate the version in the package.json, so that it comes from the git tag on HEAD like "make bindist" does.

It doesn't look possible. One could use [prerelease tags](https://docs.npmjs.com/misc/semver#prerelease-tags) to embed arbitrary data in the version, but then, it won't be updatable automatically.

> add a npm ci && npm test to make certain that dependencies are right and the thing passes tests before publishing

PR at https://github.com/dedis/cothority/pull/2226
