### ISSUE TITLE
SDA Channels Pointer to TreeNode

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#178]
Discussed with Linus and it makes more sense to register something like:
```
type myChan struct {
    *TreeNode
    MyPacket
}
```

instead of
```
type myChan struct {
    TreeNode
    MyPacket
}
```
Since we use *TreeNode everywhere... we don't have time to do it right now but it should be quite easy to do so.

EDIT: We should also do that for the packet them self, to stay consistent (using pointers most of the time).

**Comment by ineiti** [comment]
Done
