### ISSUE TITLE
BLSCoSi warning and fix

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1785]
As @Gilthoniel wrote in #1780, the BLSCoSi service can be used by a malicious user to lead an attack by getting the service to sign a malicious block, for example.

Currently it has been disabled, but there should be a message in the README.md showing that it's a problem.

To solve it, the BLSCoSi service should only sign the `sha256("bls" | message)`, then nobody can use it as an oracle, as an attacker cannot know the pre-image of the hash...

**Comment by ineiti** [comment]
In fact it seems that there is no need to use a specific signature, as the new version of the cothority has one separate keypair per service. So the `BLSCoSi` service cannot sign a message that will be accepted by the `ByzCoin` service.

Problem solved.

If somebody from DEDIS thinks this is correct, please close this issue.

**Comment by nkcr** [comment]
I let @jeffallen close this issue and PR #1790 if he agrees.

**Comment by jeffallen** [comment]
I agree.
