### ISSUE TITLE
Use URL from ServerIdentity struct (JS only)

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1791]
The task is to use the URL field in the ServerIdentity struct so that a roster can indicate how to contact the server from the client side.

Ideally, we'd do this work on all three client libraries (Go, Java, JavaScript). But to keep this task from being too big, let's deliver this feature on JS first, and then move on to other client libraries.

Tasks:
- [x] get dedis/student_18_explorer app working for dev mode, use the yarn version of `npm link` to work on a development version of cothority TS client.
- [x] fix cothority TS client to respect the URL field (see getWebSocketAddress). Hopefully callers will not notice the change at all (i.e. no corresponding change in the skipchain explorer?)
- [x] figure out how this can be tested in the context of the TypeScript tests -- perhaps it is enough to include one URL in the external/js/cothority/spec/support/public.toml file?
- [x] deploy it, and see it working for real
- [x] evolve one production conode to have URL in the ServerIdentity in it's roster (get help from @jeffallen )

**Comment by nkcr** [comment]
#1800

**Comment by nkcr** [comment]
#1804
