### ISSUE TITLE
missing forward links when roster changes

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1793]
Seen on the production cothority, where the 3 original nodes have a forward link for 0->16, but nodes added into the roster after block 16 are missing the 0->16 link. Thus from the point of view of accordion.employees.org:7770, the shortest path from 0->21 is 4 blocks long. But form the point of view of fairywren.ch:7770, the path is 7 nodes:

In the following, `scmgr s u` is a new feature to call GetUpdateChainLevel on targeted nodes. 3.toml is accordion.employees.org:7770, 4.toml is fairywren.ch:7770.

```bash
$ scmgr s u 3.toml -from 9cc36071ccb902a1de7e0d21a2c176d73894b1cf88ae4cc2ba4c95cd76f474f3
index 0, hash 9cc36071ccb902a1de7e0d21a2c176d73894b1cf88ae4cc2ba4c95cd76f474f3
index 16, hash c287771fd714b79a1b4ad60ef5c2779f580215d0ea9dd14e37eaf23e5f6e93ad
index 20, hash 1065f9544f65750719ba6a8c81a85d8012e8e9371478607110564d2171da55d9
index 21, hash fbf0896b9dda00b378fe710f77457ad1432af218dec3ac1433ca05daa84996ff
$ scmgr s u 4.toml -from 9cc36071ccb902a1de7e0d21a2c176d73894b1cf88ae4cc2ba4c95cd76f474f3
index 0, hash 9cc36071ccb902a1de7e0d21a2c176d73894b1cf88ae4cc2ba4c95cd76f474f3
index 4, hash 418c1c9748752db450fdf851ae93ae71e0ba23d35f61f1d9eb350e48a7cc8b25
index 8, hash 50644255b43a4e425b5534bf60197cdbc31f7e1501be77e913893820fb667796
index 12, hash 291d7445836a09844594bd663558539e6f1636be2bac0ab5c80f52dda8f4ab0c
index 16, hash c287771fd714b79a1b4ad60ef5c2779f580215d0ea9dd14e37eaf23e5f6e93ad
index 20, hash 1065f9544f65750719ba6a8c81a85d8012e8e9371478607110564d2171da55d9
index 21, hash fbf0896b9dda00b378fe710f77457ad1432af218dec3ac1433ca05daa84996ff
```

Todo:
- [ ] write a unit test to trigger this situation
- [ ] with the unit test, investigate how the chain behaves after it, i.e. will higher level forward links be correctly added?
- [ ] probably fix the call to `s.startPropagation(s.propagateForwardLink, from.Roster, &PropagateForwardLink{fl, fs.TargetHeight})` to use the new Roster instead of from.Roster
- [ ] decide if/when/how to catch up missed forward links

**Comment by Gilthoniel** [comment]
One benefit of the forward links is that they can be shared alone as you have everything to assert the integrity. So for the *if* I would be positive. Now for the *when*, if we fix the propagation, I guess it can be done during a catch up as you can search for missing ones (based on the backwards links/height) or in the background task after the catch up as they are not mandatory. That means that a restart of the conode would catch up missing forward links.

**Comment by jeffallen** [comment]
While investigating what would happen if we tried to fill in forward links later on conodes that are behind, I noticed this:

```go
// AddForwardLink stores the forward-link at the indicated position. If the
// forwardlink at pos already exists, it returns an error.
func (sb *SkipBlock) AddForwardLink(fw *ForwardLink, pos int) error {
	if len(sb.ForwardLink) > pos || pos < 0 {
		return errors.New("this forward-link already exists or invalid position")
	}
	for len(sb.ForwardLink) <= pos {
		sb.ForwardLink = append(sb.ForwardLink, &ForwardLink{})
	}
	sb.ForwardLink[pos] = fw
	return nil
}
```

That code makes the forward link list monotonically increase, filling holes with empty links, which is also not robust against a rogue leader who manages to deliver valid forward links to followers, but give them out of order.
