### ISSUE TITLE
darc.GetIdentityString

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1796]
Currently the `darc.GetIdentityString` is defined like this:

```
// GetIdentityString returns the string representation of the ID.
func (d Darc) GetIdentityString() string {
	return NewIdentityDarc(d.GetID()).String()
}
```

To me this seems counter-intuitive, as we're rarely interested in the darc-ID, and mostly only in the darc-base-ID. So would it make sense to change the above to

```
	return NewIdentityDarc(d.GetBaseID()).String()
```

??

**Comment by jeffallen** [comment]
I agree, and I'll take care of this, because I've got a bunch of little changes to check in pending right now.
