### ISSUE TITLE
Adding Proof of Knowledge to ServiceIdentity

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1797]
Continuing the discussion from #1675 and proposing an alternative to #1794:

I propose to change the `ServiceIdentity` to have a new field called `Proof` that is a signature on the marshalled public key. The field is optional, so that the `ServiceIdentity` from older nodes is still valid:

```
        Proof []byte `protobuf:"opt"`
```

Additionally a new method on the `Roster` needs to be defined (and also on the `TreeNodeInstance`):
`ServiceAggregateVerified(name string)(kyber.Point, error)`
This method will verify that all keys used to create the aggregate public key have a `Proof` in them and that the proof is correct.

Changes to the `PKI` service in #1794:
- no need for inter-node communication when verifying the onboarding of a new node
- change in `ServiceIdentity` which is part of every `Roster` and thus available to all services, whereas the change in #1794 only changes the `ForwardLink`, so only the byzcoin-service has the proofs in an offline setting
- using the new `ServiceIdentity`, both onboarding of new nodes as well as verification in an offline setting for all services is supported

**Comment by Gilthoniel** [comment]
Downgrade attack if the field is optional ?

**Comment by ineiti** [comment]
No downgrade attack, because the service decides whether he wants to have proofs for all the entries or not.

To migrate the byzcoin-service, you could either use what you did with the environment variable, or make it automatic:
- the `contractConfig.update_config` only allows new nodes with a proof
- the `contractConfig.spawn` only allows new byzcoins with all proofs
- in the verification methods, use a non-strict `ServiceAggregateVerified` method

Both the environment variable method and the automatic method suppose that the initial roster is not corrupt. So for best proofs, the keypairs should not be changed, and all nodes should get a proof in a block to show that they were legit in the past. If this doesn't happen, then we lose the trust in the byzcoin instance `9cc3...` and need to start from scratch.

To migrate automatically, you can have every node create its proofs (perhaps in `onet/app/config.parseServiceIdentity`), then the admin of `9cc3...` (Jeff) collects the new roster with the proofs, and updates the byzcoin-config with this new roster. If a node stays behind for some time, that's not a problem. If a node disappears, all blocks where he was part are tainted and should not be used for forward-links.

**Comment by jeffallen** [comment]
We will not add to ServerIdentity because the better solution is to accelerate exclusion of public keys correctly, as will be discussed in #1675.
