### ISSUE TITLE
Bad certificate due to a missing ca-certificates in docker

### ISSUE THREAD

**Issue by Gilthoniel** [dedis/cothority#1836]
https://github.com/golang/go/issues/24652#issuecomment-464613737

Conode binary compiled with version `< 1.11.6` might see this error when trying to reach other conodes: `x509: certificate signed by unknown authority`. I open this issue as a reference and also to update current Travis jobs to 1.12.

**Comment by Gilthoniel** [comment]
From @ineiti :
```
with regard to ssl - I was obviously the only one using docker-images, so I was the only one who had problems due to a missing `ca-certificates` in the very trimmed-down `debian:stretch-slim`…
```

**Comment by ineiti** [comment]
Renamed issue so we don't have a misleading `go compiler error` where there is none...
