### ISSUE TITLE
Add version information to blocks

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1854]
As we are using pre-compiled contracts, one of the problems we'll be facing a lot is the change of functionality in a contract. This is important to handle correctly, specifically if we want to keep the possibility of recreating the global state of the blockchain starting from the genesis-block.

I propose we add a field to the `byzcoin.DataHeader`, `Version *int`, that is also available in the `ReadOnlyStateTrie`. So a contract that wants to change its behaviour can check the version it should apply, and so behave correctly for different blocks.

Some details:
- `byzcoin.verifySkipBlock` has to check that the version of the proposed new block is `>=` the version of the previous block
- the `Version` needs to be a pointer to int - a `protobuf:"opt"` will still create the field when using `protobuf.Encode`, and thus create incompatible blocks
- to allow correct updating of the byzcoin instance: all the nodes return their version in `getTx`, and the leader choses the highest version with at least `2n/3+2` representatives

**Comment by nkcr** [comment]
Instead of adding a new `Version *int` field, why not simply using the current ledger's block index?
If a contract wants to change its implementation, it checks the current ledger's block index and then knows that, for any greater block index than the current one, it must use its updated implementation.

**Comment by ineiti** [comment]
That's what Ethereum is doing: for their 'hard-forks', they have a list that defines which version of Ethereum is to be used at what block-index. But then you need to carry around a configuration that defines for which chain-instance you change the versions.

My proposition allows every contract to update itself and then be backward-compatible, for any number of chain-instances, without having to define globally which version should be used.

**Comment by nkcr** [comment]
> But then you need to carry around a configuration that defines for which chain-instance you change the versions.

can't this information be kept on a per contract basis? Each contract could be responsible of keeping its own list of block idx that matches each of its own different implementations.

If a contract `A` has 3 different implementations: `A1, A2, A3`, then it can keep a hard coded list of block indexes, for example: `[12, 39]`, that says: "Use `A1` until block 12, then use `A2` until block 39, then use `A3`". 
Adding a new implementation `A4` after block index 45 would only requires to update the hard coded list: `[12, 39, 45]`.

**Comment by ineiti** [comment]
That _could_ work, but then you'll have to mix handling of global state (the version of the contract) and handling of instance state (data of this instance) in the same code, which looks sub-optimal to me. Also, it would be difficult to handle a `replay` method, where the `v2` contract is replaying blocks from a contract that should stay in `v1`. How would the contract know that it's only replaying and that it should not start behaving in `v2`-mode?

**Comment by nkcr** [comment]
I am surely missing something, but I would handle it exactly as if we had your proposed `Version *int` field, but instead of using like `rst.getVersion()` we would use `rst.getIndex()`.
