### ISSUE TITLE
implementation of Atomix protocol

### ISSUE THREAD

**Issue by kewangcmu** [dedis/cothority#1872]
Can anyone give me a pointer on the implementation of the Atomix protocol in the Omniledger paper? Thanks!

The Atomix protocol was reported to be used when there are cross-shard transactions. It implements a lock-unlock logic to avoid partially spent coins.

**Comment by ineiti** [comment]
The current implementation is only that of ByzCoin. There is an OmniLedger project from a student, but it never got merged to the main branch, due to a lack of testing and quality: 

https://github.com/ineiti/student_18/tree/patch-1/omniledger_sharding

**Comment by jeffallen** [comment]
Closing because it seems to be answered, please re-open if you need more info.
