### ISSUE TITLE
Java bn256 makes too much garbage

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1877]
@yanngabbud noticed frequent GCs when using the Cothority java client inside of an Android app. Memory profiling indicates that this is due to thousands of BigNum, which come from GFp[2,6,12]'s, which come from the loop in OptAte.miller.

(Yann will add additional info to this issue when he can export it.)

The challenge is to try to find a way to make less garbage, perhaps by calling new GFpX less often in the miller test's loop, by reusing existing points on each time through the loop.

**Comment by kc1212** [comment]
Yes it will create a lot of garbage. It is due to my laziness when porting the code, sorry about that.

In the go code, it "manually" does garbage collection using a pool. Whenever you want a GFp to work with you get it from a pool https://github.com/golang/crypto/blob/master/bn256/twist.go#L103, whenever you're done with it you put it back to the pool https://github.com/golang/crypto/blob/master/bn256/twist.go#L148. I didn't do any of that in Java. I think that's the right fix for this issue.

**Comment by yanngabbud** [comment]
Here are some data that may be useful to you. These data come from a call to the methode ByzcoinRPC.fromByzCoin().

![Screenshot from 2019-05-14 12-04-31](https://user-images.githubusercontent.com/36629634/57690161-52771b00-7641-11e9-9922-af2b9d02c7a3.png)
[Heap_dump.zip](https://github.com/dedis/cothority/files/3177048/Heap_dump.zip)

**Comment by nkcr** [comment]
Update: The `BigInteger` class we use is immutable, so using a pool won't work. A possible solution is to find and use another mutable `BigInteger` class.

**Comment by nkcr** [comment]
@yanngabbud I published a branch that uses a pool of GFp2 => https://github.com/dedis/cothority/tree/gfp2-gc-optimization

Can you try it and check if it improves?

**Comment by yanngabbud** [comment]
@nkcr I tried your fix and it is definitely better as you can see on the screenshot, but there is still a lot of gc calls. Maybe the problem come from the method `GFp12 exp(GFp12 a, BigInteger power)`. In this method there is a for loop that call the method `GFp12 mul(GFp12 a, GFp12 b)` and this method generate new GFp6. Maybe a pool of GFp6 may fix the problem as for `miller()` method.

![Screenshot from 2019-05-25 11-32-41](https://user-images.githubusercontent.com/36629634/58367918-79590b00-7ee5-11e9-8c07-988ce8361703.png)

**Comment by nkcr** [comment]
Nice to see an improvement! I updated the branch with a pool of GFp6 and GFp12, let's see if that solves the problem.
