### ISSUE TITLE
SDA - improvements

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#188]
* Public / Private : A lot of stuff is still public in the SDA. we must reduce to the minimum the API surface exposition to the user so it is easily understandable, safer, les prone to api change errors etc etc etc
* Debug output: Since we started from scratch we should really well define debug level and at appropriate place, because now it is already kind of a mess, and most of the debug output are un-usable.
* What else? SDA is very good.

**Comment by Liamsi** [comment]
Nice, a "bit-rot"-prevention-issue ;-) 
Regarding debug-output: We currently use the dbg package for all kinds of log output (and not only for debug output). For a server application it might be actually useful to know **when** sth. happend (and not from which line it came which is indeed very helpful for debugging). E.g. when we used the debug output for finding out why the test-cothority wasn't running as expected it was difficult to understand if an output was triggered before or after a certain event. There are several existing logging libraries we could use (instead?) for this (also levelbased).

**Comment by ineiti** [comment]
@nikkolasg: *most debug output are unusable*:
- how do you use it?
- what do you propose?
- what didn't show up while you searched?
Personally I do use the debug-output a lot and change often the debug-level to find what's going on. And yes, I also adjust the levels a lot, because as the code matures, what was important to debug, is not so important anymore later.

Public/Private - now here we go with a mess. My proposition is that the user only needs to know about `Node` - the rest is not necessary.

@Liamsi Please point to a debug-library that has a *numerical* debug-output instead of "fatal, error, warn, info".
I added some comments for the 'correct' debug-levels in
https://github.com/dedis/Coding/blob/master/README.md

And if anybody is able to have a running debugger for Go, I take it!

**Comment by ineiti** [comment]
Please also look how people use the library and what they are doing 'wrong' all the time. For example I had difficulties explaining the difference between `Node.Children()` and `Node.Parent().Children`: once Children is a function, once it's an element of a structure.

The same goes for all other accessors in `Node` which are done using a function. Personally I prefer elements of a structure, even though it's not as 'secure' against wrong usage as functions.

**Comment by ineiti** [comment]
And please do use a dictionary in whatever editor you're using.

**Comment by Liamsi** [comment]
+1 for the dictionary/spell checker

**Comment by nikkolasg** [comment]
>how do you use it?

I don't get the question...  The problem is everything is mixed, mostly all the debugs are Lvl3, so if you search for something higher-level than the message dispatching, you have to go through all the messages including the dispatching debug output  to find the relevant lineS.
>what do you propose?

Since the beginning we don't use the 5 levels (especially lvl2 & 4). Two solutions:
* either we fix strict rules for the 5 levels, llike every network related = 5, message passing = 4, protocolinstance / sda = 3, etc. The guidelines you put in the README are confusing for me:

> 2 - additional information which doesn't spam the screen when running with more than 20 hosts
>3 - debugging information for following the code-path, only useful for up to 20 hosts
 
What are exactly the differences between 2 & 3 ? And 20 hosts is already a big number to debug !
Then Lvl 4 is "everything else" ?
* Or we reduce the number of levels to 3, since we use mostly three different debug lvl. It may be easier than fixing strict rules on 5 levels, and still totally usable / readable. In the guidelines you even say that lvl 5 is unused, so we should be able to throw the Lvl5 away.

I tend to go for the latter option.

> what didn't show up while you searched? Personally I do use the debug-output a lot and change often the debug-level to find what's going on. And yes, I also adjust the levels a lot, because as the code matures, what was important to debug, is not so important anymore later.

Of course we use it a lot also, how do you think we debug ;) It's not what **did not** show up, but more what **did** show up = too much ! Maybe you do change the levels after but there's still a lot that are inadequate ("starting of protocol" debug output at same level as message processing with the whole message printed in bytes), that's why this issue is raised.

>Public/Private - now here we go with a mess. My proposition is that the user only needs to know about Node - the rest is not necessary.

+1 Absolutely ! And in Node, there are some methods that don't need to be exposed also ( like DispatchMsg etc)

> Please also look how people use the library and what they are doing 'wrong' all the time. For example I had difficulties explaining the difference between Node.Children() and Node.Parent().Children: once Children is a function, once it's an element of a structure.

We can try to unify that by using functions in TreeNode too so it looks uniform.

**Comment by ineiti** [comment]
Opened an issue #191 about debugging.

**Comment by ineiti** [comment]
Choosing between accessor-functions and accessing the variables directly (even for read-only), I prefer variables. 

For accessor-functions we'll have to change all accessor-functions to return a copy of the structure, which can be difficult, specially with regard to `Tree`s or `TreeNode`s which also store information about parents or children.

**Comment by nikkolasg** [comment]
> For accessor-functions we'll have to change all accessor-functions to return a copy of the structure

 Why? Can't we simply return the field ? It's not a golden rule of getter to return a copy I think, e.g. [Wikipedia] (https://en.wikipedia.org/wiki/Mutator_method): 
> by a getter (also known as an accessor), which returns the value of the private member variable.

**Comment by Liamsi** [comment]
What is most urgent (I think) is that the current SDA framework seems to have **data races** all over the place. Golang provides a nice tool to find those. If we ignore all the warnings we could end up not finishing some simulation in time (thin of a near deadline) because we spend hours on debugging. I already fixed JVSS (with the help of @nikkolasg). JVSS doesn't even use a lot of SDA... If I run the CoSi tests with race detection on, I currently see 19 data races! (For JVSS, a simple protocol it took half a day to fix #199 and #212 )
Will open an issue for that.

**Comment by nikkolasg** [comment]
Another improvement:
* Make sure sda library won't ever block even if a ProtocolInstance blocks. For the moment we dispatch a message to a channel but that operation may be blocking at some point if the ProtocolInstance is blocking. We should be able to have a buffer of messages for each nodes. Each time a message comes, sda appends it to the buffer. Then the node try continuously to send something to the protocol instance.

**Comment by Liamsi** [comment]
Every mentioned improvement is already taken care of in other issues.
