### ISSUE TITLE
Create new forward-links

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1883]
A new leader should check whether he needs to request additional forward-links from previous blocks, in order to optimize the chain.

The current `9cc3` chain has a lot of missing higher-order links, which means that currently the shortest path from the genesis-block to the block 400 is 23 blocks instead of the optimal 5!

And we should also check why the genesis-block doesn't add any new forward-links.

**Comment by jeffallen** [comment]
We fixed this with the scmgr optimise feature, I think.
