### ISSUE TITLE
Merge message structs and their SDA-wrappers

### ISSUE THREAD

**Issue by Daeinar** [dedis/cothority#189]
I think it would be good to merge message structs, as used by an SDA-protocol, and the wrappers around those structs, as required by the SDA-framework. The current solution requires a protocol-designer to specify two structs for a message instead of just one. In other words, move from this

```
// The protocol message
type Msg struct {
    // message fields
}

// SDA-wrapper around Msg
type WMsg struct {
    *sda.TreeNode
    Msg
} 
```

to this

```
// The protocol message
type Msg struct {
    *sda.TreeNode
    // message fields
}
```

**Comment by ineiti** [comment]
Le 03/02/2016 15:24, Philipp Jovanovic a écrit :
>
> I think it would be good to merge message structs, as used by an 
> SDA-protocol, and the wrappers around those structs, as required by 
> the SDA-framework The current solution requires a protocol-designer to 
> specify two structs for a message instead of just one In other words, 
> move from this
>
> |// The protocol message type Msg struct { // message fields } // 
> SDA-wrapper around Msg type WMsg struct { *sdaTreeNode Msg } |
>
> to this
>
> |// The protocol message type Msg struct { *sdaTreeNode // message 
> fields } |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dedis/cothority/issues/189>.
>
good call - I thought about the same. If everybody is OK with that, I 
can do that tomorrow (as I wear the 'reflect'-hat for the moment :)

**Comment by Daeinar** [comment]
@ineiti: Feel free to go ahead, you have the 'assign'-hat as well now. ;)

**Comment by ineiti** [comment]
Next try ;)

**Comment by ineiti** [comment]
Look if an error-handling on `Handler`s and `Channel`s is possible.

**Comment by ineiti** [comment]
In the services we started to use

`func Process(e *network.Entity, msg *Processing)`

which, when used also in the protocols, would be much more easy than fiddling around with the structures in reflect.

**Comment by ineiti** [comment]
Followed by https://github.com/dedis/onet/issues/207
