### ISSUE TITLE
Investigate byzcoin leader behavior when subleader is down

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1898]
It seems that over the week-end of 18/19 May 2019, one of the subleader nodes has been down. As a consequence, none of the transactions went through. I suppose (if @jeffallen can confirm by looking at the logs) that the leader simply accepted his fate of the block not being accepted, and dropped all transactions that were supposed to be in this block.

So if the leader would re-shuffle the tree in case of a timed out block, that would fix this issue.

**Comment by jeffallen** [comment]
I could not find logs to support or contradict this theory. I think the next step on investigating this should be to try to create a unit test where we know that a subleader is down and see how the system behaves.

**Comment by jeffallen** [comment]
We think this is done, closing until we see it again.
