### ISSUE TITLE
Organise branching

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#19]
I think we need to organise branching and merging better.

Nicolas found this interesting link which looks nice, IMO:

http://nvie.com/posts/a-successful-git-branching-model/

I propose we implement such a new 'development' branch. Even though we have then to define how a feature branch gets merged into the 'development' branch - which only pushes the problem of when to merge a bit further.

**Comment by ineiti** [comment]
Added a 'development'-branch where the different feature-branches can be added. To merge to the 'development'-branch, it needs to be accepted by at least two developers.

**Comment by bford** [comment]
Just had a chance to read that article - I agree, that seems like a perfectly reasonable branch development model; let's go with it.

We need to start a "dedis house rules" wiki or Google docs page or something like that somewhere specifying standard internal practices and with pointers to things like this that we decide to adopt.  I seem to recall there might already be a wiki that our LCA-group admins are managing; I'll check.

**Comment by ineiti** [comment]
We also started to use Zenhub:

https://www.zenhub.io/

The biggest advantage is the fact that it’s directly integrated into Github - check it out. Every issue can come into one of several pipelines and you can assign issues to people.

Either we use the LCA-wiki or the Github-wiki, which also looks nice.

**Comment by bford** [comment]
Good find!  Looks quite reasonable; let's try it.
