### ISSUE TITLE
Differentiate uuid.UUID

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#190]
`uuid.UUID`s are used for different IDs. To name just a few:
- TreeNodeID
- EntityID
- TreeID
- others

We should use types for each ID which point to uuid.UUIDs, so that we don't mix up the different IDs. This has to be done for all the code.

**Comment by Daeinar** [comment]
+1

That would make the code much clearer!

**Comment by Liamsi** [comment]
I can work on this one. 
Besides the above mentioned UUIDs, do you all agree on naming the one returned by `RegisterMessageType` as `MessageType` (instead of MessageID)?

**Comment by Liamsi** [comment]
I started with this one. I have a question here: Would you prefer two types `EntityID` and `EntityListID`? Currently they are used interchangeably (possible because everything is just a UUID), see here: https://github.com/dedis/cothority/blob/6484a74cf3e99521821636bcc108831476a40244/lib/sda/tree.go#L212-L214

**Comment by ineiti** [comment]
The example you give is a hack - blame says it's mine :( I remember having done that to avoid having a field that is only used for the root. Bad programming, sorry.

There should be two IDs for Entity and EntityList, but then that part has to be somewhat rewritten.

**Comment by Liamsi** [comment]
OK. I will see how much changes are necessary for that. The easiest way would be to cast from one type to the oder (which would also be a hacky way...)

**Comment by ineiti** [comment]
Or store the EntityListID somewhere else - it's only used in the root-node of the TreeMarshal anyway.

**Comment by Liamsi** [comment]
It seems like it is already stored somewhere (or is this another one): https://github.com/dedis/cothority/blob/6484a74cf3e99521821636bcc108831476a40244/lib/sda/tree.go#L276-L277

**Comment by Liamsi** [comment]
Note for my slef: Sometime we compare uuids using `uuid.Equal` sometimes we use the `==` 
-> write a test to  make sure both work as expected

**Comment by Liamsi** [comment]
> Or store the EntityListID somewhere else - it's only used in the root-node of the TreeMarshal anyway.

OK, just created a new field for this purpose. 

But we have similar problems for `NodeId` which also (sometimes) identifies the `TreeId` ...

**Comment by Liamsi** [comment]
> But we have similar problems for NodeId which also (sometimes) identifies the TreeId ...

And sometimes it even identifies the `TreeNode`? 
here ist stores the `TreeID`: https://github.com/dedis/cothority/blob/6484a74cf3e99521821636bcc108831476a40244/lib/sda/tree.go#L74
here it stores the `TreeNodeID`: https://github.com/dedis/cothority/blob/6484a74cf3e99521821636bcc108831476a40244/lib/sda/tree.go#L235
and NodeId sounds like it stores the Node's id... No wonder @Daeinar was confused.

**Comment by Liamsi** [comment]
Wow, what a quickfix ;-) All tests run fine (in PR #320). Maybe some further manual testing would also be appropriate. 
Another good thing about adding a type for each ID is that all the other packages don't have a direct dependency to the 3rd party `go.uuid` library anymore. So if it disappears we are in less trouble.

**Comment by Daeinar** [comment]
Merged #320.
