### ISSUE TITLE
Debugging-library

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#191]
We're outgrowing the simple debugging-library. For the moment we have different verbosity-levels (1-terse .. 5-spam), but we could go further and
- define tags (network, sda, ...)
- print depending on tags, structures, levels, ...
- add time

What is useful?

**Comment by Liamsi** [comment]
If we have clarified what is needed: It might be worthwhile to see if other people didn't already solve all these in their library: http://stackoverflow.com/a/31076772 (there is also one where you can define the verbosity in a numeric way, which seems important)

**Comment by ineiti** [comment]
@Liamsi - make two propositions with their pros and cons and decide with @nikkolasg and @Daeinar how to best replace ageing `lib/dbg` (I really like that one).

Consider my list I wrote above to see which library would be good. Filtering according to tags really is a killer-feature for me. This could also go to the command-line (like `-debug 2`).

So if none of the library has that, add it to `lib/dbg`...

**Comment by ineiti** [comment]
For the moment this doesn't seem to be an issue anymore.

**Comment by Liamsi** [comment]
Yes, and we have more urgent tasks. I still think people will want at least a log output with a time per output (if the deploy their own node). 
Close and create a new issue when/if relevant again?

**Comment by Liamsi** [comment]
I still think this is relevant and if CoSi will deploy CoSi we will have to integrate some form of logging anyways.

**Comment by nikkolasg** [comment]
Is it still relevant ? The issue is 9 month olds and we never referenced to it in any of our problems since. I propose we close it.
@ineiti  ?

**Comment by ineiti** [comment]
Yes, I still like that library ;)
