### ISSUE TITLE
Show args of the instructions in a proposed transaction

### ISSUE THREAD

**Issue by nkcr** [dedis/cothority#1937]
#1924 
> to see the proposed argument, use bcadmin contract deferred get, but it needs to show the args, using a heuristic to try to show ASCII if there is enough, see strconv.Quote. Or maybe BasicContract should implement String() and contract writers should be encouraged to override it?

This happens to be actually much more tricky. Using `strconv.Quote` or other heuristic methods is not sufficient to provide meaningful information about an instruction, especially for more complex instruction like `invoke:config.update_config` that has a `Config` as argument.

**Problem statement**:

Given an `Instruction` only, print this instruction along with the potential arguments contained in the `spawn` or `invoke` methods, which depend on the contracts.

**The problem**:

Only contracts know how to print their arguments, but we are left with only an `Instruction` that can provide an `action` string of form `invoke:config.update_config`.

**One solution**:

One dirty solution would be to manually check the `action` string, extract the contract name, and call a new `PrintArgs` function on that contract that can be overrided by contracts or has a default behavior (like using `strconv.Quote`) implemented on `BasicContract`. It would be like:

```go
name := extractName(action)
switch(name) {
  case "value":
    return PrintValueArgs(action, args)
  case "config":
    return PrintConfigArgs(action, args)
  ... 
}
```

**Comment by ineiti** [comment]
And it also has to work in `java` and `javascript` ;) In the current `c4dt/omniledger` js-frontend I manually check the `contractID` and then interpret the arguments. 

For `go` you could extend the `byzcoin.Contract` with a `Print` and a `PrintArgs`, then you can write `GetContractConstructor(contractID).PrintArgs(args)` or so.

PS: in the example you give, is the `switch` really on the `name`, shouldn't it be on the `contractID`?

**Comment by nkcr** [comment]
> I'm not sure if there should be a `PrintSpawn` and `PrintInvoke` instead of a `PrintArgs`.

For the same contract the arguments can be very different if it's a `spawn` or `invoke`, which is why I use different functions. But OK, there could be a switch inside a global `PrintArgs` that checks the action.

 > PS: in the example you give, is the switch really on the name, shouldn't it be on the contractID?

Could be too. On my example, `name` is extracted from `Action()`, which contains the `contractID`.

---

I don't really like this solution: contract should be only implemented in one single place, but there we require to update another piece of code. In an ideal situation, the `PrintArgs` method should be implemented in the contract.

**Comment by ineiti** [comment]
> I don't really like this solution: contract should be only implemented in one single place, but there we require to update another piece of code. In an ideal situation, the `PrintArgs` method should be implemented in the contract.

Yes, definitely. My proposition to enhance the `Contract` interface would mean that 
1. you can have a default implementation in `BasicContract`
2. every contract can define its own `Print*` methods

So it is 'implemented in one single place'. Or did I miss something?

**Comment by nkcr** [comment]
Oh, I didn't see that `GetContractConstructor` already exists... But in fact that doesn't help since this function belongs to a service instance, which is something I do not have (I only have an `Instruction`).

So, in order to have a "static function", we would need to write a new function with that `switch(instanceID) {...}` code.

**Comment by ineiti** [comment]
I don't see how to have the cake and eat it, too...
1. if you separate the `Print` from the contract, you run into _ contract should be only implemented in one single place_
2. if you keep the `Print` in the contract, you need a 'dummy' service to call `GetContractConstructor`
3. you could keep the `Print` in the contract, and register all contracts yourself in `bcadmin`, then write your own `GetContractConstructor`

My personal preference is `2.` - least amount of code necessary.

**Comment by nkcr** [comment]
I dare asking but... Is adding a référence to `BasicContract` in an
`Instruction` something doable? But guess it would make the protobuf
encoding/decoding too heavy, which is why we only keep a string identifier.

Le mar. 11 juin 2019 à 16:32, Linus Gasser <notifications@github.com> a
écrit :

**Comment by ineiti** [comment]
Can you elaborate why you want to reference `BasicContract`? And, as far as I see, `BasicContract`  only has methods, so I really don't see how you want to reference it...

**Comment by nkcr** [comment]
I should have mentioned `Contract`, not `BasicContract`:

* We add a field `InstrContract Contract` to `Instruction`, 
* update the `Contract` interface to include `Print() string` ,
* add a default `Print() string` function to `BasicContract`,
* when an instruction is created, either provide `BasicContract` or another implementation of `Contract` as the `InstrContract` field,
* when we want to print an `Instruction`, we use `instr. InstrContract.Print()`

**Comment by ineiti** [comment]
Well, `Contract` is an interface - as such I don't see how you want to pass it along over the network. You would have to do something similar like in the `kyber.Point` case with a decoder. Which is possible, but quite complex. And also would have to be implemented in javascript / java. So I don't see the advantage over my proposed point `2.` above...

Also, adding an `InstrContract` field to the `Instruction` just for printing seems not-optimal to me. The protobuf-messages should carry data, not methods.

**Comment by nkcr** [comment]
I am convinced !  I'll go for 2). 

How would you create a dummy service? I can't figure out how this `onet.RegisterNewServiceWithSuite(...)` and factories stuff work. 

A simple `s := Service{}` doesn't work..

**Comment by ineiti** [comment]
I don't remember where I did this and if it stayed in the final code or not ;) But looking at `onet/local.go`, I think you can do:

```go
ls := onet.NewLocalServer(cothority.Suite, 1234)
defer ls.Close()
bc := ls.Service(byzcoin.ServiceName)
cc := bc.GetContractConstructor("config")
```

The localserver uses only channels, so it shouldn't open any ports. However, there will be a db generated for the services. I don't remember how they are deleted.

**Comment by nkcr** [comment]
Thanks! 
We are getting close, however `bc` in an `onet.Service`, not a `byzcoin.Service`

**Comment by nkcr** [comment]
Emulating a `byzcoin.Service` is actually quite a lot of effort when the only very thing we want from the `byzcoin.Service` is its `contracts map[string]ContractFn` that maps a contractID to its constructor.

**New idea**: move `s.contracts` out of `byzcoin.Service` and make it staticly-publicly available. This map would then be filled from the `init()` function at package loading. No more dummy service needed.

**Comment by ineiti** [comment]
> however bc is an onet.Service, not a byzcoin.Service

OK, do this:
```
bc := ls.Service(byzcoin.ServiceName).(*byzcoin.Service)
```

> Emulating a byzcoin.Service is actually quite a lot of effort when the only very thing we want from the byzcoin.Service is its contracts map[string]ContractFn that maps a contractID to its constructor.

Yes, that's the not-ideal part of my solution `2.`, the other one is the creation of a `.db` file that should be deleted. But if you want to change that you'd have to change quite a lot the structure of the services and the contracts, and I'm not even sure it will all work out.

Else you do `1.` and register a `InstructionPrinter` that is globally public in the byzcoin service. But personally I still prefer `2.`, as the overhead is not that big.

> **New idea**: move `s.contracts` out of `byzcoin.Service` and make it staticly-publicly available. This map would then be filled from the `init()` function at package loading. No more dummy service needed.

This won't work, because the contracts are registered when the services start up. This is because the contracts often need access to the service they come from, so you cannot register the contracts in the `init` method.

**Comment by nkcr** [comment]
> This is because the contracts often need access to the service they come from

True! 
But it happens that every contract that needs a service actually use the service only to get the constructor of another contract.

I have committed a branch with the changes and it happens that tests pass. We might now discuss under what circumstances a contract may need to access  a`Service`, and if removing this functionality in favour of a public constructor map is satisfying.

**Comment by ineiti** [comment]
OK - sounds good. If the current contracts don't really need the service they are registered by, then perhaps they don't need it at all.

And if later a contract will need some more information, I'm all for extending the `ReadOnlyStateTrie` structure and add additional methods to get information about the block, like in #1854, or other information.

So I'm all for the registration of the contracts outside of the services. In fact, the `byzcoin/contracts` only have a service to register the contracts, which is also non-optimal. So taking that out looks like a good move!

Can you link the branch to a PR linked to this issue?
