### ISSUE TITLE
Use depth instead of hosts in .toml-files

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#194]
When writing the toml-files in `simul/runfiles` we can give the branching factor (BF) and the number of hosts (Hosts). To have fully-populated-trees (each nodes has either no children or the BF children) we can use a depth-parameter (Depth) which can be used instead of the 'Hosts'-parameter. This will add

( 1 - BF^(Depth + 1))/(1-BF)

hosts and such create a fully-populated tree.

**Comment by Liamsi** [comment]
Can be done directly `lib/sda/simulation.go` in the SimulationBFTree.

**Comment by Liamsi** [comment]
Fixed in #237
