### ISSUE TITLE
Make simul/matplotlib work on newer MacOSX

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#195]
`simul/matplotlib` has two useful libraries: one for reading .CSV generated by the simulation and another one interfacing with `matplotlib`. The latter is somewhat a moving target. For the moment it uses 1.4.3 and fails if something else is installed.

Update to 1.5.1 - there are some functions that changed their arguments. Also update the installation-instructions if matplotlib is missing.

**Comment by Liamsi** [comment]
Merged
