### ISSUE TITLE
Attack on ByzCoin proof

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1959]
# Problem

The current byzcoin proof is supposed to proof the existence or absence of an instance, given only the byzcoin-id. It does this by providing the following items:

1. forward-links that link the byzcoin-id to the latest block
2. latest block including the hash of the global state merkle-tree-root
3. inclusion proof from merkle-tree-root to the instance leaf
4. the instance leaf itself

Unfortunately, `1.` is flawed. It is supposed to link the byzcoin-id, which is the hash of the genesis-block, to the latest block. It uses the forward-links, which is a signature on:
- hash of the source block
- hash of the destination block
- the roster of the destination block, if the roster changed

This signature can be checked against the aggregate public key of the source block. Now the client only has the byzcoin-id, so he cannot check the link of the genesis-block to the next block. This is why the first forward-link in the proof points from a `nil` source block to the genesis block, and includes the roster. But there is a problem:
- this first, initial forward link is not signed
- the client cannot verify if the roster is correct

So an attacker can simply create a new roster, use it to sign an erroneous forward-link to a new block, and then prove anything he wants.

# Proposed solution

The following solution makes sure that
1. during some phase-out, old clients can still rely on the wrong proof
2. new clients can correctly check the proof

I propose to add an optional `Genesis` field to https://github.com/dedis/cothority/blob/master/byzcoin/proto.go#L158 :
```go
type Proof struct {
	// InclusionProof is the deserialized InclusionProof
	InclusionProof trie.Proof
	// Providing the latest skipblock to retrieve the Merkle tree root.
	Latest skipchain.SkipBlock
	// Proving the path to the latest skipblock. The first ForwardLink has an
	// empty-sliced `From` and the genesis-block in `To`, together with the
	// roster of the genesis-block in the `NewRoster`.
	Links []skipchain.ForwardLink
	// The header of the genesis-block to prove the initial roster of nodes
	Genesis *skipchain.SkipBlockFix `protobuf:"opt"`
}
```

As long as old clients are around, the `Links` field needs to keep the first link pointing from `nil` to the genesis block. Old clients will simply ignore the `Genesis` field, and rely on this first link. New clients will ignore the first link, and use the `Genesis` field to verify the byzcoin-id and get the initial roster.

# Further thoughts

Once we allow for proofs that don't start at the genesis-block, the `Genesis` field will be empty, and the links start at the latest known block to the client.

**Comment by Gilthoniel** [comment]
Can't the initial roster be verified by checking the hash of the genesis block ? I'm not sure why this `nil` source is necessary because if you assume the ByzCoin ID is correct, you can insure that what is inside the genesis block is correct, right ?

**Comment by ineiti** [comment]
We suppose that the client only has the byzcoin-id, which is the hash of the genesis block. The client doesn't have enough information, even with the initial roster, to re-create the genesis block and calculate the hash.

**Comment by Gilthoniel** [comment]
But the proof contains the genesis block so the information stored inside can be verified against the ID.

**Comment by ineiti** [comment]
Yes, that was my proposition, to add the `Genesis` field in there ;) Should've made that clearer, probably...

In fact, it should perhaps not be `Genesis`, but `First` or so. Then, if somebody implements #1960, the field-name could stay the same.

**Comment by Gilthoniel** [comment]
I started working on this but I'm facing troubles with the usual downgrade attack of a backwards compatible change. An attacker could simply set the Genesis field to `nil` in order to revert the verification to the old process and you can't assume the Genesis field will always be filled as old conodes won't fill it.

The first solution I'm seeing is to add a function `VerifyFromBlock` that will take an additional block as parameter that will be fetched by whoever wants to verify the proof. One benefit is that at the service level you know the block so you can get it from the DB, but a client will need to two requests if it doesn't know the block.

**Comment by ineiti** [comment]
I would simply allow for one version (3.1.x) that the `Genesis` / `First` is missing, and then in the cothority-npm / cothority-java for version `3.2.x` refuse if the `Genesis` / `First` is missing. There are not that many libraries around using the current proof...

**Comment by ineiti** [comment]
And if you keep the first link to point to the genesis block (as it is now), old libraries will continue to work.

**Comment by Gilthoniel** [comment]
So after talking with @jeffallen we decided to not add the block to the proof but to have a stateful client a bit like you did for the Javascript library which means that the client is responsible to fetch whatever it needs to check the initial state.

**Comment by ineiti** [comment]
Hmm - this means that a proof is now not offline-verifiable anymore if the client has just the `byzcoin-id`. Now the client needs both the `byzcoin-id` and the `genesis-header`.
