### ISSUE TITLE
Redo plots for cosi-paper

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#196]
In the directory `simul/runfiles/Paper_cosi` there are a number of .toml-files for the simulations done for the paper. Make a new directory `simul/runfiles/Paper_cosi2` and copy over the .toml-files and make them work on the new infrastructure.

Also make a new directory `simul/matplotlib/Paper_cosi2` and fill it with the simulations done in `simul/runfiles/Paper_cosi2`, so that the graphs can be compared.

**Comment by Liamsi** [comment]
Thanks for the hints!

**Comment by Liamsi** [comment]
Related issues: #180 #199 #200

**Comment by Liamsi** [comment]
After resolving the depending issues (or before using one of the example simulations in `protocols/example/channels` or `protocols/example/handlers`) either adapt `mplot.py` or rewrite it to match with the new csv output.

**Comment by ineiti** [comment]
Closing this one and writing multiple small ones....
