### ISSUE TITLE
byzcoin should check that contracts of StateChanges are valid

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1966]
If a contract emits StateChanges with a contract name that is unknown, then the execution of the contract should fail.

**Comment by ineiti** [comment]
I think that would break our current evm implementation, as we're emitting `StateChange`s that are not tied to a contract. So we could get over this by defining a dummy-contract, but this feels clumsy.

Also, how are the signer-counters updated? I remember that they have an empty `contractID`, but I'm not sure anymore if there are `StateChange`s emitted... Theoretically they should.

So I know of 1-2 examples where this would not currently work.
