### ISSUE TITLE
Leader does not filter identical transactions

### ISSUE THREAD

**Issue by cgrigis** [dedis/cothority#1987]
When a client sends a transaction to ByzCoin, it will send it to multiple members of the roster for redundancy. The leader may consequently receive multiple times the same transaction, and does not currently seem to filter them. All transaction copies after the first one will then be rejected with an error about invalid counters, such as the following:
```
(...) and returned error: instruction verification failed: for pk ed25519:7072c949808ca44df779d79bf03a8e0c12b3d03713b442876022cef44442b26a, got counter=12, but need 13
```

It has no consequence on the correctness of ByzCoin, but is a waste of time and resources.

**Comment by ineiti** [comment]
Specifically of engineering resources that try to figure out why the counters are wrong ;)
