### ISSUE TITLE
Return errro messages for transaction failures

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#2013]
We need a better to present the errors during a transaction failure. Right now the error simply gets logged by `log.Error`. The return value of a `AddTransactionAndWait` is always something like "transaction got refused" but it never says why it got refused.

We need to return a better error so that the caller and the test can check exactly what happened.

**Comment by ineiti** [comment]
Yes, sounds very good. As I wanted to work on that, too, here my idea:

`bcNotifications.createWaitChannel` actually returns a `chan ctxResult`, which `ctxResult being something like:

```
type ctxResult struct {
  Accepted bool
  // Empty if Accepted == true
  Error string
  // Which block holds the clientTransaction
  BlockIndex int
  // Index of the transaction in the TxResults
  CtxIndex int
}
```

And then the `ctxResult` is returned to the caller. But that's just my first idea.

**Comment by kc1212** [comment]
if I understood your solution correctly, it might not work due to the way we cache state changes. The error messages are only present the first time you execute the instruction which could be in `verifySkipBlock` or `createNewBlock` depending on whether you're the leader.

My plan is to have a go-routine store the errors (the errors are submitted by `createStateChange`). When we're ready to return errors back to the caller then we check whether there are any errors for the given block.

**Comment by ineiti** [comment]
I see what you mean. Couldn't `processOneTx` write any errors it has to a `map[TxHashWithSignatures]string` and then `updateTrieCallback` could pick any errors out of this map and use it when calling `informWaitChannel`?

**Comment by kc1212** [comment]
> I see what you mean. Couldn't `processOneTx` write any errors it has to a `map[TxHashWithSignatures]string` and then `updateTrieCallback` could pick any errors out of this map and use it when calling `informWaitChannel`?
> 
> Of course there would need to be some cleanup with that map to make sure we're not collecting errors of all transactions...

yeah I'm doing something like this now, using a go-routine to manage errors is an overkill. But we have another problem, websocket doesn't support long errors, from my testing the maximum length is 105 characters. From looking at the code it should be a bit more, about because [`maxControlFramePayloadSize`](https://github.com/gorilla/websocket/blob/master/conn.go#L397) is 125. Nevertheless, we cannot send large error messages back. So the compromise is to only send the most specific error. V4 will have a better error-reporting story because it'll be either grpc or REST based.

**Comment by ineiti** [comment]
Why don't you pack the error in the `AddTxResponse` structure? And put the websocket error to "failed transaction" or so?

**Comment by kc1212** [comment]
good idea.. we never used it for anything so i totally forgot about it

**Comment by kc1212** [comment]
actually, we can't use `AddTxResponse` when there is an error because onet doesn't write the actual response back to us. I will see if we can change onet to add the response...

**Comment by kc1212** [comment]
after some investigation, i don't think it's possible to reply with a message and an error for the following reason

the error we get in websocket is from: 
```go
	ws.WriteControl(websocket.CloseMessage,
		websocket.FormatCloseMessage(websocket.CloseProtocolError, errMessage),
		time.Now().Add(time.Millisecond*500))
```

if we want to add an reply, we have to do something like:
```go
	if err != nil {
		if len(reply) != 0 {
			if err := ws.WriteMessage(mt, reply); err != nil {
				log.Error(err)
			}
		}
	}
```
just before the close message.

However, if we write anything before the close message, the client will simply return with no errors because its call to `conn.ReadMessage()` succeeded.  Effectively, the client returns success before it sees the error message.

**Comment by ineiti** [comment]
OK - you mean that if you return an error PLUS a response, the response gets dropped?

We could say that the `AddTransaction` DID successfully add a transaction. However, while adding the transaction, an error was raised. So we could return only the `AddTxResponse`, and eventually use the `byzcoin.Client.AddTransaction` to return an error + a message... Or is that too weird?

**Comment by kc1212** [comment]
> OK - you mean that if you return an error PLUS a response, the response gets dropped?

The error gets dropped if you do `ws.WriteMessage(mt, reply)` before `ws.WriteControl(websocket.CloseMessage, ...)`. 

> 
> We could say that the `AddTransaction` DID successfully add a transaction. However, while adding the transaction, an error was raised. So we could return only the `AddTxResponse`, and eventually use the `byzcoin.Client.AddTransaction` to return an error + a message... Or is that too weird?

I don't really understand this solution. So the client will make a second query to get the error?

**Comment by ineiti** [comment]
> So the client will make a second query to get the error?

No, the following happens upon a call to `AddTransaction`:
- if something is wrong before sending the transaction, return `nil, error`
- if the transaction is added to a block, return `AddTxResponse, nil`, where `AddTxResponse`
   - has an empty `Error` if the transaction has been accepted
   - has an `Error` filled out if the transaction has been refused

**Comment by kc1212** [comment]
I see, yeah I had this idea too but i found it too strange especially in golang.

The pragmatic way is to write code like `if x, err := dosomething(); err != nil {...`, but putting the error in `AddTxResponse` won't allow it. It's also somewhat backwards incompatible, because old client code will have to be updated to handle the new way of returning errors.

**Comment by ineiti** [comment]
You could handle this in the `byzcoin.Client.AddTransactionAndWait` and return an error in there if the `Error` field is non-empty. Yes, it's a hack, so you have to decide between two hacks:
1. truncate error messages
2. pass rejected transaction error in structure

Another reason I prefer 2. is the fact that I'd like to add (at least) two more fields to the `AddTxResponse`:
- `BlockIndex` to indicate in which block the transaction is in
- `TxIndex` to indicate at what position the transaction is in
And even nicer would be:
- `StateChanges` with the statechanges generated by the transaction
- `Instances` with the updated instance-data touched by the transaction

So at least the first pair of fields would still be nice to have, even for a rejected transaction. But you won't be able to pass these along if you return an error to onet.

**Comment by kc1212** [comment]
Yeah it's a choice between two hacks...

Your suggestion is works if the public API is only on the client side. But the public API of the service will change and this change (returning errors in the response) looks very odd to me when none of the other service APIs do it this way. The truncate method is not perfect but it won't change how we use byzcoin, it simply provides more detailed (but truncated) error messages.

Maybe we need a third opinion on this...

**Comment by jeffallen** [comment]
I'm ok with returning the transaction error in the reply structure. It's not beautiful, but it's what's needed, so let's get on with it.

**Comment by kc1212** [comment]
btw, the reason the errors are long is because the full instance ID is in the error messages, here is what the truncated errors look like (the first one is not truncated)

```
websocket: close 1002 (protocol error): unexpected error: tcp://127.0.0.1:60601: contract darc tried to create existing instanceID
websocket: close 1002 (protocol error): unexpected error: <truncated>7ddc2ecca and returned error: instruction verification failed: all signatures failed to verify
websocket: close 1002 (protocol error): unexpected error: <truncated>338582764dfe95d643df914528877 and returned error: instruction verification failed: key not set
websocket: close 1002 (protocol error): unexpected error: <truncated>900377cf13f and returned error: instruction verification failed: expression evaluated to false
websocket: close 1002 (protocol error): unexpected error: <truncated>481ff256c56c47c024aa8083ab3ee9575c55b9db7876fedb9 and returned error: the name cannot be empty
websocket: close 1002 (protocol error): unexpected error: <truncated>174728c5c8f661226921cc130554b752d9fd88f1e5f3f25ff and returned error: this name already exists
websocket: close 1002 (protocol error): unexpected error: <truncated>144350acada693bbec3150261224e957ad7dbb3ea9bd019fc4a1b85e5a1e09 and returned error: key not set
websocket: close 1002 (protocol error): unexpected error: <truncated>9a069928505944fb32f93d2cdb56c053532da13b59a7 and returned error: this entry is already removed
```
