### ISSUE TITLE
`lib/tree/tree.go` - GenerateBigNaryTree is not correctly colored

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#205]
Added a TODO in `tree.go` about how to change `GenerateBigNaryTree` to a correctly colored tree.

**Comment by Liamsi** [comment]
@ineiti : There is no TODO in `tree.go` about `GenerateBigNaryTree`.  Can you point to the branch where you added the TODO (or describe what the problem is, here)?

**Comment by ineiti** [comment]
Le 07/02/2016 15:50, Ismail a écrit :
>
> @ineiti <https://github.com/ineiti> : There is no TODO in |tree.go| 
> about |GenerateBigNaryTree|. Can you point to the branch where you 
> added the TODO (or describe what the problem is, here)?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dedis/cothority/issues/205#issuecomment-181026470>.
>
https://github.com/dedis/cothority/blob/sda_1/lib/sda/tree.go#L289

**Comment by Liamsi** [comment]
Thanks
