### ISSUE TITLE
Add logging-service

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2052]
In order to better debug the running byzcoin instance, a logging-service can help a lot. The basic idea is:

- add a `cothority/logger` service that registers itself using `log.RegisterLogger`
- every conode-admin can configure his logger to connect to a central logging service
- the central logging service should
  - be self-hosted by EPFL (DEDIS or C4DT)
  - have a nice web-UI to easily sift through the different messages

**Comment by tharvik** [comment]
One could use [Logstash](https://www.elastic.co/products/logstash) to merge/dispatch logs.

**Comment by ineiti** [comment]
Yes, that was one of the tools I looked at yesterday. But I didn't find an easy enough way (`apt-get install logstash` or `docker run logstash`) that would give me directly a nice GUI with:
- a simple user management
- possibility to send messages to it out of go
- nice dashboard with drag/drop adding of stats, filters, ...

But perhaps the rest of the elastic suite does have that?

**Comment by tharvik** [comment]
Yup, Logstash is only for the log handling, ES is for storage and processing, Kibana is for presenting.

> * a simple user management

Depending on how much "simple" you mean, there is an API there: https://www.elastic.co/guide/en/elasticsearch/reference/7.3/security-api.html#security-user-apis

> * possibility to send messages to it out of go

As long as your programming language can do IO, Logstash can read what it generates: https://www.elastic.co/guide/en/logstash/current/input-plugins.html

> * nice dashboard with drag/drop adding of stats, filters, ...

That's Kibana then :)

**Comment by ineiti** [comment]
Yes, but for a 'simple' logging-system, if I have to handle three components, I still put some time into investigating an 'all-in-one' solution. Just for update, peace-of-mind, and for the next guy...

**Comment by Gilthoniel** [comment]
I'm definitely against a full Elastic stack, that's overkill. Yes stats might be interesting but for the moment we mostly need access to the Cothority logs in one place split by conode.

We can always have a student project to improve this later.

**Comment by jeffallen** [comment]
This system should be opt-in, and then ideally with one single line in private.toml, for example:
```
CentralLogging: https://cloudwatch.eu.aws.com/245423/jhgd6sdhgdhgsd
```

i.e. "do central logging towards project 245423, using API key jhgd6sdhgdhgsd". The given API key was set up by the operator of the central logging system, one per conode.

I have no idea if such a thing exists, but that's about the maximum amount of complexity and dependency I'd like to introduce for this.

**Comment by tharvik** [comment]
A less centralized way (AWS) would be to use [collectd](https://collectd.org/), it has a [go library](https://github.com/collectd/go-collectd) to send logs easily.

**Comment by ineiti** [comment]
> This system should be opt-in, and then ideally with one single line in private.toml, for example:

Yes, that's exactly what I had in mind! Either `private.toml`, or have a CLI that is able to send and store this information in the conode.

**Comment by ineiti** [comment]
> collectd

I'm less concerned about the collecting part as about the displaying part. I know that sifting through logs can be hell, and if there is some nice filtering available, that would help a lot.

Again, on the other side, having a nice UI might be overkill for the first implementation.

**Comment by nkcr** [comment]
Pragmatic solution: 
implement a logging service that continuously saves chuncks of logs to a cloud storage endpoint. Each Conode would then have its own bucket that contains the chunck files, named after the creation time.

This would look like:

```
cloud-endpoint/
├── wookie/
│   ├── 19.09.19.11:08:02.txt
│   ├── 19.09.19.11:12:31.txt
│   └── 19.09.19.11:18:52.txt
├── nella/
│   ├── 19.09.19.11:07:12.txt
│   ├── 19.09.19.11:11:21.txt
│   └── 19.09.19.11:18:24.txt
```

That solution could be easily hosted on the dedis server (a minio server is already running for the SwissRE project) and would require small implementation on the conode side. We would then only have to implement a small script to gather the logs and display them nicely.

**Comment by ineiti** [comment]
> Pragmatic solution:
Two points I would like to avoid:
- storing things in chunks means that there is no 'real-time' update of the log messages
- having storage and display separated needs again two services that need to be integrated with each other (storage and display), where I'd prefer to use only one...

**Comment by Gilthoniel** [comment]
Also:

- Please don't make it a service. A logger usually has opt-in transport solutions. For instance right now the Onet logger has only a standard output transport but it should be able to add multiple ones (i.e. a rest, tcp, whatever one).

- It would be nice to have a behaviour similar to logrotate to limit the files in size and in time.

**Comment by ineiti** [comment]
@Gilthoniel - so you would rather like to see it integrated into `onet`, rather than `cothority`? That should also work. So something like `onet/log/remote.go`?

But then who would be responsible for enabling that logger? The `onet.Server`?

**Comment by ineiti** [comment]
And with regards to logrotate, this PR would only add a network-logger. There is already a file-logger in `onet/log`.

Then it would be up to the receiving service to handle the files however it wants. The conodes themselves would not need additional disk-space.

**Comment by Gilthoniel** [comment]
Yes, the remote transport is enabled when the server starts. It's not a problem, the configuration is available at this point.

**Comment by ineiti** [comment]
OK, sounds good.

**Comment by ineiti** [comment]
So the first try is to simply set up a https://www.graylog.org instance on the c4dt-server, and then redirecting the logs with
`conode | tee /dev/stderr | netcat graylog 9001`
The graylog runs with a raw tcp connector that just accepts anything.
This kind of works, except that the dedis-conode cannot talk directly to the graylog instance because of network-restrictions at EPFL ;)

**Comment by ineiti** [comment]
Done in dedis/onet#623
