### ISSUE TITLE
Connection-test service

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2053]
Add a service with a CLI that allows to send a `ping` to all other nodes given in a roster:
- the CLI should use the `private.toml` of the conode to sign the start of the request
- to avoid abuse, a rate limitation of 1/sec should be given
The connection-test can be done using https://github.com/dedis/cothority/blob/master/messaging/broadcast.go:
1. the requester uses the CLI tool to send a ping-request over the websocket
2. the service of the requester node sends out a broadcast-protocol `ContactNodes` using `CreateProtocol(name, tree, serviceID)`
3. all receiver nodes (excluding the requester node) catch this protocol-message in their `NewProtocol` and send out another broadcast-protocol `ContactNodes`, but this time using `CreateProtocol(name, tree, NilServiceID)`
4. upon reception of the reply of 3., the nodes reply back to 2.
5. the service replies back whether all could talk to all other nodes

If it's possible to have some stats, e.g., how long it took to contact whom, and which connections failed, that would be awesome.

**Comment by Gilthoniel** [comment]
What if instead of creating a new service, we use the already existing one (Status) that is very naive at this moment ?

 - The service gathers information with the other nodes periodically. To reduce the network traffic, it can check a server per minute or stuff like that so even if the Cothority has thousands of members, it scales.
- A status request can now contain information about others nodes so the front-end can display when a node fails to contact another one.

**Comment by ineiti** [comment]
I see services as separate, manageable tools, that can be enabled/disabled at wish (currently only through the `import` in `conode.go`).

If we put it in the `status`, how do you define the roster that the status service should check?

**Comment by Gilthoniel** [comment]
The status service can read from the skipchain service and make a list of peers to ping. Or we could also improve Onet to send notification when a connection cannot be established, or when a connection is broken from the other side and then the status service can listen for them. Then the status request can contain the skipchain id to resolve the roster internally.

**Comment by Gilthoniel** [comment]
So that we have a kinda automatic detection of connection failures on the website.

**Comment by ineiti** [comment]
Hmm - I feel that keeping that in a cache, making sure it's up-to-date, handle spurious timeouts, etc., will make this very hard...

Currently with the very_simple_log, there is already a view of errors - so we can look if there are failing connections. You can even create a view in graylog just for that...

I just hacked together a simple addition to the status-service that is protected by a signature by one of the nodes. I'll create a PR as soon as I have the CLI ready, then you can start shooting your critics there ;)
