### ISSUE TITLE
View-change improvement

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2054]
Currently a view-change is triggered if the leader doesn't ask for transactions. This helps to detect if the leader is down, but it doesn't help to detect if the leader is faulty. (At least) three more things would be needed:

1. Have the leader produce an empty block if he doesn't get any new transactions x (10?) times in a row. Then the followers can check that there is a new block every 2x blockIntervals, and if there is no new block, ask for a viewChange
2. Have the followers verify if their valid transactions have been processed by the leader or not. This is to avoid censorship by the leader. But it is difficult to implement, as the followers would have to prove that they actually sent their transactions to the leader
3. Change the leader on a regular basis
  - test if all leaders are OK
  - remove an eventual censorship without implementing 2.

**Comment by Gilthoniel** [comment]
Duplicate for #1963
