### ISSUE TITLE
Error-wrapping

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2061]
I would like to discuss when and how error-wrapping makes sense.

# Why
the goal of error-wrapping in go is to get a clearer indication of what is going wrong. E.g., if `protobuf.Encode` returns an error and that error gets into the logs, there is often no indication of which of the 100 `protobuf.Encode` went wrong. Here error-wrapping makes sense.

## How I use it
Personally I use error-wrapping to do a `<shift><cmd>F` of the error-message and then find which line is giving the error, and debug from there. So for my use of error-wrapping, I would be very happy to have something like

https://github.com/dedis/cothority/blob/calypso_ocs/ocs/helper.go#L97

So instead of

```
return nil, err
```

you could write

```
return nil, log.Erret(err)
```

and you'd get a clear indication of the error-stack. This would reproduce something like the java-stacktrace, but would also work over the network, where the error happens on the other side of the websocket and where a java-stacktrace would not indicate what went wrong.

## Current usage

In the current code, with error-wrapping being in the `Issue-TODO` list, I simply do things like

```
return nil, errors.New("Couldn't encode structure: " + err.Error())
```

which, for my use-case, helps, as long as there are not 100 `Couldn't encode structure: ` error-messages.

## Unnecessary error-wrapping

Sometimes an error-wrapping doesn't make sense. E.g., a method-call that is used only once, and where it is clear where the error comes from.

# Proposition (please edit)

- Wrap error-messages with `Erret` (or other name) where the error can come from multiple places
- Don't wrap error-messages where it is clear where the error comes from

**Comment by tharvik** [comment]
There is this go library to do that, while also producing a chain of error to allow better automated instrumentation: https://github.com/pkg/errors

**Comment by nkcr** [comment]
> * personally I prefer, once a decision on how to wrap errors is made, to have it done without exception

I totally follow you on this one!

> Wrap error-messages with Erret (or other name) where the error can come from multiple places

I failed to convince myself on this one. It looses the simplicity if "just" returning a plain old `"failed to ... " + err.Error()` and makes the message less readable (like a stack trace...).

The nice thing if every errors are wrapped is that we should end up with each error message being a uniq path from the root to the leaf of a tree, where each node of this tree is an error wrapping message and its children the possible errors. Like so it is always possible to find the exact place an error occurs (in case the last error message is not uniq). (and, if there are multiple "roots", those must have uniq messages)

**Comment by nkcr** [comment]
Leaving this example of error wrapping here https://play.golang.org/p/IOVg9ojqM5g

**Comment by Gilthoniel** [comment]
As @cgrigis mentionned, there's the future Go2 support for errors available as of 1.13 but also for previous version thanks to https://godoc.org/golang.org/x/xerrors.

In short, that gives: https://play.golang.org/p/cvjcAbE44YM which I think is great.

**Comment by nkcr** [comment]
.. and it is not possible anymore to use a simple concatenation with `+`.
I like it, here is my previous example adapted: https://play.golang.org/p/dREBDJIEF87

**Comment by ineiti** [comment]
I get my stack-trace, so I'm happy!

**Comment by Gilthoniel** [comment]
If @jeffallen agrees, I guess we can move forward with this issue by replacing our errors (and wrap the ones coming from external packages) with this package and stick to that.

**Comment by ineiti** [comment]
Done
