### ISSUE TITLE
network.Roster.fromTOML doesn't take Url field into account

### ISSUE THREAD

**Issue by nkcr** [dedis/cothority#2104]
I found out that the `network.Roster.fromTOML` function always tries to connect to secure web socket, even if the `Url` field is not set or set to `http://...`.

**How to reproduce**

1) Launch some conodes locally (`./run_nodes.sh`)
2) Set up and use `external/js/cothority/index.html` (run `npm run bundle` before)
3) Try to load the generated `public.toml` file from the step 1, which won't work.

**Comment by Gilthoniel** [comment]
So the issue is that `window.isSecureContext` is true when the content is delivered locally...
