### ISSUE TITLE
SDA - External communication API

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#211]
For now, we've focused mainly on the internal API : 
* How to form a tree
* Run a protocol on top of it
* Can run many nodes for one host on one server
* Everything related to SDA *inside* the tree

But we **deeply** lack of external communication means:
* Configuration when launching a ProtocolInstance (instead of a fixed registered method)
* Longterm listening for external connections -> Client want to timestamps a message. There should be a way to contact the Timestamp protocol at any time, not just when an instance exists at that exact time.

The lasts two points are starting to appears as we move towards the protocol's simulation-development phase, where we must do special tricks to give some informations to the root (creating the node first, then cast to the right protocol instance and then, for example, give the message,i.e. check the *protocols/***/simulation.go*).

With Linus, we discussed a bit about the future of SDA, and we agreed that a kind of a client / daemon interface could be worth trying. A SDA Host would run into the background and one would send him commands via a Command Line Interface. Here it **should** be possible to give some external configurations when starting a new protocol instance. But at the present moment, looking at the SDA structure, it is not clear how to achieve that since the ProtocolInstance "factory" is only a registered method with as only argument a ```*sda.Node```.

One idea that come to mind trying to solve this problem is to have another layer of abstraction simply called ```Protocol```. A ```Protocol``` is a structure that would be the interface between the internal sda states and the external world.
Its main responsability would be to receive the commands from the CLI. Imagine something like:
+ ```sda cosi start --rounds 10 *config.txt*```  where *config.txt* would contains the EntityList + Tree.
+  ```sda cosi start --infinite```
+ ```sda bizcoin listen``` would make the ```Protocol```listen for miners transactions and would dispatch them to the current running BizCoin ProtocolInstance.
+ ```sda bizcoin send *transaction.txt*``` would send the transaction to the ```Protocol```.

Its other responsability as you might have found is to create + launch new ProtocolInstance (kinda a java Factory).

Every ```Protocol```  has a ```Setup()``` method that does what it wants to do, and is called either at the *beginning* of the ```sda.Host``` life, i.e. at startup time, or *via* the CLI as defined above. 
It also have a ```Create(protocolInstanceType)```method that instantiate a ProtocolInstance and returns it (much less ***static*** since it can already have read a config from elsewhere).
Of course, there are still some issues though. One amongst others is that we provide the ability to run many ```sda.Node``` in the same ```sda.Tree``` within the same "protocol round". We would have to select which ```sda.Node```we want to contact (but this problem is present whatever solutions we might come up with).

 However, I think this ```Protocol```could solve the two problems above:
* It can read a configuration file / web page / usb-device, whatever, when it is called and anytime after that (if it wants to regularly check the configuration file every 5mn, it launches its own go-routine)
* It can open an external longterm port for easy communication with external world. Why not only CLI ? Because it's very restricting. A Client would not necessarily be on the same machine to give its *transaction* with the CLI. For **example**, a Protocol could setup a simple webserver serving a JSON-API so *everyone* can request its transaction to be signed, and there's no need to learn Go + Protobuf + SDA to use BizCoin.

**ADDITION** : 
* Moreover, the ```Protocol``` can controls the creation of ProtocolInstance. For example, we would not want a malicious guy to start a NewCoSiProtocol with 66% of the node he controls and the rest is choosen randomly (or not). There can be many possible scenarios, but the ability to say "yes" or "no, I don't want to be part of this" is for me an **absolute** feature to have. 
* Another useful feature that comes from this design, we can pass around informations from ProtocolInstance to ProtocolInstance. For example, ByzCoin needs the "LastBlock" hash, i.e. the last block signed by this "server", the last ProtocolInstance.

Again, this is simply an idea and it might just be completely a dead end, but I thought I'd share it with you guys since these questions will arise pretty soon.

**EDIT**:
As we are coding the simulation for BitCoSi / ByzCoin, we are feeling too constrained by the simulation framework in the sense that we can have control over the children nodes in the Tree. We only control the root. For example, having timeout occuring on the children if the root is malicious / failing, we had to include directly the measurement into the protocol and that's not something we want to continue on, because of the dependency issue. A protocol should not have to monitor itself if it doesn't want.

**Comment by ineiti** [comment]
Old comment about new `service` interface. Mostly done.
