### ISSUE TITLE
ByzCoin failure

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2118]
As of 28th of October 2019, ByzCoin is in a state where it cannot continue.

Block #21511 has a forward-link to block #21512, but this latest block is not stored in any of the nodes. Thus the chain cannot go forward.

Most probably this is linked to #2079 and #2080, with a probably addition of the leader sending out the forward-link, but not the block. Which is strange, to say the least.

At least three possible next steps:
1. reset the chain
2. automatically remove dangling forward-links when restarting the nodes
3. add `bcadmin debug resetBlock` which removes the forward-link

My take on this:
1. please not ;) C4DT already has quite a lot of users, and the underlying error has not been fixed yet, so this will not really help
2. I don't like the idea of the nodes automatically removing forward-links
3. Sounds good to me

**Comment by Gilthoniel** [comment]
Could this and related issues be fixed by allowing the leader to override the very last block. Or in other words, the very end of the forward link chain ? Then the children only allow the override to happen if they have the forward link but no block.

**Comment by ineiti** [comment]
That would be a

4. Leader can override dangling forward-links

to which I'd say

4. same as 2. - this is a bug and shouldn't be fixed with something more complicated and automated

**Comment by Gilthoniel** [comment]
Hm yeah the leader at least should have the block which is weird for today's issue but still, if something wrong happens when propagating the block after the forward link has been created, like the leader crashes, we would still need to remove the dangling forward link because the view change couldn't end I presume.

**Comment by ineiti** [comment]
In #2080 there is a proposition how to fix that so that it should not happen anymore...
