### ISSUE TITLE
@dedis/cothority@dev deps on out-of-scope ../kyber via personhood/ring-sig.ts

### ISSUE THREAD

**Issue by tharvik** [dedis/cothority#2124]
@dedis/cothority@dev is **broken**: a dep on kyber in cothority:personhood/ring-sig.ts got resolved to a relative path outside of project dir. I don't know why, my guess goes to the `npm run link` in travis.

**Comment by Gilthoniel** [comment]
So for the context: `export declare const ed25519: import("../../../kyber/dist/curve/edwards25519/curve").default;`
