### ISSUE TITLE
calypso: clients must verify the content of DecryptKeyReply

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#2136]
If a dishonest server that leads a reencryption protocol puts garbage into the DecryptKeyReply.C it returns, the client will fail to recover the original data that the write put in to care of Calypso. If the client is using the data like a symmetric key, and the symmetric cipher is an AEAD, then they can at lest detect it. If not, they will get garbage.

The client cannot tell if the original write was corrupt, or if the renencryption was dishonest.

The client must re-do the rencryption of Write.C using DecryptKeyReply.XHatEnc and check that it is the same as Write.U (U == X * XhatEnc + C).

**Comment by nkcr** [comment]
After talking with @LefKok it comes out that re-doing the reencryption is not trivial and can not be simply done as described above.

In the current situation the client has already the possibility to check the correctness of a re-encryption and the possibility to eventually get a correct one:

- If the client stores a symmetric key as the secret, he should then use an AEAD cipher. That gives him the ability to detect a wrong re-encryption
- If the client detects a wrong re-ecnryption, he can then choose another node to talk to. He will retry at most f+1 times before having a correct re-encryption.
