### ISSUE TITLE
SDA - TreeMarshal can be slow

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#214]
Currently, when we want to pass a Tree into the network, we transform the Tree into a TreeMarshal and then we pass the TreeMarshal. On the receiving end, the TreeMarshal is unmarshalled into a Tree using the EntityList associated. The way it does this is to search each EntityId of the tree into the EntityList one-by-one ... O(n). We can reduce to O(1) using a map of map[id] => Entity.

**Comment by ineiti** [comment]
Can you do a Benchmark to show how slow it is?

**Comment by evanv03** [comment]
I did the Benchmarks and the problem is not in the `MakeTree` but it is in the `Protobuf.decode`

**Comment by nikkolasg** [comment]
Then we close the issue.
