### ISSUE TITLE
SDA: Timeouts should be configurable

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#215]
We use all sorts of timeouts in sda. Currently, they are hardcoded either in global vars or (even worse) scattered around the code. Where it makes sense these timeouts should be configurable (otherwise students will have to change core-code in order to run experiments which take longer as the hard-coded timeouts allow).

**Comment by ineiti** [comment]
Do you remember what timeouts still need to be changed? I remember we got rid of a lot of them some time ago.

**Comment by Liamsi** [comment]
> Do you remember what timeouts still need to be changed? I remember we got rid of a lot of them some time ago.

There were quite a few. We deleted some during the byzcoin sprint (basically the ones that we had to change to run the simulations). I'm sure there are still some present. But for me it's OK to close this one and see if all problems are solved.
