### ISSUE TITLE
Implementation used to evaluate Omniledger?

### ISSUE THREAD

**Issue by devos50** [dedis/cothority#2178]
We can across the [Omniledger paper](https://eprint.iacr.org/2017/406.pdf) and would like to reproduce the experimental results. To do so, we would like to use the original implementation as used in the paper. However, I'm unable to find the Omniledger implementation with sharding.

I noticed that [there is a PR that adds support for Omniledger sharding](https://github.com/dedis/cothority/pull/1674), but I'm not sure if that is the implementation used in the paper? There also is some [student code](https://github.com/dedis/student_18_byzcoin) apparently?

Any pointers to the implementation used would be appreciated!

**Comment by ineiti** [comment]
Hi @devos50,

Thanks for your interest in OmniLedger. Here is what I can tell you:
- student_18_omniledger - student project to implement OmniLedger sharding in byzcoin
- dedis/cothority#omniledger_sharding - same student project, trying to get into master
- ??? (looking for it) - code used to evaluate the performance

The code used to evaluate the performance in the paper is very bare-bones and only tailored to evaluate the potential, theoretical maximum performance. For example, in the evaluation, the transaction-mechanism is only simulated, but no real transactions take place.

Once the paper was out, we started implementing parts of the ByzCoin protocol including a transaction mechanism that borrowed heavily from Ethereum - in the meantime we even added an EVM layer to our byzcoin implementation.

The student_18_omniledger project started implementing the sharding mechanism, but unfortunately it didn't find its way into `master`, where usable code resides. We're still waiting for somebody to finish that part ;)

We do have a running testnet for byzcoin here: https://status.dedis.ch and start using it for real-life usage: https://www.c4dt.org/article/dynacred/ - please be aware that the 'OmniLedger' in those posts refers to our `byzcoin` implementation here: https://github.com/dedis/cothority/tree/master/byzcoin 

For now the implementation of a sharded version of byzcoin is not very high on our priority list. We're kind of waiting for the transactions to reach the limit, which is currently around 20tps in our testnet. Once we're getting close to that one, we'll start updating the priorities ;)

As soon as I have found the code for the evaluations I'll ping you,

Linus Gasser

**Comment by devos50** [comment]
@ineiti thanks for your extensive response! Looking forward to an implementation 👍

**Comment by ineiti** [comment]
OK - according to @LefKok , the following branch should contain the simulations of the OmniLedger paper: https://github.com/dedis/cothority/tree/lbyzcoin/services/byzcoin_ng

As I said before: the simulations are _simulations_ ;) With a lots of nuts and bolts missing.

Here goes my favorite joke for PhD / engineering:

```
Question: How long does it take for an engineer to implement a PhD's

time.sleep(166 * time.Millisecond)

???

Answer: About one year, because that was the implementation for the paper of the transaction, global state, smart-contract, access-control, ... 
```
