### ISSUE TITLE
lib/crypto: need tests

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#218]
Wrote a small subpackage crypto library (instead of everywhere writing our own SchnorrSig + SchnorrVerify). Did not wrote tests for the moments and stg might fail.

**Comment by ineiti** [comment]
Why not putting this into `dedis/crypto`?

**Comment by Liamsi** [comment]
I added a test in the branch https://github.com/dedis/cothority/tree/test_schnorr which fails.

**Comment by Liamsi** [comment]
> Why not putting this into dedis/crypto?
Now, as this works correctly we could open a PR in dedis/crypto. But maybe the coe as it is, isn't general enough?

**Comment by Liamsi** [comment]
Closed: merged in #232
