### ISSUE TITLE
Link Bevm with ByzCoin

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2187]
Implement something like:
https://cryptpad.c4dt.org/pad/#/2/pad/view/hcUYF0pKjY8fmcxBwjqNnHvmAAGdCmACn6fZfsdT2CA/

Proposed workflow:
- [x] Convert BEVM-Events to Instructions dedis/cothority#2201
- [x] Add `bevm_state` as darc-identity dedis/cothority#2202

**Comment by cgrigis** [comment]
Closes c4dt/byzcoin#7.
