### ISSUE TITLE
Add bevm as darc attr expression evaluator

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2202]
To use BEVM contracts in darcs, add a `bevm_state` identity that takes a contractID and a method. The method is a view-method with the parameters `skipblock_index` and `signature`. The `signature` is passed from the `ClientTransaction.Instructions[x].Signature[y]` where x is the corresponding instruction and y is the corresponding darc-identity.

Use-case:
- allow only update of a valueInstance between 8am and 5pm CEST.

Sub-tasks:
- [x] Pass ByzCoin timestamp to EVM
  - [x] For an EVM transaction, timestamp of the ByzCoin block currently being created
  - [x] For an EVM view method, timestamp of latest ByzCoin block OR current time on the executing machine
- [x] Implement `bevm` attribute expression evaluator

**Comment by cgrigis** [comment]
Diving back into the work that @kc1212 did, my understanding is that I could use the `attr:` mechanism with an appropriate expression evaluator to achieve this. This would not require to add a new identity. It would look something like:
```
darc rule → invoke:config.update = <identity> & attr:bevm:<bevm_id>:<contract_address>:<method>
```
which would mean that the `invoke` is allowed if signed by the correct identity and the execution of the BEvm method returns `true`.
The call to the BEvm, implemented in the `bevm` expression evaluator, would be performed on the given `bevm_id`, the given EVM contract address, the given method name and passed arguments such as `skipblock_index` and instruction signature. We could also pass the instruction arguments.

Does that make sense or am I missing something?

**Comment by ineiti** [comment]
Two questions:
- would that also work stand-alone, like:
```
darc rule →
    invoke:config.update = attr:bevm:<bevm_id>:<contract_address>:<method>
```
- do you need two signatures to fulfil your proposed darc?

**Comment by cgrigis** [comment]
From the test https://github.com/dedis/cothority/blob/master/byzcoin/contracts/attr_test.go#L311-L390, it seems:

>     * do you need two signatures to fulfil your proposed darc?

No, only one for the identity.

>     * would that also work stand-alone, like:
> 
> 
> ```
> darc rule →
>     invoke:config.update = attr:bevm:<bevm_id>:<contract_address>:<method>
> ```

No, because in this case there would be no signature at all which is rejected by `Instruction.VerifyWithOption()`.

**Comment by ineiti** [comment]
Hmm - I would like the bevm-method to be a "full" identity then, so that you can give a signature with it, even if the signature only contains additional data.

Except if this would make it much more difficult...

**Comment by cgrigis** [comment]
After some more discussion, we agreed to go forward with the `attr` expression evaluator, with the idea that extra information such as a signature can be passed through instruction arguments.
To that effect, arguments shall be added to the `delete` instruction structure (currently only `spawn` and `invoke` have arguments).
