### ISSUE TITLE
Get SDA to pass Travis

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#224]
Before we merge SDA with development, travis has to be passed, again.

**Comment by ineiti** [comment]
There is an issue with regard to network-connections. It seems that even between different test-runs, not all go-routines are quit correctly and thus block opened ports that already have been closed.

**Comment by Liamsi** [comment]
We are almost there. As for now only tests in `protocols` fail.

**Comment by Liamsi** [comment]
done on sda_1 branch #151
