### ISSUE TITLE
A rookie‘s question

### ISSUE THREAD

**Issue by a1424360017** [dedis/cothority#2250]
I am learning your project and confronting some questions at the beginning,
1、Could I use windows10 to run your project ?  or i must use linux ro something else.
2、which part should I learn first?
I would be gratetful if you can give me some advise.

**Comment by ineiti** [comment]
1. I think it runs on Windows 10, but it's not a supported platform
2. Depends on what you want to do
  - run a byzcoin-node -> https://github.com/c4dt/byzcoin
  - implement a new protocol -> https://github.com/dedis/cothority_template

**Comment by a1424360017** [comment]
I just want to run a conode program on my computer(do not need to connect to web) ，could i use windows10?

**Comment by ineiti** [comment]
That should work - what do you want your conode to do?
