### ISSUE TITLE
Problem in scmgr

### ISSUE THREAD

**Issue by a1424360017** [dedis/cothority#2251]
When I run command "scmgr follow add single SKIPCHAIN_ID 127.0.0.1:7004" or "scmgr skipchain block add -roster public.toml SKIPCHAIN_ID" of the README , I always confront "Error while sending closing type: websocket: close sent" or " couldn't add this block as chain-follower: sending: connection read: websocket: close 1002 (protocol error): unexpected error: processing error: wrong signature of unknown signer" ,Could you please tell me what should I do or which part I have done is wrong.

**Comment by ineiti** [comment]
That's actually a bug ;) Fixed in #2252 - either wait for it to get in, or check out the corresponding branch and try again.

Thanks for the report.
