### ISSUE TITLE
latest @dedis/cothority complains about missing tslib

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2336]
According to @nkcr , if he tries to update https://github.com/dedis/columbus-united to the latest @dedis/cothority, it complains about a missing `tslib`. Steps to reproduce:

```
git clone https://github.com/dedis/columbus-united
cd columbus-united
npm ci
npm i @dedis/cothority
mv src/roster.ts.template src/roster.ts
npm run bundle
```

At least on my machine it doesn't complain about a missing `tslib`, but about a missing `@dedis/cothority/network/connection` file. The correct path is the `index.ts`, which is at `@dedis/cothority/network`:

```
find . -name "*.ts" | xargs perl -pi -e "s:network/connection:network:"
```

**Comment by nkcr** [comment]
The fix, works thanks.
That is due to @ineiti moving the `dedis/cothority/network/connection` file.
