### ISSUE TITLE
SDA - Handlers with 2 arguments: TreeNode + Msg

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#239]
Could be nice to have only to define the function and the message we use in SDA. 
Something like:
`func handleAnnouncement(node *sda.TreeNode, msg Announcement) { ... }`

So there would be no need to define wrapper structure to contains the TreeNode.

**Comment by ineiti** [comment]
Thinking about it I prefer #189. With #239 we have two slices that we have to search through, whereas with #189 there is only one slice and each element contains everything we need.

**Comment by ineiti** [comment]
Not relevant anymore.
