### ISSUE TITLE
Add github-action to replace Jenkins

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2395]
As the Jenkins-instance at DEDIS will be shut down somewhere in November 2020, I propose to add a github-action that runs _all_ go-tests according to the following schedule:

- Monday 8am
- Monday-Friday 8am 1pm IF code changed on that day

I think that's a good compromise in having the code run regularly without overflowing the github-action servers

**Comment by nkcr** [comment]
I would do 6am instead of 8am. So you can start your day with either a good news, or a session of debugging :P

**Comment by ineiti** [comment]
I know some people (won't name them) for whom even 8am is too early ;)
