### ISSUE TITLE
localhost - machines & hpn

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#24]
How should the ```machines``` entry and the ```hpn``` entry behave in the ```localhost``` platform? Personally I would like it to spawn ```machines * hpn``` processes. For the moment it spawns ```machines``` processes only.

**Comment by nikkolasg** [comment]
I did that so I could use my home-made createTree function instead of his. When specifying hpn = 1, it did not work with his function. We'd have to go through that to be able to go with ```machines * hpn```

**Comment by ineiti** [comment]
I think that’s because of him coloring the tree and trying to put each process on a different machine, no?

Anyway, can’t you tell your home-made tree function to do a tree for « machines * hpn » nodes?
