### ISSUE TITLE
js/byzcoin - use getLatestBlock from a proxy node ..?

### ISSUE THREAD

**Issue by nkcr** [dedis/cothority#2409]
Actually it is not possible for a foreign node (like a proxy one) to use `getLatestBlock`, because of this check:
https://github.com/dedis/cothority/blob/master/external/js/cothority/src/skipchain/skipchain-rpc.ts#L189

Why so ? Is it necessary ?

**Comment by ineiti** [comment]
Yes, it's necessary in a normal node, to make sure it's not replying with an outdated block... But I think there could be a flag that could be set by the `proxy` command of `byzcoin`... Can you please open an issue in c4dt/byzcoin for that?

**Comment by ineiti** [comment]
Sorry, read too fast. That's in fact the cothority-ts part... One simple fix would be to use the `verify` argument to `getLatestBlock` and if it's true, ignore if it comes from a wrong node. Would that be a good solution?

**Comment by nkcr** [comment]
That's better but not ideal. Can't we add a new optional argument ?

**Comment by ineiti** [comment]
Also possible, but sometimes there are too many arguments ;) Also, I hesitate between:
- having an argument in `getLatestBlock` - all callers to this method need to be aware what's happening
- use a field in the `SkipchainRPC` class - it can be setup during the configuration and then the methods can be used as usual

What is your preference?

**Comment by nkcr** [comment]
I would prefer the first option of having an argument, but only in the case we don't need this kind of parameter in more than like 2-3 places in the class. Otherwise having a field seems better.
