### ISSUE TITLE
List of nodes on a tree

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#249]
Currently when  a protocols needs to operate without the tree structure, it calls ListNode() which is basically a DFS look up on the tree.
One optimization that sda could benefit is to have the tree as an array of TreeNode.
In this array, each TreeNode would have indexes for its parent & children pointing to elements of this array.  Exactly like some implementations of *heap* data structures.
Benefits:
 *  Tree structure is preserved
 *  the use of all the nodes as a list is *direct*
 * Length of the tree is constant operation

This is *only* an optimization ;)

**Comment by ineiti** [comment]
Is this related to #214?

**Comment by nikkolasg** [comment]
No, #214 is related to how to map a `TreeNode` to its `Entity`. Here I'm only talking about the *construction* of the whole `Tree`. Both optimizations can be made in parallel.

**Comment by Liamsi** [comment]
Done in #345
