### ISSUE TITLE
implementations of Randhound protocol

### ISSUE THREAD

**Issue by kase113** [dedis/cothority#2493]
excuse me! Can anyone give me a pointer on the implementation of the RandHound protocol for sharding? In fact, I had cried to run code of RandHound in cothorityv2，but it missing many library function, as cothority/log, and other. So I want to know how to run it, It will be better if there is a simulation.
Thank!

**Comment by ineiti** [comment]
Thanks for your interest in randhound. The repository of the DEDIS organization was here:

https://github.com/dedis/pulsar.dedis.ch

But as mentioned there, the protocol has now been moved to https://github.com/drand

**Comment by kase113** [comment]
@ineiti 
thank you very much for your answer! 
I have researched in RandHound and code of omniledger， but I have some questions about RandHound and omniledger:
1. I don't seem to see the implementation of VRF in the code of omniledger and its library, can you give me a pointer on the implementation of the VRF? 
2. why do you use secret share in RandHound? In order to Ensure that it will not be attacked by malicious nodes, or Ensure the safety of public randomness, or other? 
I would appreciate it if you could answer! I hope it won't bother you.

**Comment by ineiti** [comment]
1. We never implemented the VRF for this part within cothority
2. I think that's explained in the paper: you need to have a secret commit that can be revealed by a threshold of nodes, to avoid that one of the nodes influences the result at the end.

**Comment by kase113** [comment]
Excuse me! Do you have implemented the code which swaps in new validators to each shard per epoch?

**Comment by ineiti** [comment]
A student started the implementation here: https://github.com/dedis/cothority/tree/omniledger_sharding - but it never got merged to the main branch.
