### ISSUE TITLE
Localhost-wait

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#25]
It doesn't wait for the end of the experiment before quitting to the command line...

**Comment by Liamsi** [comment]
I wanted to try the localhost simulation and stumbled upon this issue, too. The monitor only starts (and returns a valid ResultSet) in  case the app is run in "deterlab mode", but RunTest() returns before the end of the experiments in case it got empty/invalid ResultSet.  
I'll open a PR. Feel free to merge or ignore it, if you have other or better plans.

**Comment by ineiti** [comment]
The long-term fix is to enable monitoring localhost, too. But that is further down the path...  So I'll just merge this one. Thanks!

**Comment by bford** [comment]
Thanks for jumping right in, Ismail, and welcome to the team!

**Comment by Liamsi** [comment]
Thanks for the warm welcome, Bryan. Can't wait for December :-)
And thanks for merging, Linus!
