### ISSUE TITLE
Elections might not be finalizable

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#2511]
During the weekend I had the following thought: what if the condition you removed is about showing elections where the admin is not part of the election? Currently we always had test elections, where the admin was part, so it showed up twice. But what about an election where the admin is not part of the voters? Wouldn’t it be missing in the “Your elections”, and then it couldn’t be finalised? So perhaps the condition needs to be updated:

- if admin && admin is not part of election then show in “Finalised Elections”

Can you check if I got that right? And if I did, can you please update the code accordingly?

**Comment by PascalinDe** [comment]
I tested it on elections where I was not part of the candidates, if that's what you mean?

**Comment by PascalinDe** [comment]
I'll go check

**Comment by ineiti** [comment]
It's not the candidates, but if you're part of the admins or voters.

**Comment by PascalinDe** [comment]
Yes, I re-read the comment, at least in the code there does not seem to be a filter on whether one is part of the voters.

In any case, it wouldn't make much sense if an admin couldn't see all elections. I'll test on an example to make sure.

**Comment by PascalinDe** [comment]
![Screenshot 2023-07-03 at 09-02-59 evoting](https://github.com/dedis/cothority/assets/15922677/b7f8d73a-6104-4841-90bd-f6ac5e01c6ef)

only one voter (and one candidate! :rofl: ), and I'm *not* part of the voters

if we are looking for things to improve, I have access to the voting view, and can try to cast a ballot (which is rejected in the backend though)

**Comment by ineiti** [comment]
Great - thanks for checking that. So we're good. I wouldn't change too much at this stage. Let's wait what Pierluca says with regards to giving a hand on the D-voting project.
