### ISSUE TITLE
Some simulations don't continue to run

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#254]
For some obscure reason some simulations don't run more than 5 rounds - is it a node failing?

For example

`go build && ./simul -platform deterlab -range 7: runfiles/Paper_cosi2/naive_cosi.toml`

in the `redo_cosi_graphs`-branch doesn't work when there are more than 6 rounds !?!

**Comment by ineiti** [comment]
Probably due to a node that is not responding. Should be caught in a timeout and restarted.

**Comment by ineiti** [comment]
Adding a function with a handler in `lib/simulation` where a round can be started and will be timeouted.

**Comment by nikkolasg** [comment]
Is it still a current problem ?

**Comment by nikkolasg** [comment]
I'm not sure this issue is still relevant as we have timeout now and such. @ineiti can you confirm ?

**Comment by ineiti** [comment]
Probably _is_ relevant, but difficult to reproduce. Closing.
