### ISSUE TITLE
Accept but warn if not enough servers are present

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#267]
If deployed to Deterlab (and MiniNet), accept if the `Server =` in the `.toml`-file is lower than the actual server-count, but print out a warning.

**Comment by nikkolasg** [comment]
I don't understand you want a warning when
1) There's not enough servers in deterlab regarding the number put in the config toml file 
OR
2) there's more servers in deterlab available than what's required from the config toml file

**Comment by ineiti** [comment]
in fact this is done.
