### ISSUE TITLE
Get your code documented

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#275]
For new code: run the [lint.sh](https://github.com/dedis/cothority/blob/development/lint.sh) manually (or use a plugin that does that, or even runs golint in your favourite -and of course best- editor). 

For existing code: run the lint.sh script manually and see the enormous output of exported yet uncommented functions, structs etc. Pick what sounds very familiar to you and please write a comment that makes sense even to someone who doesn't sit here in the office and just browses the using his/her favourite editor (`git blame` and the github API will help to automate this if no progress is made).

**Comment by ineiti** [comment]
Lazy writer: any link on how to set up lint in IntelliJ?

**Comment by Liamsi** [comment]
> Lazy writer: any link on how to set up lint in IntelliJ?

I think Intellij's go plugin comes with the linter (partly) incorporated somehow (go-java bindings?) 
See `Inspections` in Settings. Not sure if checks for uncommented code though.

**Comment by Liamsi** [comment]
Looks like they actually rewrote parts of the linter in java: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/e819044f04cf3d1d0ff32ce6c05987ade91c7d85/src/com/goide/inspections/GoCommentStartInspection.java

**Comment by Liamsi** [comment]
Linter enabled in development ( see #302 )
