### ISSUE TITLE
Prototype signing-application

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#277]
Before writing the final network-interface to SDA, start with a simple signing-application according to what Bryan wrote:

# Creating a Collective Signing Group

Create a my-cosi-group.toml file that looks like this:

[template]

The template above lists two CoSi servers run by the DEDIS group at EPFL [and/or other volunteers such as Linus Nordbergd?] just as an example, but you can change this list to refer to any set of CoSi servers you like including your own (see below).  

# Initiating the Collective Signing Protocol

We have provided a simple manually-driven collective signing application, ‘bin/cosi’, which you can use to request the collective signing group you defined to witness and cosign any message you propose.  In this case the witnesses are not validating or checking the messages you’re proposing in any way; they are merely attesting the fact that they have observed your request to sign the message.

You can collectively sign a text message specified on the command line as follows:

$ cosi sign -m “Hello World” my-cosi-group.toml

If you would instead like to sign a message contained in a file you specify (which may be either text or arbitrary binary data), you can do this as follows:

$ cosi sign -f my-message-file my-cosi-group.toml

# Running your own CoSi server

First you need to create a configuration directory for the server, and create a config file for it including a public/private key pair for the server.  You can create a default server configuration with a fresh public/private key pair as follows:

$ mkdir my-server
$ cosid init my-server

Created fresh Ed25519 witness server key pair.  Use the following line to include this server in collective signing groups:
	Server = <hostname>:<portnumber>:1a0b90db901a09ddb091ab90ad90b3d47a

Then you should be able to cut-and-paste the line above into the server list part of the group config.toml file defining any collective signing group, to add this server to that witness cosigning group.

To run the server in daemon mode, just go into the my-server directory and run:

$ cosid

**Comment by Liamsi** [comment]
Just some TODOs for me tomorrow (so we won't end-up having the same functionality twice), sorted by priority:
- [ ] add clear and concise usage output 
- [ ] incorporate the above mentioned into the Readme/documentation
- [ ] probably refactor all the Read/Write functionality (group toml & cosid config into the utils package);  (might be optional for this issue) use the same encoding everywhere (at least for almost the same structs) 
- [ ] discuss and add verification mechanism (missing in the above document)

**Comment by Liamsi** [comment]
> The template above lists two CoSi servers run by the DEDIS group at EPFL

Should/could we revive the EPFL CoSi nodes? Or do you want to wait for that until we coded the SDA-services?

**Comment by ineiti** [comment]
As soon as this works, the EPFL CoSi-nodes will have to be started again. I'll also re-start my CoSi-node in Germany.

One thing I'm not sure is whether it's worth adding the update-mechanism.

**Comment by Liamsi** [comment]
> As soon as this works, the EPFL CoSi-nodes will have to be started again. I'll also re-start my CoSi-node in Germany.

OK, then leave the structure/content of the README like this:

> The template above lists two CoSi servers run by the DEDIS group at EPFL

And we keep this template empty until the servers are running again and change that before we merge it into master? (Otherwise I would prefer to rewrite it a little further)
