### ISSUE TITLE
Start() - infinite loop

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#278]
If =>
* you define a protocol without a `Start()` method,
* this protocol embeds the `*sda.Node` like most protocols do
Then when you call `node.Start()`, it will do an infinite loop because it calls recursively the `Start()` method of the node .

It's not usual to not have a `Start()` method but still it can happens, and it happened to me during my test phase.

**Comment by ineiti** [comment]
Either renaming the `node.Start` or the protocol-interface-`Start` is probably the best.

`node.Start` -> `node.StartProtocol`?

**Comment by nikkolasg** [comment]
+1

**Comment by Liamsi** [comment]
Fixed in #306
