### ISSUE TITLE
Exception-mechanism

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#286]
Re-implement a simple exception-mechanism. If one of the children times out, simply contact the leader which will start a new round.

Take care about the timeout-issue, as the root will have to wait longer than the children.

**Comment by ineiti** [comment]
https://github.com/dedis/cosi/issues/10

**Comment by nikkolasg** [comment]
This issue should be resuscitated in regard with  #680 . 
Moreover, we should aim for a *clear* definitions of what happens for all possible cases when something goes wrong.

**Comment by ineiti** [comment]
Please have a look if https://github.com/dedis/student_17_bftcosi is possible to be integrated in cothority.v2
