### ISSUE TITLE
RunConfig extension

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#291]
In simul.go, and other places, we do our custom retrieval of values out of the RunConfig.
We can simplify / extend / normalize the RunConfig struct.
Something in the order of:

```
// Returns the value of the field designated by `name` or the `default` value if the field does not exists.
func (rc *RunConfig) GetInt(name string, default int) int {
    ...
}

... 
rc.GetInt("runwait",100)
```

We should do that for `string`,`float` etc.

**Comment by ineiti** [comment]
Overengineering of a simple interface.
