### ISSUE TITLE
Entity / EntityList

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#294]
- As writing the cli with @Liamsi , he tought it could be nice to have some kind of description of a server when choosing the list of nodes you want your message to be signed by. 
  Something along the lines like:

```
type Entity struct {
    Addresses []string
    PublicKey abstract.Point
    Metadata string # i.e. "@ineiti's server running on PI"
}
```

So when people wants to create / choose a cothority, they know which IP addresses belongs to who / what organizations.
- This changes induces another one: Move `Entity` out of the `lib/network` and more into `lib/sda` itself. All the features we do implement using Entity should not be embedded in the network library as we wanted to keep it self-contained.

**Comment by ineiti** [comment]
Is called `ServerIdentity` / `Roster` now.
