### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by bford** [DeDiS/cothority#3]
Can we use somewhat more concise directory/package names, when they'll still be clear but save a bit of typing and screen space?  Suggestions:

application -> app
protocols -> proto
helpers -> lib?

**Comment by ineiti** [comment]
Le 16/09/2015 09:39, Bryan Ford a écrit :
> Can we use somewhat more concise directory/package names, when they'll
> still be clear but save a bit of typing and screen space? Suggestions:
>
> application -> app
> protocols -> proto
> helpers -> lib?

Will do on Thursday. Even though I do like names that say a bit more...

Linus

**Comment by ineiti** [comment]
Closed with branch 'rename_dirs'

PS: do you usually keep merged branches?

**Comment by bford** [comment]
You mean do I keep the branch tags for branches that have been merged and are no longer in use?  No, I don't see a need to do that; I'd prefer to delete such branch tags to reduce long-term clutter.  Do you have a preference?
