### ISSUE TITLE
Debug-flags

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#307]
How to handle the debug-flags? We have

- debug-level: 1 to 5
- color: true / false
- time-output: false / true

To do debug-level 1, no color, with time
1. `-debug 1,c,t`
2. `-debug 1 -debug-no-color -debug-time`
3. `-debug 1 -debug-color=false -debug-time=true`

Importance: very low - but how?

**Comment by Liamsi** [comment]
I like option 3 best. Would disable color by default (or even completely, as it doesn't work reliably). Also I would disable time by default (didn't have a chance to have look on it)

**Comment by Liamsi** [comment]
Done in development
