### ISSUE TITLE
Hackish Cosi/CONIKS prototype

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#314]
- [x] re-read the paper (might be not necessary)
- [x] [clone](https://github.com/dedis/coniks-ref-implementation) repo of reference implementation
- [x] read the code and locate locate the parts where it makes sense to collectively sign
- [x] use standalone CoSi instead of a single signature (should be a few sloc)

**Comment by Liamsi** [comment]
Code can be found here: https://github.com/dedis/coniks-ref-implementation/tree/cosi_coniks

**Comment by ineiti** [comment]
So is this to be closed?

**Comment by Liamsi** [comment]
Yes
