### ISSUE TITLE
Debug-checks

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#317]
Change all tests to include something like:

```
func TestMain(m *testing.M) {
        flag.Parse()
        dbg.TestOutput(t.Verbose(), 4)
    code := m.Run()
    dbg.AfterTest(nil)
    os.Exit(code)
}
```

Also change `dbg.TestOutput` to fetch directly the `t.Verbose()`-flag instead of passing it. And move that function towards the end of `debug_lvl.go`.

PS: I'm sure this is a duplicate, but I can't find the original...

**Comment by Liamsi** [comment]
Here is the original : #229

**Comment by nikkolasg** [comment]
Is it not already fixed in master this behavior ?

**Comment by ineiti** [comment]
not for all tests, as far as I know.

**Comment by ineiti** [comment]
Mainly done.
