### ISSUE TITLE
Cosid running out of memory

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#334]
Still don't know what happens, but sometimes the cosid run out of memory!

**Comment by Liamsi** [comment]
One potential memory problem could result from from the `tempCommitment` and `tempResponse`  arrays. First step could be to output the `len` for debugging.

**Comment by Liamsi** [comment]
I'll see, if I can reproduce it locally or find the problem source (without reproducing it)

**Comment by Liamsi** [comment]
This doesn't seem to happen with the lastet cosi release -> closed
