### ISSUE TITLE
dbg.PrintIfErr(msg string, err error)

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#349]
Add a function to the debug library. See discussion starting here: https://github.com/dedis/cothority/pull/347#issuecomment-207359975

**Comment by Liamsi** [comment]
This is just a slight enhancement. But could also be a refactoring (use the function everywhere we just print out the error messages).

**Comment by ineiti** [comment]
Find better name

**Comment by ineiti** [comment]
not really used. Was:

replace
```
if err != nil{
  log.Error(err)
}
```

with

```
log.PrintIfError(err)
```
