### ISSUE TITLE
Rename Entity/EntityList

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#363]
Now:
`Entity` - represents a cothority-daemon with its public key and address
`EntityList` - list of Entities to be used in a tree where each Entity can only be once
`TreeNode` - structure that is doubly-linked to parents and children
`Tree` - structure of `EntityList` and the root-`TreeNode`

After:
`ServerIdentity` - replaces `Entity`
`Roster` - holds all elements of the tree. If a `ServerIdentity` wants to appear more than once in the tree, it needs to be listed more than once here
`TreeNode` - has an index to the `Roster` for its parent and Children. Also contains a pointer to the `Tree`.
`Tree` - structure of `Roster` and slice of `TreeNode`s.

**Comment by ineiti** [comment]
Keep this as rename-only-issue. Also rename the following:
`sda.Data` -> `sda.ProtocolMsg`
`sda.ProtocolInstance.DispatchMsg` -> `sda.ProtocolInstance.ProcessProtocolMsg`
`sda.ServiceMsg` -> `sda.InterServiceMsg`
`sda.Service.ProcessServiceMsg` -> `sda.Service.ProcessInterServiceMsg`

And add in the documentation how to distinguish a protocol from InterServiceMsg:
- Protocols are re-usable multi-steps calculations with a beginning and an end
- InterServiceMsg change state of same services on different nodes

**Comment by ineiti** [comment]
What is a good name for `network.ProtocolMessage`?
`network.Message`
`network.InterfaceMessage`
`network.AnonymousMessage`

**Comment by nikkolasg** [comment]
Mhh. Or maybe we can rename `network.Message` to `network.Packet` ? 
Also possible to do stg like:  
```
type Payload interface{}
type Packet struct {
   From *Entity
   To *Entity
   Type PayloadType
   Msg Payload
}
```

**Comment by ineiti** [comment]
I like `network.Packet`, more for `network.ProtocolMessage`:
`network.Bulk`
`network.Body`
`network.Data`

**Comment by nikkolasg** [comment]
+1 for `network.Body`

**Comment by nikkolasg** [comment]
`sda.Data` is only use by the `Overlay -> TreeNodeInstance -> ProtocolInstance`, I suggest:
`sda.OverlayMessage`
`sda.ProtocolMessage // Not a big fan but still it's a possibility`
