### ISSUE TITLE
JVSS Tweaks

### ISSUE THREAD

**Issue by Daeinar** [dedis/cothority#369]
The following tweaks should probably be integrated into JVSS:
- Move `secretsDone`, `ltssInit` and `sigChan` out of the `JVSS` struct and into the `Secret` struct as `ready (chan bool)`, `done (bool)`, and `sig (chan *polySchnorrSig)`.  Already tried to realise that but ran into a bunch of data races and therefore removed it again because it's not very urgent.
- One way to support multiple signing requests could be to deep-copy the long-term Schnorr struct to the short-term shared secret and use that for the signing. Maybe there is another and better solution. I have to think about that later.

**Comment by Liamsi** [comment]
This also holds for timevault (at least the first bulletpoint)

**Comment by nikkolasg** [comment]
Non valid anymore.
