### ISSUE TITLE
Usability issues in standalone cosi/cothorityd

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#375]
There are a bunch of cosi-cli usability issues.
@nikkolasg started to work on the server part in the [usability branch](https://github.com/dedis/cothority/tree/usability).

I will work on the client part. After that we'll merge the `cosi` and the `cothorityd` into one binary. After testing we will move the code to a seperate cosi repo.

**Comment by Liamsi** [comment]
TODOs (mainly for myself) on the client:

- [ ] `cosi check` outputs some obscure error message (coming from codegangsta cli)
- [ ] `cosi sign -help` usage instructions are confusing (`-sig` option)/"The ‘sign’ and ‘verify’ commands should be consistent" & use stdin/stdout “by default”
- [ ] don't use the `dbg` library; or at least ditch the colors
- [ ] keep the std output clean of other output (if everything is fine, otherwise use std err) 
- [ ] rename -servers to ‘-group’ or ‘-def’ (group definition) 
- [ ] update README according to all points above

**Comment by ineiti** [comment]
You can keep the `dbg`-library for debug output, but then do
```
if ! flag("-v"){
    dbg.SetDebugVisible(0)
} else {
    dbg.SetDebugVisible(3)
}
dbg.SetUseColors(false)
```

**Comment by Liamsi** [comment]
If we add a `-v` flag as above the user still won't be able to use stdin/stdout with that flag turned on.

**Comment by ineiti** [comment]
which might be acceptable - using `-v` is for debugging purposes mainly. I'm trying to write a test for the `dbg`-library to have `dbg.Error` and others on stderr - but it feels quite awkward...

**Comment by Liamsi** [comment]
Found a new (minor) usability glitch. If you are running a server and type in the IP with IP non-reachable from outside. You'll see sth like:
```
[+] Enter the IP address you would like others cothority servers and client to contact you: 
[-] Invalid IP address given (%!!(MISSING)(EXTRA string=, string=))
```

**Comment by Liamsi** [comment]
I merged both applications (`cosi` and `cothirtyd`) into one binary. The `cothorityd` functionality is now available through `cosi server`. It needs more (human) testing though.

I also created a [cosi repo](https://github.com/dedis/cosi). I didn't put anything into it yet, as we first need to make sure that the packages the cosi app imports from the `cothority` (or later maybe only from `sda` or whatever it will be called will exist even if the code changes (by using https://gopkg.in for instance). 
We could also create such a package from the whole cothority repo right now (maybe using a low release number like `0.1`). At least I don't see anything stopping us from doing so now.

Any thoughts? /cc @bford @ineiti @nikkolasg @Daeinar

**Comment by nikkolasg** [comment]
Cool!! 
* One thing though is I think it'd be best to keep separated the cothoriyd / cosi apps in the  *cothority* repository because we still gonna need to develop this "*all features*" daemon cothorityd which does not only do CoSi but a lot of other stuff. It'd be weird to have our daemon called "cosi" ...
But for the CoSi repo, we definitely want that merged together.
* Regarding the packages thing, as Bryan suggested, I think the first order is to have a usable Cosi binary for IEEE; so all about usability.As you said, I don't think we're there yet.  Then, later, maybe even after IEEE, we can move on to the "code" part, having clean packages with versions etc. This latter part is kind of a big one since we want to extract out SDA at least, start normalizing our signature format, start thinking about backward compatibility,etc. It might take a while^^.
That's why I think it might best to go directly with *something* inside the CoSi repo, importing directly `cothority/lib/{sda,network,etc}` from the Cothority repo. Nevertheless, it's also possible to start now using gopkg and having something like `gopkg.in/cosi/v1` in our Cosi repo.

What do you think ?

**Comment by bford** [comment]
I agree that the cosi repo can be kept minimal for the moment, with almost all of the actual stuff it refers staying in the cothority repository for now, until we (later) can spend more time deciding code/repository structure issues.

The only thing the cosi repository *really* needs to have is a working README and an easily buildable/installable cosi binary. :)

Let's not try to make a gopkg.in/cosi/v1 just yet either, until we decide what the API for that should be.  gopkg is intended for stable Go library APIs, and it doesn't make sense to start using it until we have a Go source-level API we think is well-organized and stable enough.

**Comment by Liamsi** [comment]
>The only thing the cosi repository really needs to have is a working README and an easily buildable/installable cosi binary. :)

> Let's not try to make a gopkg.in/cosi/v1 just yet either, until we decide what the API for that should be. gopkg is intended for stable Go library APIs, and it doesn't make sense to start using it until we have a Go source-level API we think is well-organized and stable enough.

As I said [above](https://github.com/dedis/cothority/issues/375#issuecomment-219154652) I meant it the other way around: I thought about having a `gopkg.in/cothority/vX` instead of a `gopkg.in/cosi/vX`.
In order to have a minimalistic cosi repo which refers to a subset of the cothority repo, we still need to refer to this subset in a way which doesn't break the cosi repo if there are substantial changes in the cothority repo (and there sure will be #378 ;-). 
The simplest way would be to create a `gopkg.in/cothority/vX` packe only containing the dependencies necessary for cosi. But maybe what Bryan said about the "Go source-level API we think is well-organized and stable enough" also isn't the case for the moment. But than I don't see how-to create a single cosi repo soon, without breaking it regularly (by modifying the API of its dependencies).

Any suggestions?

/cc @nikkolasg @bford

**Comment by bford** [comment]
Ah, yes - indeed, creating a gopkg.in/cothority/vX and having the cosi binary use that makes more sense, and is pretty close to what I had in mind.  But let's do that as a next-step after getting the cosi binary and README polished up nicely in time for IEEE S&P.

**Comment by Liamsi** [comment]
Thanks for you feedback!
OK, then let't keep cosi inside the cothority repo until we really polished it.

Regrading you first comment @nikkolasg:
> One thing though is I think it'd be best to keep separated the cothoriyd / cosi apps in the cothority repository because we still gonna need to develop this "all features" daemon cothorityd which does not only do CoSi but a lot of other stuff. It'd be weird to have our daemon called "cosi" ... But for the CoSi repo, we definitely want that merged together.

Currently this should be the case for the `cosi` package/binary. All the functionality is now in the `app/cosi` package. I didn't delete the `app/cothority` package (yet)

**Comment by nikkolasg** [comment]
I meant inside the cothority *repository*, our `app/cosi` should only be the client side, not the server side, because we already have a `app/cothorityd` that we want to stick with. Otherwise we have the server code at two places.

**Comment by Liamsi** [comment]
This can be closed then, or not? @nikkolasg finally copied the code over to https://github.com/dedis/cosi and is doing the rest of the work there. Great!

I still vote for having a `gopkg.in/cothority/vX` as soon as possible (maybe directly after S&P) and importing this instead of directly from the master branch (which may change and break the cosi repo).
Greetings from Germany

**Comment by nikkolasg** [comment]
Yep, I'm closing it. 
@Liamsi totally, we need to structure our code and having a maintainable part and that's why @ineiti started this [google doc sheet](https://docs.google.com/document/d/1sJTRgyezQAcbPzqrSoMxmAoqlG_RW8Rtw7DGmYjl1L8l).

*Everything in its own time...*
