### ISSUE TITLE
SDA Refactoring

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#378]
**Idea**
Let's re-factor sda while it's not too big, the main things we want from this refactoring are:
- better external API for the package (don't put everything as exported)
- better unit testing ( and still keep the integration test )
- refactoring of the Roster / Tree structs, using an array
- mocking structure for faster testing (don't need to actually open a port )
  - having a Processor interface, which can be implemented by Overlay and Service so they use a unified interface to _receive_ messages
  - having a Router interface which can be used by Service and Overlay so they can use a unified interface to _send_ messages

These two interfaces would enable us to have much more flexibility in our processing of our message (centralization of processing, defining a third entity which receives messages (another Overlay?), mocking network etc)

**Additional**
**EDIT** This part is left for sake of history but will **not** be done in this issue.
 If you have anything you'd like to see implemented / refactored, please tell !
I have some ideas of my own but they're not at all needed right now:
- Having a general messaging system so there's no need to put go-routine everywhere where the code might be blocking, and can eventually leads to better performance (
- Start with a basic implementation of events publisher / subscriber thing, so anyone that is interested in some kind of events can register and having callbacks/handler react to these events when they occur. Such events can be "NewIncomingConnection", "NewOutgoingConnection", "ConnectionDropped" etc. [1] [2]
- Supporting different overlays, not only having a TreeOverlay but a HyperCubeOverlay and MeshOverlay or MatrixOverlay (n^2). [ definitely more a _cool thing_ than a _must-have_ :) ]

[0] http://marcio.io/2015/07/handling-1-million-requests-per-minute-with-golang/
[1] https://msdn.microsoft.com/en-us/library/ff649664.aspx
[2] https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern

**Comment by ineiti** [comment]
I'm hesitating whether it is a good idea to start from scratch - I'm still finding bugs in the 'services' implementation, even though we merged that some time ago already.

I would prefer the 'linux-kernel'-way where changes, even big ones, get merged progressively. Most of the things in the above list are OK and should go in sooner or later. But I don't think we get them in a reasonable time-frame working with everything we have and want to do.

My favorite list is:

- Renaming of structures
- Verifying all interfaces are used more than once, else convert them into structures
- Refactoring of the Roster / Tree structs, using an array
- Decide on public/private methods and finish a good API

**Comment by nikkolasg** [comment]
Mhh I see. I think I forgot to mention some other internal changes that'd be great to have like:
* Having a Processor interface, which can be implemented by Overlay and Service so they use a unified interface to *receive* messages
* Having a Router interface which can be used by Server and Overlay so they can use a unified interface to *send* messages
These two interfaces would enable us to have much more flexibility in our processing of our message (centralization of processing, defining a third entity which receives messages (another Overlay?), mocking network etc)

Regarding the rest:
1. The first 2 issues are very closely related:  If you want to have a better external API, that means you need to define a lot of methods / structs as unexported, that means your tests will become real units tests now.

2. The `mocking structure` brings *a lot of refactoring* since it means using interface instead of structs. That's the biggest change for me.

3. The refactoring of Roster / Tree can already be done now on its own.

Would that be OK to separate the *from_scratch* to these 5 different issues ?

>  I'm still finding bugs in the 'services' implementation, even though we merged that some time ago already.

Is it not a better reason to refactor it ? Having a *second iteration* on this subject ?

> Verifying all interfaces are used more than once, else convert them into structures

I don't get it, what interfaces are you talking about ?

**Comment by ineiti** [comment]
All points here are valid points and need to be addressed sooner or later. If I understand correctly, the only point we're not sure is whether to re**write** or re**factor** it. I'm all for re**factor**ing it in small pieces compared to re**writ**ing it and trying to _make it right this time (tm)_.

So my proposal is to split this issue up in smaller issues that can be handled one by one.

**Comment by nikkolasg** [comment]
Ok right. 
For almost all points mentioned, we can re**factor** it. However for the point `mocking structure for faster testing`, it will mostly be re**writing** but it can definitely be in its own separate issue.

**Comment by nikkolasg** [comment]
I'm starting to change my mind on this one. I agree to the general principle that starting from scratch is not a very good solution. Now let me explain why I think in this case, it'd still be the *best* solution:
* Considering the different changes as separate issues / PR, will force to make *every* PR make Travis happy. That will be a *huge* amount of time lost because from one PR to the other, things will change, maybe small details but the rest of the code will also have to adapt => protocols , services, applications... Doing that *once* makes a huge time difference
* We now have a *cosi* repository which we want it to be usable, cleanly coded (and fast optionally). Importing our big `lib/sda` was a quick hack and it did it but it sure ain't a proper way to do it, because sda *as-it-is* is WAY too big for Cosi, and way too big in itself => it contains stuff related to network, to tree, to API etc. I'm starting to think these features could be broken down as general coding guidelines tell us often... Recently when we added something to sda in the current state, we simply said "Yeah let's add a `if msg.Type == `, and let's launch the processing in a go-routine, it's fine because we need it fast". This reasoning was perfectly OK during our sprint coding session for papers acceptance but now that we are moving towards *real - usable coding*, I think we should change our mindset. We could start thinking about:
 + our actual code and how is its current state instead of our features that we lack 
 + how to *properly* integrate new features instead of integrate features *fast*
 + proper design pattern ! Our current design is starting to be very confusing with protocols, services etc.  We could start trying to think of a better solution from the ground up with the experience we learnt doing the code as our current state  There's lot of code we don't *need* to make it work anymore such as byzcoin. 
 + Define our *clients* / *targets* : for whom are we coding this library ? For phd students ? For external people ? For expert people ? In a lot of places in our code, we are deliberately *exporting* things because of tests, because *we need it*, but *we* is not our *client*. The *client* should only see what he is allowed to do and what he is supposed to do with our library, that does not mean *everything* as we are trying to do now. 

Now that we have time, we can maybe take the time to do proper coding. Again, all we done is not bad, not at all:
 + lot of current code could be used if we start from scratch, 
 + we learnt a lot by coding this, and I think we can think about our mistakes / success to do better.

Well, I've went too far in my reflection but this issue and this post comes from a general feeling that we are doing *too fast* and not *too good*. 

>I'm all for refactoring it in small pieces compared to rewriting it and trying to make it right this time (tm).

Do you think it takes more time to do  *it right this time* / *everything above* from scratch (re-using large parts of the code) than to do it separately, with each PR adding a little feature that needs to make travis happy ? I'm really not sure.

**Comment by ineiti** [comment]
Only stupid people don't change their minds. Now if the contrary is true, I don't know ;)

I propose we close this and open issues of what you want to refactor/rewrite and why.

**Comment by nikkolasg** [comment]
I'm not sure about the `Router` thing, we have to see how it turns out after having all the issues completed...

**Comment by ineiti** [comment]
Is this active for the moment? If not -> put it into `Next steps` or `Later`.
