### ISSUE TITLE
app/lib/oi vs lib/dbg

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#406]
In PR #400, there is this new `app/lib/oi` library that outputs / exit things in different format. One idea is to merge this one with our already existing `lib/dbg` library. We would need to set the format beforehand like : `dbg.SetFormat(dbg.PythonFormat)` or `dbg.SetFormat(DebugFormat)`. 
What do you think ?

**Comment by ineiti** [comment]
Now I added an `input`-function in `lib/ui`, so it's not really dbg anymore.

**Comment by nikkolasg** [comment]
I've checked and the input function of `ui/Input` is only used by the server. Moving that part into the server lib and merging the rest seems like we could save quite a lot of duplication code and having a general logging framework would be great instead of two differents.

**Comment by ineiti** [comment]
Will probably also be used by the cisc-app. And I prefer the separation of `debug` and `user-in-out`. It's not really the same.

**Comment by nikkolasg** [comment]
Well, our `lib/dbg` is not a *debug library*, it's a complete logging library, so `lib/ui` for the *output* part should be really be merged into `lib/dbg`; it does not make sense to have two different packages doing the same thing. We maybe rename the latter as `lib/log` or something.
As for the *input* part, well then if it is used somewhere else, then let's make a module out of that, that's no problem.

**Comment by ineiti** [comment]
Done in #440
