### ISSUE TITLE
Avoid code duplication between the cosi/cothority/crypto repositories

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#409]
- [x] app/cosi in cothority is (almost) the same as equivalent parts in the cosi repo
- [x] same for services/cosi, protocols/cosi
- [x] move lib/cosi to dedis/crypto

**Comment by nikkolasg** [comment]
For the last point:
PBFTCosi needs `dedis/cosi` and some features (exception mechanism) that are not yet implemented in `dedis/crypto/cosi` because it's not clear yet how to do it.  These additional features will have to be put into PBFTCosi for the moment.

**Comment by ineiti** [comment]
I think this can be closed with the last changes from Nicolas.
