### ISSUE TITLE
Improve Client structure and connection

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#414]

**Comment by Liamsi** [comment]
Not reusing the client object makes the test pass. But we actually want to have a test where we send from one client object in parallel. 
So the goal of this issue now is to write a test like `TestClient_Parallel` which actually reuses one client object (and sends requests in parallel)

**Comment by nikkolasg** [comment]
We added with @ineiti a `Lock` on the client `Send` method which is supposed to solve the problem but it does not. The *underlying* problem is we register connections in the `sda.Host` only by using `EntityID` which in the case of one `Client` asking two `Services` on the same `Host` will still make the whole thing failing.
Therefore, we may need to register a `SecureConn` using *more* than just a `Entity` but also the `RemoteAddr()` maybe or a unique ID we add to an Entity or .. what else ?

**Comment by ineiti** [comment]
The `Client` brings troubles if the same host wants to connect more than once, because then the connection-identity will be the same for all connections.

**Comment by nikkolasg** [comment]
This issue is not relevant anymore with the latests network stack refinements.
