### ISSUE TITLE
SDA Refactor - Unit test to reduce exported API

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#430]
In `lib/sda`, most of it is exported because we started writing our test using `package sda_test`, so as it were an *integration test* instead of *unit test*. We should move that to *unit test* since that's what the tests are mostly, and doing that it enables us to clean up the exported API by a huge factor :) 
The goal is *not* to reduce exported API, but it is mostly a consequence. Reducing exported API can be further done but that's a subject of future issue.

**Comment by Liamsi** [comment]
This is resolved in #484, right? Or is this a more general issue?

**Comment by Liamsi** [comment]
As discussed with @nikkolasg this can be closed.
