### ISSUE TITLE
Having development branch as the main one

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#433]
After having discussed with the whole team, we want to have our current development branch as the main branch. That means when people go on the github page they see the development branch and also when doing `git clone https://github.com/dedis/c{osi,rypto,othority}`.
One question remain, should we still let the name of the branch being  development or should we go for master ?
I tend to like the latter, as having a master is common everywhere, and it looks more serious :D

**Comment by Liamsi** [comment]
Just stick with master as everyone else. But actually it doesn't really matter.
