### ISSUE TITLE
Return Stats from servers

### ISSUE THREAD

**Issue by evanv03** [dedis/cothority#438]
We want to be able to retrieve some stats from the servers with regard to connections.
It can possibly be added later that services can add other stats

**Comment by ineiti** [comment]
Here is a TODO-list for the stats-service:
- [ ] Merge with new master and make a PR against `master`
- [ ] Return the IP:Ports of all cothorities this one is connected to
- [ ] Return the name of all available services
- [ ] Return the version of the cothority
- [ ] Propose how the other services can return status-reports
