### ISSUE TITLE
Logging refactoring

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#444]
Since the merging of `ui` and `dbg` into `log`, we now have several redundancy and different functions that are inconsistent together.
See the big discussion with https://github.com/dedis/cothority/pull/441#discussion_r68012134
What do you think ?

**Comment by ineiti** [comment]
I still like the idea of being able to put debug-output on different numerical levels _in addition_ to use things like `Print`, `Info`, `Warn` and so on. The latest `log`-library kind of resumes the best, as you don't want to use `ui` and `dbg` in a separate manner.

**Comment by Liamsi** [comment]
See also the discussion here: https://github.com/dedis/cosi/pull/38#issuecomment-227754235

**Comment by nikkolasg** [comment]
I have a few concerns about this strategy:
*  How do you handle the flag argument for both cases ? You would need to handle both:
   * `-d 1,2,3,4,5`
   * `-v`, `-v warn`, `-v error`
* We *did not* use all the `LvlXX` from the beginning. I don't see why should we force ourself using something if we don't need it ? That just bears more work on us without any *clear* benefits. 
With grep I get:
```
dbg.Lvl1 104 results
dbg.Lvl2 93 results
dbg.Lvl3 206 results
dbg.Lvl4 86 results
dbg.Lvl5 16 results
```
That means that at least Lvl5 is useless, and lvl3 is way to much used. In the experience I had with deterlab, localhost and so on, each time I needed to debug something, `dbg.Print` was my friend, and varying the level of debugging *rarely* helped me at all finding the bug.

* Standards: From my little programming experience, I only saw these `Info, Notice...` levels. I find them much more clearer than having to specify in our github that Lvl1 is for general things, Lvl2 is for blablabla, Lvl3 is for more blablabla.

I also would have like to start with a default logging library, but now that we have a good code base, I'm not sure we want to throw away all that. Moreover, the one we have right now is pretty good in the sense that it has exactly the feature we want, without the burden of having to *instantiate* a logger struct or something (which in most of others logging library we would have to do).

**Comment by ineiti** [comment]
Irrelevant for the moment.

**Comment by nikkolasg** [comment]
Is it irrelevant really ... ? 
I'd say the situation has not changed since then... There's no urgency in this one of course but it's still something that should be discussed sooner or later.
