### ISSUE TITLE
Make the configuration in service actually work

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#455]
For the moment, the implementation is not done for the configuration parameter in `NewProtocol` for a `Service`. We should do that soon. 
The requirements are that for the first message a "service-managed" protocol sends down the tree, TreeNodeInstance also sends a `GenericConfig` which will be passed into the `NewProtocol` method of the services down the tree.
In order to do that, it seems logical to add a `SetGenericConfig` to `TreeNodeInstance` even if it looks ugly, I did not come up with a better solution yet. Any ideas ?

**Comment by ineiti** [comment]
Done.
