### ISSUE TITLE
Cothority-documentation

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#463]
Write some overview of the cothority in a `doc`-directory. The documentation should contain a 'why (motivation)/what(functionality)/how(example)' for each of:
- overview of the most important data structures
  - ServerIdentity / Roster
  - Host / Overlay
  - Protocol / Service
- longer examples of protocols / services / apps

**Comment by nikkolasg** [comment]
A high level view of the SDA architecture with the different components explained is now in the wiki https://github.com/dedis/cothority/wiki/Cothority-Framework-Description

**Comment by nikkolasg** [comment]
Furthermore I'm not sure we need "longer examples of protocols / services / app"... I mean we already have plenty of thoses already no ?

**Comment by nikkolasg** [comment]
(I'm trying to close a maximum of old non-relevant-anymore issue :D )

**Comment by ineiti** [comment]
It would be useful to have services that show how to use the different possibilities with the cothority. But not urgent, definitively.

**Comment by ineiti** [comment]
Being worked on in #752
