### ISSUE TITLE
network/local issue

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#467]
When running a lot of tests using `sda.Local` with `local.CloseAll` and `local.GenBigTree` at least the `bftcosi` protocol fails sometimes. But this is only reproducible on Travis, not locally.

One way to check this would be to verify in `local.CloseAll` that everything is correctly deleted and nothing is left over.

**Comment by Liamsi** [comment]
Could you reference the effected (skipped) tests here?

**Comment by ineiti** [comment]
All tests in `protocols/bftcosi/bftcosi_test.go`

**Comment by ineiti** [comment]
Seems to be fixed in the latest branch. Closing.
