### ISSUE TITLE
Race condition and rare deadlock in JVSS

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#471]
Rarely happens on the master branch: 
https://travis-ci.org/dedis/cothority/builds/143923343
(new race conditions were introduced in some rewrite of JVSS)

**Comment by Liamsi** [comment]
Works running the culprit test a hundred times on travis: https://travis-ci.org/dedis/cothority/builds/144119901

**Comment by Liamsi** [comment]
Race condition is fixed in PR #473 but there is still some deadlock occurring now. Most probably related how short-term and long-term secrets are handled.

**Comment by Liamsi** [comment]
Not sure if this is intentional: If one registered handler blocks (because of use of a channel for instance) it seems like the other handlers won't get called. At least for the short-term secrets one get's broadcasted and the appropriate handler never gets called for the other nodes. Could also be another problem, but I wanted to ask if this is right and intentional first @nikkolasg

**Comment by ineiti** [comment]
If the code is the contract, this is intended and normal ;) Now to know if we should change it... 

I think it makes more sense to have only one message at a time dispatched to a protocol and not multiple messages at the same time. So you would probably have to change the protocol to finish the first message before waiting for the next one.

**Comment by Liamsi** [comment]
To fix the deadlock we need to (once again) rewrite/refactor jvss. I can take care of that of that but I guess it will take some time and is not urgent right now: 
I suspect the problem to be that while the root-node is done and created the signatures, messages from either the previous rounds or even from the initialisation with `Start()` are still propagating and seem to cause a hick-up from time to time (in the next round/after `Start`).
