### ISSUE TITLE
Implement followers

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#474]
add some commands:
`cisc follow id` - starting to follow an identity-skipchain
`cisc unfollow id` - don't follow that skipchain anymore
`cisc follow update` - update all followed skipchains

**Comment by Liamsi** [comment]
Is this ready for merge? The PR is this #481, right?

**Comment by ineiti** [comment]
yes, I think it's OK. Besides the BFTCoSi-error...

**Comment by ineiti** [comment]
Done in #511
