### ISSUE TITLE
External API Design

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#475]
After some discussion with the team, we have a proposal for a clean external API of cothority.
Basically, this looks like this:

```
| Cothority / Services | < -- Go -- > | HTTP Serv - REST API | < -- HTTP (JSON) -- > Client
        |
 (internal network library with Protobuf)
        |
| Other Cothority |

```
- Having a http front end **on another port** which serves a RESTful API such as `/identity/:id`, `/cosi/sign`, `/cosi/verify` using JSON as the main data encoding.  The client can easily use any REST libraries to interface with this frontend.
- The http front end would be part of the whole binary: the http server will transforms the JSON into structs and then call the appropriate methods (depending on the endpoints of course).
- Each service will register some endpoint handlers to the http frontend such as `HandlerNewIdentity` or `HandlerConfigUpdate` for the `Identity` service. All the logic is kept in separate module.

We had some discussion about using JSON vs Protobuf for the encoding on the http frontend <-> client. Basically, our conclusion were:
- **Protobuf**: It's size and speed efficient but we don't do regular protobuf (because we encode interfaces) so it may also be complex to have clear protofiles to use for other libraries, and there's  no any applications we thought of for the moment where speed/size would be an issue (a signature or a block, or a roster list ( size=[32bytes PK + address] x N) are small).
- **JSON**: It's super well known _and_ easy to use, with a clear separation between what's external to cothority (json) and what's internal (where speed/efficiency is a matter).  A lots of libraries exist for handling REST API in JSON and a RESTFUL API doc speaks for itself (much more than a protofile).

**Master Project**: Regarding the Android app, it's best to let the student open an individual port on its own directly in the service **as a quick hack** so he can concentrate on the Android part and not having to deal with all of this.

Please feel free to _edit_ or _argue_ !

**Comment by bford** [comment]
If I understand correctly, you're proposing that the cosi binary will include a "front-end" that provides a more convenient RESTful/JSON access path to clients, purely for client-to-cothority-server interaction (and *not* for server-to-server interaction within the cothority).  This sounds reasonable and useful to me.

**Comment by nikkolasg** [comment]
That's exactly it.

**Comment by ineiti** [comment]
Thanks for the writeup - that looks good. I hope it'll also help to make a better distinction between _protocol_ (only internal communication) and _service_ (communication with clients).

**Comment by Liamsi** [comment]
@bford not only for cosi but for all other services. The discussion came up because of the students project. We came to the conclusion that on long-term it might be nice to have a http-"front-end" for every client to "service" communication. For cosi it is clear how this would look like (in fact we already coded a prototype of such an interface for cosi last year) for the other services it still needs to be defined how the clients would interact with them.

**Comment by bford** [comment]
Sounds good!

**Comment by nikkolasg** [comment]
References #500 for some ideas

**Comment by ineiti** [comment]
We finished with protobuf-over-websocket
