### ISSUE TITLE
Medco - sometimes fails

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#479]
When working on the PR #468 the `TestDeterministicSwitching` is failing on Travis (not locally though). According to @ineiti , `protocols/medco` seems to fail from time to time (10%).  I disabled the test in the PR while waiting for a fix. 
To reproduce: 
* `git checkout refactor_processor`
* Enable the test in protocols/medco/deterministic_switching_test.go

Note that I only it failing on Travis and not on my machine... Looking at the code, it seems a concurrency issue but i did not dig into it.

**Comment by ineiti** [comment]
Another `skip` is in `services/medco/service_test.go`

**Comment by Liamsi** [comment]
We can close this (as medco was moved to a private repo).
