### ISSUE TITLE
Import proto/sign to lib/sign

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#49]
Re-think the usefulness of the ```proto```-directory - is it OK to just port it back to the lib-directory? Should it be done in a way that we can ```import proto/sign``` or ```import proto/randhound``` or ```import proto/shamir``` and this way clean up the ```app/*```-directory? This way the ```proto```-directory could be used directly by third-party apps.

Or we just throw away the ```proto```-directory and include it in ```sign```

**Comment by nikkolasg** [comment]
By port you mean proto ?
I agree it could be nice to do these kinds of imports. But proto/sign is very closely related to lib/conode  and could maybe be merged with lib/conode instead of a new sub package.

**Comment by ineiti** [comment]
Of course - corrected title and message. 

And would you prefer throwing away the ```proto```-directory or rather have ```proto/(conode|randhound|shamir|simple)```?

**Comment by ineiti** [comment]
Closed in #59
