### ISSUE TITLE
Update path in the README

### ISSUE THREAD

**Issue by sycamoreone** [dedis/cothority#492]
In the README at least the following is not up to date.

```
--- a/README.md
+++ b/README.md
@@ -110,7 +110,7 @@ and that
 [`$GOPATH` and `$GOBIN` are set](https://golang.org/doc/code.html#GOPATH).
 
 ```bash
-go get -u github.com/dedis/cothority/app/cosi
+go get -u github.com/dedis/cosi
 go get -u github.com/dedis/cothority/app/cothorityd
 ```
I can't do a pull request right now and probably other parts of the README need to be updated too.

**Comment by ineiti** [comment]
Thanks - we're doing some updates in https://github.com/dedis/cothority/tree/readmes - can you have a look there?

#489
