### ISSUE TITLE
Make `sda/local` search for open port-numbers

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#495]
When running things in parallel, applying fixed IP-numbers doesn't work. Let `sda/local` search for open port-numbers.
Also change tests that use a fixed port-number, so that the tests can be run in parallel.

**Comment by Liamsi** [comment]
That's what #170 (which is part of #378). Even if the approach is a different one (mock the connections vs. search for open ports and use real connections) it tries to solve the same problem.
