### ISSUE TITLE
ServiceManager - finish method implementations

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#497]
In `sda/service.go`, there are three methods that are described but not implemented:
- `AvailableServices`
- `Service`
- `serviceByString`

It could be good to have them implemented. 
Their existence can also be questioned since for the moment we never had any use case for them. At the time of writing this, I supposed it could have been useful but for the moment, this supposition turns out wrong.

**Comment by ineiti** [comment]
Shall we delete these?

**Comment by ineiti** [comment]
Implemented.
