### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#50]
A lot of tests are failing - we should clean them up.

**Comment by ineiti** [comment]
Just to be sure that the compilation doesn't fail, it could be enough to put a dummy-test in all directories (e.g. app/*), so when running ```go test```, it tests at least whether everything compiles.

**Comment by nikkolasg** [comment]
And/Or we could set up an associated Travis CI account so it automatically tries to build everything at each pushed commit.

**Comment by ineiti** [comment]
Yes, there is quite a list on what we could/should do - I propose we do our monthly meeting early this week (Monday or Tuesday) and set up some more detailed ‘HOWTO’ about our desired workflow.

**Comment by ineiti** [comment]
Closed by #90
