### ISSUE TITLE
Services - Design decisions

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#500]
When we first started talking about Services, @ineiti wanted that we have a clean separation between Services so they could not talk to each other directly, because of maintainability reasons. Indeed, there would be a separate API from an external perspective (client) and internal perspective, and as we have our services right now, it may be hard to maintain both APIs (or not? I'm not so sure).

Now we have a `Skipchain` service and a `Identity` service that DO talk to each other. 
The way they do that is not clean: `Identity` creates a new Client and open a new connection to a host (it can even be on the _same_ host I think). It does it itself instead of using the network layer (i.e. Host / Router) to do it. 
- We _should not_ handle network layer stuff in higher levels.
- It still sounds silly to open a connection to our self ...

It seems the model we used to think before does not make sense now and we should start thinking about how to mitigate these tricks and have a nice way for Services to talk to each other.
I don't have any clear ideas yet but I'll start thinking about it, and if you have any, please post them !

**Comment by ineiti** [comment]
If we do some JSON-RPC for the services, we could build in a shortcut so we don't have to go through the network when calling locally.

**Comment by ineiti** [comment]
We're down to using protobuf-over-websockets. So it should be quite easy to use direct messages between services using the `onet/network`-connections.

**Comment by jeffallen** [comment]
@ineiti says close, what we have is working well enough. (i.e. func (c *Server) Service(name string) Service)
