### ISSUE TITLE
Network encoding - consistency regarding pointers vs values

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#501]
There's a bunch of methods in the network library that either treat msg as pointers or as values and it's very confusing since the comments are not describing enough and there's no clear distinction / benefits.
- Using pointers:
  - `NewNetworkMessage(m)`
  - `UnmarshalRegistered(buff)`
- Using values:
  - `UnmarshalRegisteredType(buff)`

I'm sure I forgot some, but nevertheless we should be consistent and stick with something like
- Encoding a message takes a pointers (protobuf requires it)
- Decoding a message returns a value (most of the code use that logic already)

And remove the others methods...

**Comment by ineiti** [comment]
I would prefer the networking-functions to return pointers, too. Else we have pointers/values still mixed up.
