### ISSUE TITLE
Makefile doesn't always checkout the right branch (on travis)

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#504]
The mechanism deployed in the Makefile (introduced here: https://github.com/dedis/cothority/commit/3680975ab71bf3064002e50ee4e292efd79c6002#diff-b67911656ef5d18c4ae36cb6741b7965R2) doesn't work reliably. We stumbled upon this issue in PR #499 where @nikkolasg ended up hard-coding the branch's name at the end to see if travis passes. If this problem is resolved in #499 this issue can be closed.

**Comment by ineiti** [comment]
Working at it in #508

**Comment by Liamsi** [comment]
See related discussion here: https://github.com/dedis/cothority/pull/508#issuecomment-238681185
