### ISSUE TITLE
Cleanup code in general

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#506]
- method-signature mixups
  - [x] `local.StartProtocol` and `local.CreateProtocol` have very similar functions but different signatures -> mend it
  - [x] `overlay.*Protocol*` also differs in signature -> mend it
  - [x] `network` still has some fields called `entity` instead of `serverIdentity`
  - [x] remove old `ProtocolMessages` and `Packet` references and methods

Import Makefile-changes from #499 and #508 once it's clear it's working.

**Comment by Liamsi** [comment]
> interfaces with only one implementation -> remove them

Is there any particular reason to remove them? I mean even if there is just one implementation: deleting the interfaces makes it impossible to mock them (even if locally) or pick another implementation (greater flexibility with almost no cost).

**Comment by ineiti** [comment]
If the interfaces are used, it is good, and we keep them.
If the interfaces just hide a single structure, they make it more complicated.
As the implementation of the 'channel-network' doesn't use the interfaces (which would be the 1 use-case I can think about for these interfaces), I see no need to keep them around.

Besides giving a nice feeling, what is the advantage of having an interface with only one implementation? In my opinion it just adds an unused layer which makes things more complicated.

**Comment by Liamsi** [comment]
Pros&Cons of interfaces (even or especially with a single implementation):

Pros:
+ ability change underlying implementation without tocuhing the rest of the code
+ clear interface independent from implementation
+ ability to "mock" away the implementation for unit tests
+ robust API for future use-cases (change `SecureTCPConnection` with `SecureUPDConnection` and/or `SecurePURPSConnection`, etc.)

Cons:
- "hides" the implementation (one extra search/click) to find it
- additional complexity (?)

Did I miss something?

**Comment by ineiti** [comment]
Due to popular request and promises to use the interfaces I revived `Host`, `Conn`, `SecureHost`, and `SecureConn`.

As a general rule I do think it's better to add interfaces only once there is more than one implementation.
