### ISSUE TITLE
Network interfaces and testing

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#514]
Use the network interfaces (`Conn`, `Host`, ...) to enable testing of the `Receive` and `Send` functions with regard to partial receiving/sending only.

Instead of putting test-variables in tcp, use external traffic shaper:
https://github.com/tylertreat/comcast
or
https://github.com/dcm-oss/blockade

**Comment by nikkolasg** [comment]
I'm wondering if we could not make a `UnstableHost` which wraps around another hosts, and have some heuristics to pass or drop a packet, partially or fully etc... 
What do you think ?

**Comment by ineiti** [comment]
This would also be useful for end-to-end testing of protocols. But here the issue was about testing the `Host` itself, so you cannot do that with an `UnstableHost`. Even though the latter would be a nice tool to have!
