### ISSUE TITLE
StatusReporter - Network

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#533]
The network layer reports a status with some inconsistent key : values pair and with some stylish issue:
- `Packet_Sent` returns the number of bytes sent from all connections. It should be more something like `bytes_sent`
- Same for `Packet_Received`
- From a general perspective I would keep all the key name lower case, but let's discuss this matter in this  issue...

**Comment by ineiti** [comment]
+1 FOR LOWER CASE (sorry for the caps-lock;)

**Comment by ineiti** [comment]
Done
