### ISSUE TITLE
update cisc to use rootsc

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#544]
`cisc` creates a new skipchain based on the given list of cothorities. So it only uses a Config-SkipChain (configsc). It does not depend and does not know how to use a Root-SkipChain (rootsc).

This is only possible once #599 is implemented.

**Comment by nikkolasg** [comment]
Can you provide a  bit more detail ? 
What is the "rootsc" ? There's no such app.

**Comment by ineiti** [comment]
New skipchains will not directly translate root/config/data-skipchains.
