### ISSUE TITLE
Eventual error in identity-skipchain

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#553]
Check why identity-skipchain doesn't update the skipblocks when `ProposeVote` is called and returns successful. In general, why does the `cisc` not store any skipblock? How should it verify things have been correctly signed?

**Comment by Liamsi** [comment]
@ineiti is this still the case? Just asking, since this issue was opened some time ago.

**Comment by ineiti** [comment]
Will be fixed in #666
