### ISSUE TITLE
Make timestamp service (again)

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#554]

**Comment by ineiti** [comment]
Have a modular possibility of including data in the timestamp.

**Comment by nikkolasg** [comment]
> Have a modular possibility of including data in the timestamp.

? Well, generally, you submit *any* data, the timestamp service hash it and timestamp the hash, and returns you the hash + timestamp signed.  What other thing you wanna add ?

**Comment by Liamsi** [comment]
> Have a modular possibility of including data in the timestamp.

Can you elaborate on that issue?

**Comment by ineiti** [comment]
Still confused about what we need to do and what the two different options from Friday's discussion are:

# Timestamps A
- one for inclusion-proof of the timestamp and 
- one for the latest software-updates at this moment in time

# Timestamps B
Loosely-coupled timestamp-services 
- just creates records of merkle-tree-inclusion-proves - perhaps every minute or every hour
- Associates freshness-proves with the time

**Comment by Liamsi** [comment]
Ok, after discussing with @LefKok and @ineiti here is what we decided to do:

We will (first) go with a simplified version where not all nodes of the cothority can take client requests (only the root node can).

Client = external clients

**Client perspective**
- Clients send hashes of data to the root node; for "swups" the data will be some client generated random number  
- After `epoch` seconds the client receives is a `timestamp` and a collective signature on (`timestamp`, `hash(treeroot)`) plus an inclusion proof that proves that the clients nonce (or hash of it) has been included in the underlying merkle tree
- The client can now rebuild the for him relevant part of the tree and verify that the recvd. signature is valid and if the timestamp is in a certain fixed timeframe.

Remarks: epoch will be sth like 10s

**Cothority (root node's) perspective**
- Root node receives the hash of the data from several clients and includes these hashes in the leafs of the tree
- After `epoch` seconds the root node initiates a cosi round on (`hash(treeroot)`, `currentTimestamp`)
- After cosi is done the root replies to each client request individually. The data (as mentioned above) is the timestamp, a collective signature on (`timestamp`, `hash(treeroot)`) plus an inclusion proof for the requested data (this might be different for every client).

**Comment by Liamsi** [comment]
Any comments, corrections, additions? /cc @LefKok @nikkolasg @ineiti ?

**Comment by nikkolasg** [comment]
> Clients send hashes of data to the root node; for "swups" the data will be some client generated random number
hashES ? For me a generic timestamp service take a slice of byte, and do the timestamp on it. The client should be responsible for hashing the multiple documents together and then send the hash to the timestamp server. If we are going on with this, the timestamp server should only accept hashes, i.e. fixed size array of bytes.

**Comment by Liamsi** [comment]
> hashES ? 

Because the server collects multiple client requests (each containing one hash) from multiple client*s*. The cothority releases the signature after the `epoch` has passed. Is that more clear, now? Or still doesn't make sense?
