### ISSUE TITLE
medco: testcode in medco doesn't pass go vet (on go1.7)

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#559]
Currently not urgent but we would like to switch to go1.7 soon (#557). The vetter in 1.7 better finds potential sources of bugs in tests, too. Hence, out travis builds fail the `go vet ./...` command. To change this it would be neccessary to make `libmedco.ClientResponse` use keyed fields instead of unkeyed while initializing.
For instance `storage.InsertClientResponse(ClientResponse{CipherVector{}, testCipherVect1})` would need to be changed to:

```
storage.InsertClientResponse(ClientResponse{
        ProbabilisticGroupingAttributes: CipherVector{},
        AggregatingAttributes: testCipherVect2})
```

(Find a corresponding `go vet` output here: https://travis-ci.org/dedis/cothority/builds/155486149#L215 )

**Comment by nikkolasg** [comment]
Medco is now in its own repo. Therefore I close the issue :)
