### ISSUE TITLE
Service request - Should Client choose the Roster ?

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#564]
In the CoSi service, the client defines what is the Roster he wants to use to collectively sign his document. That was fine for our experiment but after some discussion with @Liamsi , I find that rather contradictory with the definition of a Cothority. A Cothority is supposed to be a set of nodes under **closed membership**: Google + EFF + Mozilla trust each other and form a cothority and release their group.toml.

By allowing clients to chose their Roster, basically they chose their Cothority, they define the _closed membership_\* set of nodes. I think it rather _contradictory_.

This contradiction appeared again with the Timestamp service @Liamsi is writing. Do the timestamp service allow to make a CoSi timestamp signature with any Roster, or a fixed one, the one he belongs to ?

For me it makes most sense that Conodes define & advertise themselves the Cothority they belong to. 
I haven't checked the idea thoroughly but I think it's possible to make one co-node belongs to multiple Cothority.

**Comment by Liamsi** [comment]
Thanks for summarizing this @nikkolasg.

> This contradiction appeared again with the Timestamp service @Liamsi is writing. Do the timestamp service allow to make a CoSi timestamp signature with any Roster, or a fixed one, the one he belongs to ?

A short addition: In the timestamp application this is specifically problematic if the timestamp server handles signing requests in batches (sign tree root, return proof of inclusion). If every client sends his own roster/group definition ... Which group definition would be used?

**Comment by ineiti** [comment]
Definition of the terms used (feel free to edit):
- a cothority-node, or a conode - `cothorityd` running on a server
- a cothority - a **_co_**llective au**_thority_** formed by any group of two or more conodes
- a roster - list of conodes forming a cothority
- CoSi - **Co**llective **Si**gnature signed by any cothority
- Timestamper - service using CoSi to regularly sign hashes concatenated with a time
- That other data-structure - holds definitions of cothorities and their updates

A Conode can belong to any number of cothorities and 'per se' doesn't even know which cothorities it belongs to. Its services **can** have some of that information.

For CoSi anybody can have a hash signed anytime using any combination of conodes (which form thus a cothority and are defined by a roster).

The best way for a timestamper to get its roster would be to ask an SC (that other data-structure) and then ask any of those conodes to stamp the hash.
A more simple approach for NSDI is to have an API-message `SetupStamper` which sends a cothority-definition to the root-conode (the first conode of the roster). The root-conode will return an ID (which later should be the ID of the SC used) and the collective public key. 
Now any client who knows the root-conode, the ID and the collective public key (the roster need only to be stored in the root-conode) can send a `SignHash` and will have to wait up to the round-time to get the collectively signed merkle-tree-root (which has to include the timestamp) and the inclusion-proof of his hash.

And of course there is your favorite Google-doc (EPFL-members only):

https://docs.google.com/a/epfl.ch/document/d/1j8Yu_TJBtrcK13gGMCWpso16Ovmy2gZ0Ljv_8VFTraQ/edit?usp=sharing

And of the terms (EPFL-members only):

https://docs.google.com/a/epfl.ch/document/d/1VBJERBo2ILCFUkkjrr53kW10v0QsZCihuKGTr3DLY5s/edit?usp=sharing

I prefer comments on the google-docs if that is OK with you. If you think so, too, you can close that comment and continue on the google-doc.

**Comment by nikkolasg** [comment]
See the length of all our comments here, and see the size google docs allow for commenting on the side... I'm not sure it's more readable on the google docs. I think we should either continue on that, or make a google doc explicitly for this issue where we describe different possibilities. What do you think ?

Until then...:
> A Conode can belong to any number of cothorities

True.
> Its services can have some of that information

That's the big question. It seems to me that they MUST have that information. Your definition of Cothority is incomplete from my PoV: `a cothority - a collective authority formed by any group of two or more conodes` AND `This group is under a closed membership policy`, they collaborate together.

> For CoSi anybody can have a hash signed anytime using any combination of conodes (which form thus a cothority and are defined by a roster).

By saying that, this means a cothority is not a closed membership group now, it's open as everyone can define one. For me it makes more sense that a CoSi client gives the message + the Cothority ID (RosterID) he wants to use to the CoSi service. The CoSi service should be the one that knows in which Cothority he belongs and check if the given RosterID match one of the Cothority he belongs to.

Maybe I'm missing something....

> A more simple approach for NSDI is to have an API-message SetupStamper which sends a cothority-definition to the root-conode (the first conode of the roster). The root-conode will return an ID (which later should be the ID of the SC used) and the collective public key. 

Should it not be a config file that tells which Roster this timestamper service belongs to ?? (and there's only one).Otherwise the same problem occurs, if the timestamper service belongs to many cothorities, how should the epochs be used ? One timer per Cothority ? or one timer for all cothority,i.e. every 10 secs, the timestamper service will make X timestamp signing operations, where X is the number of Cothority he belongs to.

**Comment by ineiti** [comment]
Whiteboard?

**Comment by Liamsi** [comment]
> A more simple approach for NSDI is to have an API-message SetupStamper which sends a cothority-definition to the root-conode (the first conode of the roster). The root-conode will return an ID (which later should be the ID of the SC used) and the collective public key. 

I'm not sure I got the full idea here but wouldn't it be even simpler if both the cothority root node and the clients requesting a signature on their hash have a roster (toml) file (which preferably is identical) and simply use this without exchanging some IDs? As long as we don't use SCs to get the latest set of keys.
