### ISSUE TITLE
Cothority v1

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#576]
On October 31st there will be a gopkg.in-release for cothority v1. Everything that should be included has to be in this EPIC.

**Comment by nikkolasg** [comment]
One important thing is the "wire protocol format" for which we need to talk about (decide what is needed,what to do, if it goes there etc).

**Comment by Liamsi** [comment]
Another issue that came to my mind: Should we aim for an cosi-exception mechanism?

**Comment by nikkolasg** [comment]
Next discussion on this topic: what to add ? 
I'd like to see #287 happening, so then later we can work on #680 and #286 later in subsequent sub-versions.

**Comment by ineiti** [comment]
DID IT!
