### ISSUE TITLE
Simplify monitor NewSingleMeasure

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#603]
Why does `monitor.NewSingleMeasure` need a call to `.Record()`? Sounds illogical to me. I propose that `NewSingleMeasure` directly calls `.Record()`.

**Comment by nikkolasg** [comment]
`NewSingleMeasure(value).Record()` ? It is to make every measure implements the `Measure` interface. Moreover, if you make one that does not need to call `Record()` but the others do, to me it seems inconsistent. I prefer consistency over `hide one method call more`.

**Comment by ineiti** [comment]
Hmm - consistency is also about the language. So if we measure the time, there is a `New` and a `Record`, that makes sense. But a `SingleMeasure` - why have a record?

We could call it `RecordSingleMeasure`, which does a `NewSingleMeasure` and call `Record` on it.

**Comment by nikkolasg** [comment]
+1 for having a method `RecordSingleMeasure` directly.

**Comment by ineiti** [comment]
Implemented in #709
