### ISSUE TITLE
Add a websocket service

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#618]
In order to interact between the web-interface in javascript and the cothority, this uses protobuf over websockets to transmit messages to the services-API.

**Comment by nikkolasg** [comment]
Can you explain a bit more what exactly do you want ?

**Comment by Liamsi** [comment]
And why?

**Comment by Liamsi** [comment]
Thanks for clarifying the reasoning behind this issue. If this WIP, is there a brnach/PR for it? (I'm just going through all issues/PRs etc)

**Comment by ineiti** [comment]
Updated the epic this is attached to and the description.
