### ISSUE TITLE
Extract PVSS functionality from RandHound package

### ISSUE THREAD

**Issue by Daeinar** [dedis/cothority#624]
As mentioned in #341 we should extract the functionality of PVSS (i.e. everything in `proof.go`) and put it into the crypto library `dedis/crypto`.

Moreover, check whether it's feasible to simplify some of the function interfaces (like the return values in `Setup(...)`).

**Comment by nikkolasg** [comment]
Closed because it's being taken care of in https://github.com/dedis/crypto/issues/96
