### ISSUE TITLE
Return error in protocol-handler

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#631]
`TreeNodeInstance.dispatchHandler` doesn't return errors from the handler.

**Comment by Liamsi** [comment]
See here: https://github.com/dedis/cothority/blob/73f9e0852310a82aa077a580f65842827e597652/sda/treenode.go#L296

**Comment by Liamsi** [comment]
Might also be related to: #561 (?)

**Comment by Liamsi** [comment]
> TreeNodeInstance.dispatchHandler doesn't return errors from the handler.

Seems like the handles aren't guaranteed to return errors at all. At least here
https://github.com/dedis/cothority/blob/73f9e0852310a82aa077a580f65842827e597652/sda/treenode.go#L205 it is only checked if the passed `interface` is a function and the number of and type of arguments are verified there; the return params aren't checked.
