### ISSUE TITLE
New network cleanups

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#636]
Starting to play around with the network - some cleanups:
- rename `NewConode` and `NewConodeWithRouter` to `NewConodeTCP` and `NewConode`
  - both should return an error instead of `panic`
- `network.NewTCPConn` has 2 `sleep`s.

**Comment by nikkolasg** [comment]
> both should return an error instead of panic

I'm not so sure since you can't do much if it panics, the same way `net.Listen` panics if address is already in use..

**Comment by Liamsi** [comment]
Is there a PR related to this issue (asking because it's in WIP-pipeline).

**Comment by nikkolasg** [comment]
This has already been impl. in master. closing.
