### ISSUE TITLE
network.Router: send packet to ourself

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#649]
Sending packet to ourself still creates a new connection on the same machine which seems useless. A simple fix would be to look if the destination address == router address, and if so, directly dispatch the message to the `Dispatcher`.

**Comment by Liamsi** [comment]
> A simple fix would be to look if the destination address == router address, and if so, directly dispatch the message to the Dispatcher.

Could this somehow create a security problem? If not this simple approach is a good idea.

**Comment by nikkolasg** [comment]
In what sense ? The only thing proposed here is to not create a real connection if the destination == sender. What do you mean ?

**Comment by Liamsi** [comment]
Didn't think it through: But here was my rough idea: is it possible to spoof the address in the message and then get it wrongly dispatched? Maybe, with tls this isn't a problem? But I'm not sure.

**Comment by Liamsi** [comment]
OK, what I described doesn't work as this is for sending and not for the receiving part!

**Comment by ineiti** [comment]
Not really a bug, as it's usable even with the issue open.
