### ISSUE TITLE
Default-port for proxy redirection

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#65]
The default port should be 10001 instead of 4001, so that it doesn't interfere with the app-ports.

**Comment by nikkolasg** [comment]
Actually It does not interfer since it is only on users.deterlab and not used to listen but to connect to the SSH tunnel. But you are right it is better to keep them close with the monitor port.

**Comment by ineiti** [comment]
And when we run it locally? Doesn't it interfere then?

**Comment by nikkolasg** [comment]
No proxy on local host.

**Comment by ineiti** [comment]
OK - where is the main-proxy-port? Let's just put it 1 above the main-proxy-port per default.

**Comment by nikkolasg** [comment]
What do you call the "main-proxy-port" ? 
Proxy is listening on the same port as the main sink / monitor process, so users of the lib do not have to know if they connect to a proxy or directly the main sink.  The port of the main sink is still static (that will change soon with after merging the quickfix_args branch, we will then put it in *platform_config*.toml) and is 10000. 
The port the proxy connects to the sink (or the ssh tunnel) is written in deter.toml.

**Comment by ineiti** [comment]
main-proxy-port -> sink-port -> 10000, so let's put the proxy at 10001. Then the sink and the proxy, which are similar in usage, are also similar in port-numbers.

**Comment by nikkolasg** [comment]
You can already do that by changing your deter.toml, it is configurable. Only the sink port is not **for now**.

**Comment by nikkolasg** [comment]
Note: careful, because we can not use the same port on users. ( just saw that you were experimenting too, and ssh was failing short ><) I moved mine to 10002
