### ISSUE TITLE
Merge cosi repo with cothority

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#650]
Currently cosi and cothority depend to each other and as we currently sometimes break CoSi with changes in Cothority and vice versa: Hence, it makes sense to merge CoSi back to the cothority repo.

As we discussed, the cosi repo should still exist: It should be a pointer to the cosi packages and should contain clear instructions on how-to install cosi (and only cosi?).

Things to consider / questions / TODOs:
- [x] ~~change imports (for `v.0` _and_ `master`?)~~ master and v1
- [x] documentation in cosi repo (Readme etc)
- [x] should this be part of `v.1`?

(Feel free to edit and add todos etc)

**Comment by ineiti** [comment]
Definitively part of v1. I already think of separating protocols, services and apps from the `cothority`-repo in v2 ;)
