### ISSUE TITLE
Cleaning up hosts on Deterlab

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#66]
When running experiments on deterlab, only the used hosts are cleaned up with remaining apps that run. This can create problems if you run first an experiment with 16 hosts, then one with 4 hosts. The 12 remaining hosts aren't cleaned up.

This Quickfix will include the ```node_list```-command from users.deterlab.net to clean up all apps from all started nodes, regardless of how many nodes are used for that run.

It is already included in ```matplotlib_with_new_stats```, but will find its way as a separate pull-request.

**Comment by nikkolasg** [comment]
closed by #88
