### ISSUE TITLE
Data race / timeout

### ISSUE THREAD

**Issue by Liamsi** [dedis/cothority#669]
These two might be duplicates:
<details> <summary>
Data race (expand for error output) </summary> 
https://travis-ci.org/dedis/cothority/builds/174153591
<pre><code>
receive server identity failed:==================
WARNING: DATA RACE
Write at 0x00c4202153d8 by goroutine 53:
  internal/race.Write()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/internal/race/race.go:41 +0x38
  sync.(*WaitGroup).Wait()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/sync/waitgroup.go:129 +0x151
  github.com/dedis/cothority/network.(*Router).Stop()
      github.com/dedis/cothority/network/_test/_obj_test/router.go:119 +0x377
  github.com/dedis/cothority/network.TestRouterExchange()
      /home/travis/gopath/src/github.com/dedis/cothority/network/router_test.go:350 +0x60e
  github.com/dedis/cothority/network.TestRouterExchange()
      /home/travis/gopath/src/github.com/dedis/cothority/network/router_test.go:341 +0x4fd
  github.com/dedis/cothority/network.(*Router).Send()
      github.com/dedis/cothority/network/_test/_obj_test/router.go:145 +0x828
  github.com/dedis/cothority/network.TestRouterExchange()
      /home/travis/gopath/src/github.com/dedis/cothority/network/router_test.go:329 +0x42c
  github.com/dedis/cothority/network.TestRouterExchange()
      /home/travis/gopath/src/github.com/dedis/cothority/network/router_test.go:324 +0x3a1
  testing.tRunner()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610 +0xc9
Previous read at 0x00c4202153d8 by goroutine 56:
  internal/race.Read()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/internal/race/race.go:37 +0x38
  sync.(*WaitGroup).Add()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/sync/waitgroup.go:71 +0x292
  github.com/dedis/cothority/network.(*Router).launchHandleRoutine()
      github.com/dedis/cothority/network/_test/_obj_test/router.go:292 +0x63
  github.com/dedis/cothority/network.(*Router).Start.func1()
      github.com/dedis/cothority/network/_test/_obj_test/router.go:82 +0x3fc
Goroutine 53 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:743 +0x12f
  github.com/dedis/cothority/log.MainTest.func1()
      /home/travis/gopath/src/github.com/dedis/cothority/log/lvl.go:386 +0x38
Goroutine 56 (finished) created at:
  github.com/dedis/cothority/network.(*TCPListener).Listen.func1()
      github.com/dedis/cothority/network/_test/_obj_test/tcp.go:359 +0x83
  github.com/dedis/cothority/network.(*TCPListener).listen()
      github.com/dedis/cothority/network/_test/_obj_test/tcp.go:400 +0x398
  github.com/dedis/cothority/network.(*TCPListener).Listen()
      github.com/dedis/cothority/network/_test/_obj_test/tcp.go:362 +0xba
  github.com/dedis/cothority/network.(*TCPHost).Listen()
      <autogenerated>:87 +0x72
  github.com/dedis/cothority/network.(*Router).Start()
      github.com/dedis/cothority/network/_test/_obj_test/router.go:83 +0xfe
  github.com/dedis/cothority/network.TestRouterExchange.func1()
      /home/travis/gopath/src/github.com/dedis/cothority/network/router_test.go:315 +0x65
==================
 Error while receiving ServerIdentity during negotiation EOF
Error while reading public key: EOF
PASS
coverage: 89.4% of statements
Found 1 data race(s)
</pre></code>
</details>

See also (timeout): https://travis-ci.org/dedis/cothority/builds/174158079#L207

**Comment by nikkolasg** [comment]
Yeah... Golang thinks there's a race on the `WaitGroup` of the router because it is used in different go routines. But since waitgroup *is* thread-safe it's not really a race.
I'll try to put mutex around it, even if it's a solution to a dumb problem.

**Comment by Liamsi** [comment]
> Yeah... Golang thinks there's a race on the WaitGroup of the router because it is used in different go routines. But since waitgroup is thread-safe it's not really a race.

Sounds like you found a bug in the race detector?

**Comment by nikkolasg** [comment]
Mhhh reading a bit around on the internet, I think it's because a `wg.Add` is called after a `wg.Done` sometimes for example when the `Listen()` and the `Stop` calls are very close in time. I see if I can come up with something..
