### ISSUE TITLE
Data race in BFTCosi

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#670]
Here's the Travis output : https://s3.amazonaws.com/archive.travis-ci.org/jobs/174164914/log.txt

I could not reproduce it on my machine though.

**Comment by ineiti** [comment]
Yes, most of those travis-bugs are really hard to reproduce. Sometimes I got to reproduce the error locally by taking large amounts of nodes. Another time I intentionally split up the network packets to see an error.

**Comment by nikkolasg** [comment]
related to #673

**Comment by nikkolasg** [comment]
Never saw it again in #673 so closing this one.
