### ISSUE TITLE
CoSi - setup server command not showing in help

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#675]
I could not find an *easy way* (in fact, any way) to know how to generate my keys from the command line interface. `cosi help server` does not show about `setup` command.

**Comment by ineiti** [comment]
but `cosi help` does?

**Comment by ineiti** [comment]
Well `cosi setup` doesn't exist, so we should simply add the setup-command to `cosi`.

**Comment by nikkolasg** [comment]
In fact it *does* exists `cosi server setup` works, but I knew it because @Liamsi told me so :)

**Comment by Liamsi** [comment]
It shows up using `cosi server help`

**Comment by nikkolasg** [comment]
@Liamsi I must have had a bad version then. my bad. closing the issue.
