### ISSUE TITLE
Merging SNP17 back into master

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#678]
List issues here that we want to merge back into master.

**Comment by nikkolasg** [comment]
The snp17 branch contains a prototype of randhound and randherd,i.e. both misses the collective signature phase. randherd will need a bit of refactoring to be able to support that I'm guessing. So do we want to include them as is or wait until we do this collective signing phase ? is it a priority to do that ?

**Comment by ineiti** [comment]
Closed for the moment - randhound is about to be rewritten.
