### ISSUE TITLE
RFC for CoSi 

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#680]
We need a clear RFC for CoSi which should contains (please add to the list anything missing):
+ A clear definition of all the packets and their format,i.e. protobuf packet format, needed for a round of CoSi. This part leads us to have a clear packet format definition in dedis/cothority (issue  #287 )
+ A clear explanation of all the steps of CoSi *including* the tree / roster management
+ A clear exception mechanisms ( issue #286  )
+ A short security part, linking back to the paper maybe.

After this is written down, the next logical steps would be to make sure our implementations follows the RFC.
Then after, saving the world with deploying CoSi cothority everywhere.

**Comment by jeffallen** [comment]
CoSi is dead, but haviong a better spec for BLS cosigning would be nice. However, this will be a student project, or something a PhD needs to do to get something standardized. Closing.
