### ISSUE TITLE
How to run simulation on protocols

### ISSUE THREAD

**Issue by guoyangrui** [dedis/cothority#692]
Tried to run simulation with go/src/github.com/dedis/cothority/simul# ./simul runfiles/pbft.toml but received error "Didn't find simulation PBFT". How to run simulations other than the example?

**Comment by ineiti** [comment]
Yes, this is correct. Unfortunately there are quite some `.toml`-files in there that are obsolete now. I opened #693 to fix this.

In the meantime you can use all `test*.toml`-files - they are working. You can run

```
cd $GOPATH/src/github.com/dedis/cothority/simul
./test_simul.sh
```

to run them all. If you're on a Mac you'll get a message about how to increase the number of connections for one of the simulation, as there is a limit in MacOSX.
