### ISSUE TITLE
Service - Message dispatching ambiguous

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#708]
There is two kind of message a `Service` can receive: a `ClientRequest` message and any other messages coming from the network from other nodes. The former is automatically "un-wrapped" by the `ServiceProcessor` **IF ANY** (or by the `Service` which implements the `ProcessClientRequest`). The latter is dispatched to the `Context` then to the `Service.Process` method. 

Yeah this is a complexity that we should try to reduce in our future next refactorings, so I'm opening an issue so we don't forget.

**Comment by jeffallen** [comment]
@ineiti says: This is not true anymore.
