### ISSUE TITLE
Remove CoSi server

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#770]
Shall we remove the server from the `cosi`-app and have only 1 server, called `conode`?

Linus says: Yes

**Comment by nikkolasg** [comment]
What's the difference between the cosi server and the conode server ?
If none, I got no problem with that, +1.
If there are some, then should we port them to conode before deleting ?

**Comment by ineiti** [comment]
cosi-server was used when CoSi was a standalone. Now that CoSi is integrated again in the conode-repo, we don't really need it. Except if we decide to do a `cothority/cosi`, then we'd need it again ;)

We'll ask Bryan at 11am.

**Comment by ineiti** [comment]
Will not remove cosi-server for now.
