### ISSUE TITLE
Rename Conode Configuration Files

### ISSUE THREAD

**Issue by Daeinar** [dedis/cothority#773]
During my edit pass over the README, I realised that the names of the configuration files `config.toml` and `group.toml` might not be ideal from an operational security perspective. I already see people accidently sending around their `config.toml` to request access to cothorities thereby exposing their conode's private key. I therefore propose the following change of the default file names:
- `config.toml` => `private.toml`
- `group.toml` => `public.toml`

Thoughts?

**Comment by nikkolasg** [comment]
+1 for `config.toml` => `private.toml`
-1 for `group.toml` => `public.toml`: Even if it *is* the public version, it's mostly used to create the group, the roster ==> the cothority in our new terms. That's something that is copy/pasted into a bigger group.toml containing all the others addresses and public keys. Or it can also be used as-is in a "simulation" with the group having only one member.
What do you think ?

**Comment by Daeinar** [comment]
Well but for documentation it's easier to tell people "send us your public.toml configuration" file.

**Comment by Daeinar** [comment]
I see your point, but I think `public.toml` is more intuitive and you could think of it as the public available information of the cothority. Namewise it would be also a nice counterpart to `private.toml`.

**Comment by nikkolasg** [comment]
> public.toml is more intuitive

Is `group.toml` so non-intuitive in the context of decentralized system ?

**Moreover**, there is the address of the server and the description inside the `group.toml`, so it's not really a nice relation between private and public keys... I'm ok with changing name, even though `group.toml` does not bother me, but I'm not a fan of `public.toml` in this context. 

What about `identity.toml` ? (with or without "pub" suffix)

**Comment by nikkolasg** [comment]
Ok after discussion, @Daeinar convinced of `public.toml`. +1 for both ideas.
I think it should be pretty trivial to change in onet right ? Like that, it can be put into the public facing README. What do you think ?

**Comment by ineiti** [comment]
While we're at it, can we remove the first line of the soon-to-be `public.toml`? For the moment it looks like this:

```
Description = "Description of your cothority roster"

[[servers]]
  Address = "tcp://127.0.0.1:6879"
  Public = "N3X/Qd2D1Z2mHth24NrR/1mfvlOmhxyvicjZB+lhkv4="
  Description = "Description of your server"
```

If we remove the first line, it's more easy to cat multiple `public.toml` files together.

**Comment by Daeinar** [comment]
Moreover, we should think about including a warning comment to the beginning of `private.toml` saying that this file should never be shared with anyone.
