### ISSUE TITLE
Protobuf flattening array bug - still exists !

### ISSUE THREAD

**Issue by lbarman** [dedis/cothority#774]
An echo from the past... ah, almost one year ago now, young Ludovic discovered the marvels of cothority. And he was trilled, amazed to see arbitrary interface{}'s being swalled whole on one side, and reappearing intact on another side of the network. Yet, there was a small group of irreducible interfaces, who ever and again resisted the empire: 

![image](http://storage5.static.itmages.com/i/17/0110/h_1484088506_7676580_a4ff084fe2.jpeg)

So the problem is the same as before, my arrays get flattened:
```
//pks = [[abstract.Point, abstract.Point]]
msg := MY_GREAT_MESSAGE{ field: pks}
...SDA...
msg' :=  MY_GREAT_MESSAGE{ field: pks'}
//pks' = [[abstract.Point], [abstract.Point]]
```
To fix it, I had to do this: [trustee.go line 313](https://github.com/lbarman/prifi/blob/3fc2843eb72d4f864dd3e62bec45e6ff32bc6205/prifi-lib/trustee.go#L316)

So after all this time of ignoring the problem (on my side), I'm willing to clean it up, to remove this ugly piece of code. I have no idea where it happens in the SDA, with some hints I can write you a failing test / PR with a fix.

**Comment by nikkolasg** [comment]
It's happening in the protobuf library, in `encode.go` or `decode.go`. Please, make us one more nice issue like that in the protobuf repo. We'll gather our generals and talk about the best manœuvre in order to eradicate these rebels. Let's keep in touch by pigeon post (with the Caesar cipher!)

**Comment by lbarman** [comment]
Follow-up in protobuf. https://github.com/dedis/protobuf/pull/30
