### ISSUE TITLE
Cleanup ssh of proxy

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#80]
At the end of a measurement the ssh of the proxy should be killed.

**Comment by Daeinar** [comment]
Could you please be a bit more specific?

**Comment by ineiti** [comment]
In `Start` from `deploy/platform/deterlab.go` a ssh-proxy-forwarding is started, which is supposed to be killed by the `Cleanup`-method in the same file. We had problems with the ssh still running after the simulation failed, I think. Then you can't launch another simulation, because the ssh is still there. 

Or was it only me who uses  two users for the simulations? Then one user can't kill the ssh from the other user?

**Comment by ineiti** [comment]
Done in `cosi_linus`
