### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#801]
Now: cothority follows onet-version
Wanted: cothority has own version

**Comment by ineiti** [comment]
Needs discussion how to implement versioning

**Comment by jeffallen** [comment]
Additional linked should-haves for production-grade security software:
* reproducible builds (#967)
* git tag and/or latest commit hash is in the binary (see https://stackoverflow.com/questions/11354518/golang-application-auto-build-versioning)
* include some kind of whitelist for which PGP keys may sign tags?
* binaries which are co-signed, showing that several conodes confirm that GIt tag X -> binaries Y via repro building

**Comment by jeffallen** [comment]
Dup of #1652
