### ISSUE TITLE
[JVSS] Explicit rules/code about sloppy (late) participants

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cothority#813]
In JVSS, as soon as one shared secret has been generated, the code won't respond to more (n - t) messages from the other participants which do not have their complete share yet.
This should be allowed instead:
+ **Participate to the key generation**: 
We definitely want to allow all participants to be included in the distributed key, so it's something we need to handle. Avoid things like `if jv.ltssInit { return error }`, but rather check if we already received a message from the same address or not, and reply correctly if it's the first message. 
+ **Participate to the signature**: 
  - Do participants that were late during the generation of the random distributed secret should be kept out ? If one "random secret generation" message comes after the recipient already received at least t of them, I think it should not be harmful to actually answer back. The reason why is that 1) this behavior is not illegal, and 2) it's actually re-enforcing the signature protocol: better to have `t+1` signers than `t` signers.
  - Responding to a partial signature request (so when participants actually  "sign" with their shares) **after** the partial signature has already been made (i.e. one already received at least t partial signatures) should be a "NOP".

**Comment by jeffallen** [comment]
@nikkolasg can this be closed?

**Comment by jeffallen** [comment]
@nikkolasg says this can be closed due to age, but it will likely raise it's head again someday.
