### ISSUE TITLE
More options for pop-party

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#818]
In chronological order, I propose:
1. #905 - getting to know the repos
2. #907 - start coding in cothority/onet
3. #906 - more coding in cothority/onet
4. #910 - eventually do something in the frontend?
5. #911 - create a nodejs module
6. #908 - first work on the theory, then implement it
7. #909 - desert....

**Comment by nikkolasg** [comment]
You should do a Epic issue for this one, looks like a big one !

**Comment by ineiti** [comment]
Yes, perhaps with one of the summer-interns.
