### ISSUE TITLE
Monitor: Discard n slowest measures

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#82]
Because some of the runs take a lot more time in some special cases, we'd like to measure only the fastest measurements. So instead of only dropping the first measurement, drop the 'n' slowest measurements, where 'n' is a variable available on the command-line or in the configuration-script.

**Comment by nikkolasg** [comment]
We can take the lower and upper 90-percentile of the data, that way we have no lower nor higher extremas

**Comment by ineiti** [comment]
OK - would be nice to be able to select:

- discardMax - how many of the maximum values to discard
- discardMin - how many of the minimum values to discard

**Comment by ineiti** [comment]
Closed by #91
