### ISSUE TITLE
Reduce memory usage of conode

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#823]
Now: conode needs a server with at least 2GB of RAM, else it crashes after some time
Wanted: conode runs with 512MB of RAM on server, or 1GB of RAM
Actions: check memory-consumption and if we have a memory-leak

**Comment by nikkolasg** [comment]
Some relevant links to find out where it happens:
 + https://groups.google.com/forum/#!topic/golang-nuts/a-OQwtVARdE
 + https://husobee.github.io/golang/memory/leak/2016/02/11/go-mem-leak.html

It can be quite tricky. If you ever fall on oom panic again, it'd be nice to copy paste the output here. I'd be happy to help, once I get back from my holidays.

**Comment by jeffallen** [comment]
This was fixed a while ago.
