### ISSUE TITLE
Startup-check

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#824]
When installing a conode, some things should be checked:
- enough memory available
- can connect to itself on the public address (can fail in case of NAT)

**Comment by nikkolasg** [comment]
> can connect to itself on the public address (can fail in case of NAT)

And what should happen in this case ? I don't this it should be an error at least.

**Comment by ineiti** [comment]
Write a big warning.

**Comment by ineiti** [comment]
We discussed this with Nicolas about the memory-detection. It should detect the system's memory and then warn:
- if <= 512MB that it's too little
- if <= 1024MB that another GB would be nice
- nothing if >= 2048MB
And always write that the memory-consumption is another issue that will be fixed soon, hopefully ;)
