### ISSUE TITLE
Clean up skipchains

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#835]
Things that the skipchain should be doing:
- [x] use _real_ forward-links
- [x] allow for more than one child
- [x] get signature from previous block
- [x] allow for more than one verification function

This is for v2, as it changes the api too much:

- [x] drop distinction between roster/data skipblocks
- [x] simplify api to the skipchain

**Comment by nikkolasg** [comment]
> allow for more than one child

What does that mean ?

Regarding the "simplify api to the skipchain", I'd like to ask the question if, when asking the service to add a new block, if it's needed to give the latest block also in the function call. If anyway, a new block is appended to the latest, then there should not be a need to give the latest (?).

**Comment by ineiti** [comment]
`more than one child` -> we have a 2-dimensional structure: the skipchains, and a hierarchy: the root-chain is the parent of the configuration-chain. The configuration-chain has data-chains as children.

**Comment by ineiti** [comment]
For some kind of chains it makes sense that we have to give the latest block, to be sure we're adding a block in a correct order. For other kind of chains it doesn't matter. So there should be both possibilities.

**Comment by nikkolasg** [comment]
> For some kind of chains, it makes sense that we have to give the latest block, to be sure we're adding a block in a correct order.

Do you have an example on that kind of chains ? I fail to see the reason ( can propbably say IRL)

**Comment by ineiti** [comment]
If you have the ssh-keys set up with CISC, let's say in DEDIS, and we keep a threshold of 2. If we have our whole team of 8 people that means that different part of the team can evolve the keysets independently from each other. 

But as the block saves the _state_, and not the _changes_, one set of developers might erase keys that are added by another set of developers.

```
State 1: key 1, key 2
Dev1 and Dev2 add key3 ->
State 2: key 1, key 2, key 3
But Dev3 and Dev4 don't update and want to add key 4 ->
State 3: key 1, key 2, key 4
```

Now you say: _but they have to update before adding their keys_.
And my reply: _this is assured by giving the latest block in the store_skipblock_

**Comment by nikkolasg** [comment]
Ok thanks for the detailled explanation.
From what I see, it seems that you enforce the `Client` to *retrieve* the latest block (At least I hope, that the `AddNewBlock` call returns an error if the latest given in argument is not the latest?). But the `Client` is not enforced to anything else, so developers can still erase Key 3 the same way as before if they give an updated "latest" block...
So I'm still not sure about this trick of forcing the user to be up-to-date (thus adding more actions on the `Client`'s side) while it does not prevent any "bad" actions. I think this should be handled at a higher level (a cisc `Client` should make sure it's not erasing keys etc) or with a future scripting / smart contract type of code.

**Comment by ineiti** [comment]
Moved to #858, #859 and #863
