### ISSUE TITLE
Debug Root

### ISSUE THREAD

**Issue by nikkolasg** [DeDiS/cothority#85]
It would be nice to have a dbg.PrintRoot or something, so we don't have a to play with the levels to get important informations.

**Comment by ineiti** [comment]
either ```dbg.PrintRoot``` or the ```forkexec``` could use a different debug-level for the root-node

**Comment by nikkolasg** [comment]
We could but then we restrict ourselves to the deterlab, then we'd have to change for localhost and for future platforms.

**Comment by ineiti** [comment]
How can we define better who is root? Can we have another definition? Who says some process is 'special'? Where is this defined?

All platforms have to call the processes with special flags - for the moment we have 'amroot' - we could use that one. I think it's used in both localhost and deterlab.

**Comment by nikkolasg** [comment]
The amroot flag is good enough. But for the moment I think this flag is generated by the platform themselves, not the actual application. It should be the application which says which hosts will be the root.
But amroot flag is good enough for now !
