### ISSUE TITLE
Monitor: take all fields that we receive

### ISSUE THREAD

**Issue by nikkolasg** [DeDiS/cothority#87]
In monitor remove the extraFields and additionals measures so that it displays every fields that it gets and every measures it receives.

**Comment by nikkolasg** [comment]
In fact, I did not think about it before but there exists an incompatibility between this feature and the fact that we want the header of the CSV already written to file before any tests have been made. Either we wait for the first measure to arrive and display all the fields in the header (Still have to be careful that we do not write send new measures for subsequents tests), or we simply continue specifying which fields exists in our tests results.

**Comment by ineiti** [comment]
No problem if the header comes with the first line of measures.

**Comment by ineiti** [comment]
Closed by #94
