### ISSUE TITLE
skipchains - access control

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#872]
Now: With the skipchain-service, everybody has the right to add a new skipchain. This can get out of hand if people start to `spam` our conodes.

Wanted: Access Control of who has the right to add skipchains

How: 
1. Per default the skipchains are in `allow everything` mode.
2. `scmgr` can be used to create an `acl`-skipchain (identified by an `ACLVerifier`-function) that creates a private/public keypair and stores the public key on the skipchain
  1. other admins can ask to be added to that skipchain, similar to `cisc`
  2. any admin can create an additional private/public key-pair with an acl that defines:
    - how many skipchains the user is allowed to create
    - maximum size of the skipblocks
3. `scmgr` can use a user-private-key to create a new skipchain on the conodes

Questions (add if you have more):
- 1 - should `allow everything` be the default, or `disallow everything`?
- 2.1 - Can we merge this `add admins`-function with what is in `cisc`?

**Comment by hsluoyz** [comment]
Hi, I'm the author of [Casbin](https://github.com/casbin/casbin). It is an authorization library that supports models like MAC, RBAC, ABAC.

Casbin has many features. Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database.

So please consider using Casbin when the skipchain service implements access control security. Also let me know if there's any question:)

**Comment by ineiti** [comment]
Skipchains won't have access-control, but will be controlled by other services. scmgr will disappear, and services like `identity` or `ocs` that use the skipchains will have to do the access-control there.
