### ISSUE TITLE
Add key/value to ServerIdentity

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#877]
We need to be able to store additional data in the `ServerIdentity`:
- tls-certificate
- description
- version

and probably others. A simple solution would be to have a `[]KeyValue{Key string, Value string}`. I put a slice for reproducible hashing without having to sort a map.

**Comment by nikkolasg** [comment]
> We need to be able to store additional data in the ServerIdentity:

We can also think of the problem as:
What is the identifier of a conode and can we only use that in our `Roster` and `Tree` structures (and in almost all our protocols) ? Where should we store all the conode informations and how to retrieve it easily from anywhere in the stack from this identifier, or other criteria (think "yellow pages") ?
I'm very concerned about putting all informations in one struct and using that same struct everywhere in our Roster / Tree definitions + protocols. Seems a huge loss of space / bandwidth / perf  and not in the spirit of modularization where each part of code should only get what it needs.

**Comment by ineiti** [comment]
Should be linked with config.v2

**Comment by jeffallen** [comment]
While waiting for the clear use case that drives it, closing.
