### ISSUE TITLE
Add onet/graph setup

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#878]
Now: we have `Roster` for a general listing of nodes and `Tree` for the description of the connections between the nodes.

Wanted: add a `Graph` with more flexible description of the connections between the nodes.

Used in: `prifi`, `medco`, others

**Comment by nikkolasg** [comment]
+1000 for that. 
I think it may be possible to change the `Tree` as a specialization of a `Graph` so it is retrocompatible with old code and new code can use the `Graph`. Anyway, it's definitely a must-have, we should have a meeting on that !

**Comment by ineiti** [comment]
I thought you'd like it ;)
