### ISSUE TITLE
replace md5 with shasum or other

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#912]
The `test.sh`-file uses `md5` to compare files, but this doesn't exist on linux (windows?) - replace `md5` with `shasum`, `cmp` or `diff` and verify it exists on both.

**Comment by nikkolasg** [comment]
Or using a language provided everywhere such as python:
```
printf "import hashlib\nprint(hashlib.sha256(b'hello').hexdigest())" | python3
```

**Comment by ineiti** [comment]
I'm sure you can get it incompatible between python2 and python3 ;) `cmp` seems to be the most short, appropriate, present and useful tool here.

**Comment by nikkolasg** [comment]
? Python2 is available everywhere so if we default to python2, there's no problems.

But I did not know `cmp` at all ! It's real nice and indeed perfect for the job ;)
