### ISSUE TITLE
Need blocking of skipblocks during BFTCosi

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#913]
When two clients ask to add a new block in parallel, skipblock will fail:

Given 3 nodes (node0..node2) and a block A
t0: Client1 asks node0 to add a block B to A
t0: Client2 asks simultaneously node5 to add a block C to A
t1: node0 asks nodes1..2 to check validity of block B
t1: node2 asks nodes0..1 to check validity of block C and create collective signature
t2: nodes0..2 approve block B and create collective signature, sending it to node0
t2: nodes0..2 approve block C and create collective signature, sending it to node2
t3: node0 propagates block A, B through system
t3: node2 propagates block A, C through system
t4: node1 wants to add block D to block A, but this will fail, because this block will not be approved, due to the presence of B or C.

At t2 we created a fork in our beloved skipchain, because we collectively signed two different future blocks :( 
My first idea is to use a `signatureinprogress`-list of blocks that are about to be signed, and then look up this list in the BFT-verification function. But this list is quite brittle, as we have to take care to remove failed signature attempts from it.

**Comment by nikkolasg** [comment]
> t2: nodes0..2 approve block C and create collective signature, sending it to node2
Why does nodes0..2 approve the block C since they already approved the block B just before ? the verification function associated with CoSi should take care to make no fork IIRC. Basically, the ver. function should check that
1) the new block is "correct"
2) no BFT-CoSi were run for another block that has the same predecessor

I'm surely missing something here. but what ? :D

**Comment by ineiti** [comment]
You didn't miss anything - you're right on the spot! Problem was, that the check that no other block with the same predecessor has been processed (your 2.) depended on `t3` above, which means for two parallel requests, that they will both be accepted and collectively signed!

Using my PR this will not happen anymore. But now you can have a valid block that fails, because somebody else was faster than you. So you have to re-try with the updated block-list. This is what `TestService_WriteParallelBlocks` does.

**Comment by ineiti** [comment]
After discussion with Bryan, we should:
1. only allow the leader to propose new blocks (then locking gets simple)
2. have the other nodes collect transactions that the leader will collect and propose (not implemented here).
