### ISSUE TITLE
Use deploy with protected ssh-key

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#93]
When the ssh-key is protected by a password, ```deploy``` can't connect to the users.deterlab.net-server without having to ask for the password all the time.

Use ```ssh-agent``` or any other convenient tool to bypass the password-request.

**Comment by Daeinar** [comment]
On OSX it is sufficient to execute

```
ssh-add path/to/private/key
```

and then enter the password for the ssh key to resolve this issue.

**Comment by ineiti** [comment]
is this for the session, one hour or for ever?

**Comment by Daeinar** [comment]
The passphrase is stored in the OSX keychain, i.e. it depends on how you handle keychain unlocking. See: https://help.github.com/articles/working-with-ssh-key-passphrases/

**Comment by Daeinar** [comment]
Btw. the default OSX `ssh-add` command seems not to have a `-K` flag as mentioned in the article.

**Comment by ineiti** [comment]
OK, can you add that to the deploy/README in an appropriate place?

**Comment by ineiti** [comment]
And make a pull-request?

**Comment by Daeinar** [comment]
There's no deploy/README file yet. Should I add one or should I include that ssh-comment in the main README https://github.com/DeDiS/cothority/blob/master/README.md ?

**Comment by ineiti** [comment]
As we have now two separate apps in the tree (app/conode and deploy), we could split the cothority/README to cothority/app/conode/README (already exists) and cothority/deploy/README and then just give a short overview in the cothority/README over the two apps.

**Comment by Daeinar** [comment]
Okay, I'll take care of that later today.

**Comment by ineiti** [comment]
Closed by #106
