### ISSUE TITLE
Deploy: Remove first cleanup

### ISSUE THREAD

**Issue by ineiti** [DeDiS/cothority#96]
When deploy is first started, it calls ```users -kill``` to clean up. But the config.toml is not copied yet, so the wrong experiment might be cleaned up.

Either copy over config.toml from the start, or remove the first cleanup before compiling the app.

**Comment by Daeinar** [comment]
The first cleanup was removed in #102, right? I.e. this issue can be closed?

**Comment by ineiti** [comment]
Yep, close it.

**Comment by Daeinar** [comment]
Resolved in #102.
