### ISSUE TITLE
Fix formatting of code-sections in README

### ISSUE THREAD

**Issue by Daeinar** [DeDiS/cothority#97]
There's an issue with mutli-line code formatting in the conode [README](https://github.com/DeDiS/cothority/blob/development/app/conode/README.md).

**Comment by ineiti** [comment]
Care to be more specific?

**Comment by Daeinar** [comment]
Checkout the lower half of the README. Multi-line code should have a newline after the first three apostrophes, but in the **Compile conode** section it doesn't and therefore the formatting breaks.

**Comment by ineiti** [comment]
Updated the issue to reflect what needs to be done instead of what is broken.

**Comment by Daeinar** [comment]
Okay, thanks. I'll send a pull request.

**Comment by Daeinar** [comment]
Hmm btw. there is an incomplete sentence in the **Compile Conode** section. 

"We suppose you have a running ... (?)"

Did you mean a running Go implementation?

**Comment by Daeinar** [comment]
This issue can be closed right?
