### ISSUE TITLE
Skipchain tests sometimes timesout 

### ISSUE THREAD

**Issue by kc1212** [dedis/cothority#983]
For example here https://travis-ci.org/dedis/cothority/builds/318483529. Concretely, it happens on `TestService_ParallelStore`. A workaround is to add more delay to https://github.com/dedis/cothority/blob/c0eb4d6a4147f5fae87cc5f03c8ae1515487f7c4/skipchain/skipchain_test.go#L488

A thorough investigation is needed to understand the exact issue.

**Comment by jeffallen** [comment]
We will attack flakiness when we see it.
