### ISSUE TITLE
Clean up usage of .config in apps

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#985]
.config should only hold text-files that are editable by users. As the app-config files are binary only, we should move them to .local/share or make them text-files, too.

Also to rationalise: onet/app's GetDefaultConfigFile and onet's dbPathFromEnv

Also capitalization: dbPathFromEnv on OSX makes ~/Library/Conode, but if you run "run_conode.sh public", it creates the private.toml file in ~/Library/conode (lower case). It works because the OSX filesystem is case insensitive (blech).

**Comment by kc1212** [comment]
Relevant documentation - https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by jeffallen** [comment]
@kc1212 says that apps should be writing into .local/share on linux.

**Comment by kc1212** [comment]
I did some research on where these config and app data files are stored on different operating systems.

For Linux it's pretty well defined by the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html). To summarize, app data (usually not human readable, e.g. the database) should go into `$HOME/.local/share/appname` and app configuration (human readable) should go into `$HOME/.config/appname`, unless these are redefined by the XDG environment variable.

For macOS, there is an [official documentation](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1) that explains how to store application data. From my understanding, for our use case, all the files should go into something like `~/Library/Application Support/appname`. I propose we store config files in `~/Library/Application Support/appname` and the database files in `~/Library/Application Support/appname/Data`.

Finally, on Windows, there's basically a single place for application data and that's in `%AppData%` - [documentation](https://technet.microsoft.com/fr-fr/library/cc766489(v=ws.10).aspx). So I propose we do something similar to macOS - `%AppData%/appname` for configs and `%AppData%/appname/Data` for the database. However, I won't be able to test this very well without a Windows machine.

Should I proceed like this @jeffallen @ineiti ?
